# Generated by Django 5.2.17 on 2026-09-24 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_default_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_confirmation',
            },
        ),
    ]
