# Generated by Django 5.2.17 on 2026-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_storefront_permissions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-occurred_at', '-id'], name='audit_time_id_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-occurred_at', '-id'], name='audit_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_code', '-occurred_at', '-id'], name='audit_action_time_idx'),
        ),
    ]
