# Generated by Django 5.2.17 on 2026-09-28 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditlog_audit_time_id_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_read_quota',
                'constraints': [models.UniqueConstraint(fields=('actor', 'scope', 'window_start'), name='admin_read_quota_unique'), models.CheckConstraint(condition=models.Q(('scope__in', ['audit', 'business'])), name='admin_read_quota_scope'), models.CheckConstraint(condition=models.Q(('count__lte', 60)), name='admin_read_quota_count')],
            },
        ),
    ]
