# Generated by Django 5.2.17 on 2026-09-25 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_asset_product_main_image_product_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(default='HOME', max_length=5)),
                ('name', models.CharField(default='首页', max_length=80)),
                ('draft_revision', models.PositiveIntegerField(default=1)),
                ('draft_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'micro_page',
            },
        ),
        migrations.CreateModel(
            name='PageConfigVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('config_json', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_config_version',
            },
        ),
        migrations.CreateModel(
            name='PageDraftAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'page_draft_asset',
            },
        ),
        migrations.CreateModel(
            name='PagePublishRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_publish_request',
            },
        ),
        migrations.CreateModel(
            name='PageVersionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'page_version_asset',
            },
        ),
        migrations.CreateModel(
            name='PagePublication',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='pages.micropage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'page_publication',
            },
        ),
        migrations.AddConstraint(
            model_name='micropage',
            constraint=models.UniqueConstraint(condition=models.Q(('page_type', 'HOME')), fields=('page_type',), name='one_home_page'),
        ),
        migrations.AddConstraint(
            model_name='micropage',
            constraint=models.CheckConstraint(condition=models.Q(('page_type__in', ['HOME', 'MICRO'])), name='known_page_type'),
        ),
        migrations.AddField(
            model_name='pageconfigversion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pages.micropage'),
        ),
        migrations.AddField(
            model_name='pageconfigversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagedraftasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='pagedraftasset',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.micropage'),
        ),
        migrations.AddField(
            model_name='pagepublishrequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagepublishrequest',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.micropage'),
        ),
        migrations.AddField(
            model_name='pagepublishrequest',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.pageconfigversion'),
        ),
        migrations.AddField(
            model_name='pageversionasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='pageversionasset',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.pageconfigversion'),
        ),
        migrations.AddField(
            model_name='pagepublication',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.pageconfigversion'),
        ),
        migrations.AddConstraint(
            model_name='pageconfigversion',
            constraint=models.UniqueConstraint(fields=('page', 'revision'), name='unique_page_revision'),
        ),
        migrations.AddConstraint(
            model_name='pagedraftasset',
            constraint=models.UniqueConstraint(fields=('page', 'asset'), name='unique_page_draft_asset'),
        ),
        migrations.AddConstraint(
            model_name='pagepublishrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'page', 'key'), name='unique_page_publish_key'),
        ),
        migrations.AddConstraint(
            model_name='pageversionasset',
            constraint=models.UniqueConstraint(fields=('version', 'asset'), name='unique_page_version_asset'),
        ),
    ]
