# Generated by Django 5.2.17 on 2026-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageconfigversion',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
