# Generated by Django 5.2.17 on 2026-09-25 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_startup(apps, schema_editor):
    StartupConfig = apps.get_model("pages", "StartupConfig")
    StartupPublication = apps.get_model("pages", "StartupPublication")
    config = StartupConfig.objects.using(schema_editor.connection.alias).create(id=1)
    StartupPublication.objects.using(schema_editor.connection.alias).create(config=config)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_asset_kind'),
        ('pages', '0003_pageconfigversion_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('draft_revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallback_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startup_fallback_drafts', to='catalog.asset')),
                ('gif_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startup_gif_drafts', to='catalog.asset')),
            ],
            options={
                'db_table': 'startup_config',
            },
        ),
        migrations.CreateModel(
            name='StartupConfigVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('fallback_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_fallback_versions', to='catalog.asset')),
                ('gif_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startup_gif_versions', to='catalog.asset')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_config_version',
            },
        ),
        migrations.CreateModel(
            name='StartupPublishRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.startupconfigversion')),
            ],
            options={
                'db_table': 'startup_publish_request',
            },
        ),
        migrations.CreateModel(
            name='StartupPublication',
            fields=[
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='pages.startupconfig')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.startupconfigversion')),
            ],
            options={
                'db_table': 'startup_publication',
            },
        ),
        migrations.AddConstraint(
            model_name='startupconfig',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='one_startup_config'),
        ),
        migrations.AddConstraint(
            model_name='startupconfigversion',
            constraint=models.UniqueConstraint(fields=('revision',), name='unique_startup_revision'),
        ),
        migrations.AddConstraint(
            model_name='startuppublishrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'key'), name='unique_startup_publish_key'),
        ),
        migrations.RunPython(seed_startup, migrations.RunPython.noop),
    ]
