# Generated by Django 5.2.17 on 2026-09-27 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



def backfill_publications(apps, schema_editor):
    for model in ("PagePublication", "StartupPublication"):
        publication = apps.get_model("pages", model)
        publication.objects.using(schema_editor.connection.alias).filter(
            current_version__isnull=False).update(revision=1)


IMMUTABLE_SQL = """
CREATE FUNCTION protect_content_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Published content versions are immutable' USING ERRCODE = '23514';
END;
$$;
CREATE TRIGGER page_version_immutable BEFORE UPDATE OR DELETE ON page_config_version
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE TRIGGER startup_version_immutable BEFORE UPDATE OR DELETE ON startup_config_version
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE TRIGGER page_version_asset_immutable BEFORE UPDATE OR DELETE ON page_version_asset
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE FUNCTION protect_page_publication_target() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.current_version_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM page_config_version WHERE id = NEW.current_version_id AND page_id = NEW.page_id
    ) THEN
        RAISE EXCEPTION 'Publication version belongs to another page' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER page_publication_target BEFORE INSERT OR UPDATE ON page_publication
FOR EACH ROW EXECUTE FUNCTION protect_page_publication_target();
"""
REVERSE_SQL = """
DROP TRIGGER page_publication_target ON page_publication;
DROP FUNCTION protect_page_publication_target();
DROP TRIGGER page_version_asset_immutable ON page_version_asset;
DROP TRIGGER startup_version_immutable ON startup_config_version;
DROP TRIGGER page_version_immutable ON page_config_version;
DROP FUNCTION protect_content_version();
"""

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_startupconfig_startupconfigversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepublication',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagepublishrequest',
            name='result',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='startuppublication',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startuppublishrequest',
            name='result',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(backfill_publications, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ContentRollbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=7)),
                ('object_id', models.CharField(max_length=36)),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_rollback_request',
                'constraints': [models.UniqueConstraint(fields=('actor', 'domain', 'object_id', 'key'), name='unique_content_rollback_key')],
            },
        ),
        migrations.RunSQL(IMMUTABLE_SQL, REVERSE_SQL),
    ]
