# Generated by Django 5.2.17 on 2026-09-28 01:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_storefront(apps, schema_editor):
    Config = apps.get_model('pages', 'StorefrontConfig')
    Publication = apps.get_model('pages', 'StorefrontPublication')
    alias = schema_editor.connection.alias
    navigation = {'items': [
        {'key': key, 'label': label, 'iconAssetId': None, 'selectedIconAssetId': None}
        for key, label in (('HOME', '首页'), ('CATEGORY', '分类'), ('CART', '购物车'), ('ME', '我的'))]}
    service = {'enabled': False, 'mode': None, 'phone': None, 'qrAssetId': None,
               'prompt': '', 'iconAssetId': None}
    for domain, config in (('navigation', navigation), ('customer_service', service)):
        row = Config.objects.using(alias).create(domain=domain, draft_config=config)
        Publication.objects.using(alias).create(config=row)


GUARDS = """
CREATE FUNCTION protect_storefront_publication_target() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.current_version_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM storefront_version WHERE id = NEW.current_version_id AND config_id = NEW.config_id
    ) THEN
        RAISE EXCEPTION 'Storefront publication version belongs to another domain' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER storefront_publication_target BEFORE INSERT OR UPDATE ON storefront_publication
FOR EACH ROW EXECUTE FUNCTION protect_storefront_publication_target();
CREATE TRIGGER storefront_publication_revision BEFORE INSERT OR UPDATE ON storefront_publication
FOR EACH ROW EXECUTE FUNCTION protect_publication_revision();
CREATE TRIGGER storefront_publication_retention BEFORE UPDATE OR DELETE ON storefront_publication
FOR EACH ROW EXECUTE FUNCTION protect_publication_retention();
CREATE TRIGGER storefront_version_immutable BEFORE UPDATE OR DELETE ON storefront_version
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE TRIGGER storefront_version_asset_immutable BEFORE UPDATE OR DELETE ON storefront_version_asset
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE TRIGGER storefront_operation_immutable BEFORE UPDATE OR DELETE ON storefront_operation
FOR EACH ROW EXECUTE FUNCTION protect_content_version();
CREATE FUNCTION protect_storefront_singleton() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Storefront singleton cannot be removed' USING ERRCODE = '23514';
END;
$$;
CREATE TRIGGER storefront_config_retention BEFORE DELETE ON storefront_config
FOR EACH ROW EXECUTE FUNCTION protect_storefront_singleton();
"""

UNGUARD = """
DROP TRIGGER storefront_config_retention ON storefront_config;
DROP FUNCTION protect_storefront_singleton();
DROP TRIGGER storefront_operation_immutable ON storefront_operation;
DROP TRIGGER storefront_version_asset_immutable ON storefront_version_asset;
DROP TRIGGER storefront_version_immutable ON storefront_version;
DROP TRIGGER storefront_publication_retention ON storefront_publication;
DROP TRIGGER storefront_publication_revision ON storefront_publication;
DROP TRIGGER storefront_publication_target ON storefront_publication;
DROP FUNCTION protect_storefront_publication_target();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_asset_library_indexes'),
        ('pages', '0007_publication_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontConfig',
            fields=[
                ('domain', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('draft_revision', models.PositiveIntegerField(default=1)),
                ('draft_config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storefront_config',
            },
        ),
        migrations.CreateModel(
            name='StorefrontDraftAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'storefront_draft_asset',
            },
        ),
        migrations.CreateModel(
            name='StorefrontOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=8)),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storefront_operation',
            },
        ),
        migrations.CreateModel(
            name='StorefrontVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('config_json', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storefront_version',
            },
        ),
        migrations.CreateModel(
            name='StorefrontVersionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'storefront_version_asset',
            },
        ),
        migrations.CreateModel(
            name='StorefrontPublication',
            fields=[
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='pages.storefrontconfig')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'storefront_publication',
            },
        ),
        migrations.AddConstraint(
            model_name='storefrontconfig',
            constraint=models.CheckConstraint(condition=models.Q(('domain__in', ['navigation', 'customer_service'])), name='known_storefront_domain'),
        ),
        migrations.AddField(
            model_name='storefrontdraftasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='storefrontdraftasset',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.storefrontconfig'),
        ),
        migrations.AddField(
            model_name='storefrontoperation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefrontoperation',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.storefrontconfig'),
        ),
        migrations.AddField(
            model_name='storefrontversion',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pages.storefrontconfig'),
        ),
        migrations.AddField(
            model_name='storefrontversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storefrontoperation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.storefrontversion'),
        ),
        migrations.AddField(
            model_name='storefrontversionasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='storefrontversionasset',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.storefrontversion'),
        ),
        migrations.AddField(
            model_name='storefrontpublication',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.storefrontversion'),
        ),
        migrations.AddConstraint(
            model_name='storefrontdraftasset',
            constraint=models.UniqueConstraint(fields=('config', 'asset'), name='unique_storefront_draft_asset'),
        ),
        migrations.AddConstraint(
            model_name='storefrontversion',
            constraint=models.UniqueConstraint(fields=('config', 'revision'), name='unique_storefront_revision'),
        ),
        migrations.AddConstraint(
            model_name='storefrontoperation',
            constraint=models.UniqueConstraint(fields=('config', 'actor', 'action', 'key'), name='unique_storefront_operation_key'),
        ),
        migrations.AddConstraint(
            model_name='storefrontoperation',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['publish', 'rollback'])), name='known_storefront_action'),
        ),
        migrations.AddConstraint(
            model_name='storefrontversionasset',
            constraint=models.UniqueConstraint(fields=('version', 'asset'), name='unique_storefront_version_asset'),
        ),
        migrations.RunPython(seed_storefront, migrations.RunPython.noop),
        migrations.RunSQL(GUARDS, UNGUARD),
    ]
