# Generated by Django 5.2.17 on 2026-10-10 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_storefrontconfig_storefrontdraftasset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCopyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_requests', to='pages.micropage')),
            ],
            options={
                'db_table': 'page_copy_request',
                'constraints': [models.UniqueConstraint(fields=('actor', 'source_page', 'key'), name='unique_page_copy_key')],
            },
        ),
    ]
