# Generated by Django 5.2.17 on 2026-09-24 09:17

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'member_grade',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=8)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['parent_id', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_no', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('fulfillment_kind', models.CharField(choices=[('SHIP', 'Ship'), ('REDEEM', 'Redeem')], max_length=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ON_SALE', 'On sale'), ('OFF_SALE', 'Off sale')], default='DRAFT', max_length=8)),
                ('description_html', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(max_length=64)),
                ('spec_key', models.CharField(max_length=150)),
                ('list_price_fen', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_status', models.CharField(choices=[('ON_SALE', 'On sale'), ('OFF_SALE', 'Off sale')], default='OFF_SALE', max_length=8)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.product')),
            ],
            options={
                'db_table': 'sku',
            },
        ),
        migrations.CreateModel(
            name='SkuGradePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_fen', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.membergrade')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_prices', to='catalog.sku')),
            ],
            options={
                'db_table': 'sku_grade_price',
            },
        ),
        migrations.CreateModel(
            name='SkuUnitVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_unit', models.CharField(max_length=30)),
                ('sale_unit', models.CharField(max_length=30)),
                ('ratio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_versions', to='catalog.sku')),
            ],
            options={
                'db_table': 'sku_unit_version',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='current_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='catalog.skuunitversion'),
        ),
        migrations.CreateModel(
            name='SpecAxis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_axes', to='catalog.product')),
            ],
            options={
                'db_table': 'product_spec_axis',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.specaxis')),
            ],
            options={
                'db_table': 'product_spec_option',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkuSpecSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='catalog.sku')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.specaxis')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.specoption')),
            ],
            options={
                'db_table': 'sku_spec_selection',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='category_not_self_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='product_cat_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('product_no'), name='unique_product_no_upper'),
        ),
        migrations.AddConstraint(
            model_name='skugradeprice',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('sku', 'grade'), name='unique_active_sku_grade_price'),
        ),
        migrations.AddConstraint(
            model_name='skugradeprice',
            constraint=models.CheckConstraint(condition=models.Q(('price_fen__gte', 0)), name='sku_grade_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='skuunitversion',
            constraint=models.CheckConstraint(condition=models.Q(('ratio__gte', 1)), name='sku_unit_ratio_positive'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['product', 'sale_status'], name='sku_prod_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('sku_code'), name='unique_sku_code_upper'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('product', 'spec_key'), name='unique_product_spec_key'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(condition=models.Q(('list_price_fen__gte', 0)), name='sku_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='specaxis',
            constraint=models.UniqueConstraint(fields=('product', 'sort_order'), name='unique_product_axis_order'),
        ),
        migrations.AddConstraint(
            model_name='specoption',
            constraint=models.UniqueConstraint(fields=('axis', 'sort_order'), name='unique_axis_option_order'),
        ),
        migrations.AddConstraint(
            model_name='skuspecselection',
            constraint=models.UniqueConstraint(fields=('sku', 'axis'), name='unique_sku_axis_selection'),
        ),
    ]
