# Generated by Django 5.2.17 on 2026-09-24 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_member_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCategoryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('result', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_batch_category_request',
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'key'), name='unique_batch_category_key')],
            },
        ),
    ]
