# Generated by Django 5.2.17 on 2026-09-24 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_batchcategoryrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5)),
                ('content_type', models.CharField(max_length=32)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=120)),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_asset',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_for_products', to='catalog.asset'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_for_products', to='catalog.asset'),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.asset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product')),
            ],
            options={
                'db_table': 'product_gallery_image',
                'constraints': [models.UniqueConstraint(fields=('product', 'position'), name='unique_product_gallery_position'), models.UniqueConstraint(fields=('product', 'asset'), name='unique_product_gallery_asset')],
            },
        ),
    ]
