# Generated by Django 5.2.17 on 2026-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_asset_product_main_image_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('GIF', 'Animated GIF')], max_length=5),
        ),
    ]
