# Generated by Django 5.2.17 on 2026-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sku_driven_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='redeem_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
