# Generated by Django 5.2.17 on 2026-10-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_manual_off_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_conversion',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
