# Generated by Django 5.2.17 on 2026-09-28 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_operation_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORDER_PAID', 'ORDER_PAID'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('REFUND_SUCCEEDED', 'REFUND_SUCCEEDED')], max_length=24)),
                ('source_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('identity_digest', models.CharField(blank=True, max_length=64)),
                ('template_id_snapshot', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='BLOCKED', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'subscription_message_task',
            },
        ),
        migrations.CreateModel(
            name='MessageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('lease_token', models.UUIDField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(default='IN_FLIGHT', max_length=16)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='notifications.messagetask')),
            ],
            options={
                'db_table': 'subscription_message_attempt',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(choices=[('ORDER_PAID', 'ORDER_PAID'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('REFUND_SUCCEEDED', 'REFUND_SUCCEEDED')], max_length=24)),
                ('template_id', models.CharField(max_length=128)),
                ('identity_digest', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=8)),
                ('evidence_source', models.CharField(choices=[('SYNTHETIC_TEST', 'Synthetic test'), ('MINIPROGRAM', 'Mini Program')], max_length=24)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorization_grant', to='notifications.messagetask')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'subscription_grant',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_PAID', 'ORDER_PAID'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('REFUND_SUCCEEDED', 'REFUND_SUCCEEDED')], max_length=24)),
                ('wechat_app_id', models.CharField(max_length=64)),
                ('template_id', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_template',
                'constraints': [models.UniqueConstraint(fields=('event_type', 'wechat_app_id'), name='subscription_template_event_app_unique'), models.CheckConstraint(condition=models.Q(('enabled', False), models.Q(models.Q(('template_id', ''), _negated=True), models.Q(('wechat_app_id', ''), _negated=True)), _connector='OR'), name='subscription_enabled_binding_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='messagetask',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='subscription_task_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.UniqueConstraint(fields=('event_type', 'source_id'), name='subscription_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('ORDER_PAID', 'ORDER_SHIPPED', 'REFUND_SUCCEEDED'))), name='subscription_task_event_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['BLOCKED', 'READY', 'RESERVED', 'CLAIMED', 'RETRY_WAIT', 'UNKNOWN', 'FAILED', 'SIMULATED'])), name='subscription_task_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'BLOCKED'), models.Q(models.Q(('identity_digest', ''), _negated=True), models.Q(('template_id_snapshot', ''), _negated=True)), _connector='OR'), name='subscription_send_identity_ready'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', 3)), name='subscription_attempts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='messagetask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_token__isnull', False), ('lease_until__isnull', False), ('status__in', ['RESERVED', 'CLAIMED'])), models.Q(models.Q(('status__in', ['RESERVED', 'CLAIMED']), _negated=True), ('lease_token__isnull', True), ('lease_until__isnull', True)), _connector='OR'), name='subscription_task_lease_shape'),
        ),
        migrations.AddConstraint(
            model_name='messageattempt',
            constraint=models.UniqueConstraint(fields=('task', 'ordinal'), name='subscription_attempt_ordinal_unique'),
        ),
        migrations.AddConstraint(
            model_name='messageattempt',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['IN_FLIGHT', 'SIMULATED', 'RETRYABLE', 'PERMANENT', 'UNKNOWN'])), name='subscription_attempt_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='messageattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('outcome', 'IN_FLIGHT')), models.Q(models.Q(('outcome', 'IN_FLIGHT'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='subscription_attempt_finish_shape'),
        ),
        migrations.AddIndex(
            model_name='subscriptiongrant',
            index=models.Index(fields=['member', 'event_type', 'template_id', 'expires_at'], name='subscription_grant_match_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('ORDER_PAID', 'ORDER_SHIPPED', 'REFUND_SUCCEEDED'))), name='subscription_grant_event_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['ACCEPTED', 'REJECTED'])), name='subscription_grant_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_source__in', ['SYNTHETIC_TEST', 'MINIPROGRAM'])), name='subscription_grant_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('identity_digest', ''), _negated=True), name='subscription_grant_identity_set'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('observed_at'))), name='subscription_grant_expiry_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscriptiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('observed_at')), _connector='OR'), name='subscription_grant_revoke_valid'),
        ),
    ]
