# Generated by Django 5.2.17 on 2026-09-28 02:20

from django.db import migrations, models


def seed_candidates(apps, schema_editor):
    Draft = apps.get_model('notifications', 'SubscriptionTemplateDraft')
    for event in ('ORDER_PAID', 'ORDER_SHIPPED', 'REFUND_SUCCEEDED'):
        Draft.objects.using(schema_editor.connection.alias).get_or_create(event_type=event)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTemplateDraft',
            fields=[
                ('event_type', models.CharField(choices=[('ORDER_PAID', 'ORDER_PAID'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('REFUND_SUCCEEDED', 'REFUND_SUCCEEDED')], max_length=24, primary_key=True, serialize=False)),
                ('draft_app_id', models.CharField(blank=True, default='', max_length=64)),
                ('draft_template_id', models.CharField(blank=True, default='', max_length=128)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_template_draft',
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ('ORDER_PAID', 'ORDER_SHIPPED', 'REFUND_SUCCEEDED'))), name='subscription_draft_event_valid')],
            },
        ),
        migrations.RunPython(seed_candidates, migrations.RunPython.noop),
    ]
