import { createRouter, createWebHistory } from 'vue-router'

export const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', component: () => import('./views/DashboardView.vue'), meta: { title: '概览' } },
    { path: '/accounts', component: () => import('./views/AccountsView.vue'), meta: { title: '子账号', permission: 'account.read' } },
    { path: '/permission-groups', component: () => import('./views/GroupsView.vue'), meta: { title: '权限组', permission: 'permission.read' } },
    { path: '/audit-logs', component: () => import('./views/AuditView.vue'), meta: { title: '操作日志', permission: 'audit.read' } },
    { path: '/business/summary', component: () => import('./views/BusinessSummaryView.vue'), meta: { title: '经营统计', permission: 'business.report.read' } },
    { path: '/subscription-messages', component: () => import('./views/SubscriptionMessagesView.vue'), meta: { title: '订阅消息', permission: 'notification.read' } },
    { path: '/subscription-message-tasks', component: () => import('./views/SubscriptionMessageTasksView.vue'), meta: { title: '消息任务', permission: 'notification.read' } },
    { path: '/store/wechat-integration', component: () => import('./views/WechatIntegrationView.vue'), meta: { title: '小程序接入', permission: 'wechat.integration.read' } },
    { path: '/store/code-versions', component: () => import('./views/CodeVersionsView.vue'), meta: { title: '代码版本', permission: 'code.version.read' } },
    { path: '/assets', component: () => import('./views/AssetsView.vue'), meta: { title: '素材中心', permissionsAny: ['asset.read', 'asset.upload'] } },
    { path: '/catalog', component: () => import('./views/CatalogView.vue'), meta: { title: '商品管理', permission: 'catalog.read' } },
    { path: '/members', component: () => import('./views/MembersView.vue'), meta: { title: '会员', permission: 'member.read' } },
    { path: '/members/rules', component: () => import('./views/MemberRulesView.vue'), meta: { title: '等级与积分规则', permissionsAny: ['member.rules.read','member.rules.manage'] } },
    { path: '/members/:memberId', component: () => import('./views/MemberDetailView.vue'), meta: { title: '会员详情', permission: 'member.read' } },
    { path: '/coupons', component: () => import('./views/CouponsView.vue'), meta: { title: '优惠券活动', permission: 'coupon.read' } },
    { path: '/coupons/new', component: () => import('./views/CouponDetailView.vue'), meta: { title: '创建优惠券活动', permission: 'coupon.read' } },
    { path: '/coupons/:campaignId', component: () => import('./views/CouponDetailView.vue'), meta: { title: '优惠券活动详情', permission: 'coupon.read' } },
    { path: '/exchange-offers', component: () => import('./views/PointsExchangeView.vue'), meta: { title: '积分商城商品', permission: 'exchange.read' } },
    { path: '/exchange-offers/new', component: () => import('./views/PointsExchangeDetailView.vue'), meta: { title: '添加兑换商品', permission: 'exchange.read' } },
    { path: '/exchange-offers/:offerId', component: () => import('./views/PointsExchangeDetailView.vue'), meta: { title: '兑换商品配置', permission: 'exchange.read' } },
    { path: '/orders', component: () => import('./views/OrdersView.vue'), meta: { title: '订单管理', permission: 'order.read' } },
    { path: '/orders/:orderId', component: () => import('./views/OrderDetailView.vue'), meta: { title: '订单详情', permission: 'order.read' } },
    { path: '/aftersales', component: () => import('./views/AfterSalesView.vue'), meta: { title: '售后管理', permission: 'aftersale.read' } },
    { path: '/aftersales/:caseId', component: () => import('./views/AfterSaleDetailView.vue'), meta: { title: '售后详情', permission: 'aftersale.read' } },
    { path: '/redemptions', component: () => import('./views/RedemptionView.vue'), meta: { title: '到店核销', permission: 'fulfillment.redeem' } },
    { path: '/fulfillment/settings', component: () => import('./views/FulfillmentSettingsView.vue'), meta: { title: '履约设置', permission: 'fulfillment.settings.manage' } },
    { path: '/store/payments', component: () => import('./views/PaymentSettingsView.vue'), meta: { title: '付款配置', permission: 'payment.settings.manage' } },
    { path: '/inventory', component: () => import('./views/InventoryView.vue'), meta: { title: '库存管理', permission: 'inventory.read' } },
    { path: '/pages/home', component: () => import('./views/HomePageView.vue'), meta: { title: '首页装修', permission: 'page.read' } },
    { path: '/pages/micro', component: () => import('./views/MicroPageView.vue'), meta: { title: '独立微页面', permission: 'page.read' } },
    { path: '/store/info', component: () => import('./views/StoreInfoView.vue'), meta: { title: '店铺信息', permission: 'startup.read' } },
    { path: '/store/navigation', component: () => import('./views/NavigationView.vue'), meta: { title: '底部导航', permission: 'navigation.read' } },
    { path: '/store/customer-service', component: () => import('./views/CustomerServiceView.vue'), meta: { title: '客服悬浮入口', permission: 'customer_service.read' } },
    { path: '/:pathMatch(.*)*', redirect: '/' },
  ],
})
