from django.urls import path, re_path

from accounts import views
from accounts import audit_read
from catalog import views as catalog_views
from catalog import media_views
from pages import views as page_views
from pages import startup_views, history, storefront_views
from inventory import views as inventory_views
from checkout import views as checkout_views
from customers import views as customer_views
from customers import operation_views as member_views
from orders import views as order_views
from shipping import views as shipping_views
from payments import views as payment_views
from payments import wechat_views
from orders import admin_views as admin_order_views
from fulfillment import views as fulfillment_views

from aftersales import views as aftersale_views
from aftersales import return_views
from payments import refund_views
from payments import wechat_refund_views
from payments import business_read
from benefits import coupon_views
from points_exchange import views as exchange_views
from notifications import views as notification_views
from notifications import task_views as notification_task_views
from code_versions import views as code_version_views
from report_exports import views as export_views
from config.health import health_view

urlpatterns = [
    path("healthz", health_view),
    path("api/v1/admin/exports", export_views.exports_view),
    path("api/v1/admin/exports/<uuid:task_id>", export_views.export_detail_view),
    path("api/v1/admin/exports/<uuid:task_id>/download", export_views.export_download_view),
    path("api/v1/admin/code-versions", code_version_views.versions_view),
    path("api/v1/admin/code-versions/<uuid:version_id>", code_version_views.version_detail_view),
    path("api/v1/admin/code-sync-jobs", code_version_views.jobs_view),
    path("api/v1/admin/subscription-message-tasks", notification_task_views.tasks_view),
    path("api/v1/admin/subscription-message-tasks/<uuid:task_id>", notification_task_views.task_detail_view),
    path("api/v1/admin/subscription-message-tasks/<uuid:task_id>/recover-reservation",
         notification_task_views.recover_reservation_view),
    path("api/v1/admin/subscription-templates", notification_views.template_drafts_view),
    path("api/v1/admin/subscription-templates/<str:event_type>", notification_views.template_draft_view),
    path("api/v1/app/subscription-messages/availability", notification_views.public_availability_view),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/draft$", storefront_views.admin_view,
         {"operation": "draft"}),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/preview$", storefront_views.admin_view,
         {"operation": "preview"}),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/publish$", storefront_views.admin_view,
         {"operation": "publish"}),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/versions$", storefront_views.admin_view,
         {"operation": "versions"}),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/versions/"
            r"(?P<version_id>[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$",
         storefront_views.admin_view,
         {"operation": "versions"}),
    re_path(r"^api/v1/admin/(?P<segment>navigation|customer-service)/rollback$", storefront_views.admin_view,
         {"operation": "rollback"}),
    path("api/v1/app/storefront", storefront_views.public_view),
    path("api/v1/admin/exchange-offers", exchange_views.offers_view),
    path("api/v1/admin/exchange-offers/<uuid:offer_id>", exchange_views.offer_detail_view),
    path("api/v1/admin/exchange-offers/<uuid:offer_id>/availability", exchange_views.offer_availability_view),
    path("api/v1/admin/exchange-sku-options", exchange_views.sku_options_view),
    path("api/v1/admin/exchange-operations/<uuid:key>", exchange_views.admin_operations_view),
    path("api/v1/app/exchange-products", exchange_views.products_view),
    path("api/v1/app/exchange-products/<uuid:offer_id>", exchange_views.product_detail_view),
    path("api/v1/app/exchange-quotes", exchange_views.quotes_view),
    path("api/v1/app/exchange-orders", exchange_views.orders_view),
    path("api/v1/app/exchange-operations/<uuid:key>", exchange_views.member_operations_view),
    path("api/v1/admin/coupon-product-options", coupon_views.campaign_product_options_view),
    path("api/v1/admin/coupon-campaigns", coupon_views.campaigns_view),
    path("api/v1/admin/coupon-campaigns/<uuid:campaign_id>", coupon_views.campaign_detail_view),
    path("api/v1/admin/coupon-campaigns/<uuid:campaign_id>/publish", coupon_views.campaign_publish_view),
    path("api/v1/admin/coupon-campaigns/<uuid:campaign_id>/distribution", coupon_views.campaign_distribution_view),
    path("api/v1/admin/coupon-campaigns/<uuid:campaign_id>/issuances", coupon_views.campaign_issuances_view),
    path("api/v1/admin/coupon-operations/<uuid:request_key>", coupon_views.admin_coupon_operation_view),
    path("api/v1/app/coupon-campaigns", coupon_views.app_campaigns_view),
    path("api/v1/app/coupon-campaigns/<uuid:campaign_id>/claim", coupon_views.app_claim_view),
    path("api/v1/app/member/coupons", coupon_views.app_coupons_view),
    path("api/v1/app/member/coupon-claims/<uuid:request_key>", coupon_views.app_coupon_claim_view),
    path("api/v1/admin/members", member_views.member_list_view),
    path("api/v1/admin/members/<uuid:member_id>", member_views.member_detail_view),
    path("api/v1/admin/members/<uuid:member_id>/points", member_views.member_points_view),
    path("api/v1/admin/members/<uuid:member_id>/consumption", member_views.member_consumption_view),
    path("api/v1/admin/member-rules", member_views.member_rules_view),
    path("api/v1/app/member/overview", member_views.app_overview_view),
    path("api/v1/app/member/points", member_views.app_points_view),
    path("api/v1/app/member/consumption", member_views.app_consumption_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/settle-benefits", refund_views.settle_benefits_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/wechat-refund", wechat_refund_views.dispatch_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/wechat-refund/query", wechat_refund_views.query_view),
    path("api/v1/payments/wechat/refund-notify", wechat_refund_views.notification_view),
    path("api/v1/app/aftersales/<uuid:case_id>/return-shipment", return_views.return_shipment_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/return-acceptance/preview", return_views.return_acceptance_preview_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/return-acceptance", return_views.return_acceptance_view),
    path("api/v1/app/orders/<uuid:order_id>/aftersale-options", aftersale_views.options_view),
    path("api/v1/app/aftersales/preview", aftersale_views.preview_view),
    path("api/v1/app/aftersales", aftersale_views.member_cases_view),
    path("api/v1/app/aftersales/<uuid:case_id>", aftersale_views.member_detail_view),
    path("api/v1/app/aftersales/<uuid:case_id>/withdraw", aftersale_views.withdraw_view),
    path("api/v1/admin/aftersales", aftersale_views.admin_cases_view),
    path("api/v1/admin/aftersales/<uuid:case_id>", aftersale_views.admin_detail_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/review", aftersale_views.review_view),
    path("api/v1/admin/aftersales/<uuid:case_id>/offline-refunds", refund_views.prepare_view),
    path("api/v1/admin/refunds/offline-reconciliations/<uuid:reconciliation_id>/confirm", refund_views.confirm_view),
    path("api/v1/admin/fulfillment/carriers", fulfillment_views.carriers_view),
    path("api/v1/admin/fulfillment/policy", fulfillment_views.policy_view),
    path("api/v1/admin/orders/<uuid:order_id>/shipment", fulfillment_views.shipment_view),
    path("api/v1/admin/orders/<uuid:order_id>/shipment/correct", fulfillment_views.shipment_correct_view),
    path("api/v1/admin/shipments/batch", fulfillment_views.batch_ship_view),
    path("api/v1/admin/redemptions/lookup", fulfillment_views.lookup_view),
    path("api/v1/admin/redemptions/<uuid:voucher_id>/use", fulfillment_views.use_view),
    path("api/v1/admin/redemptions/events/<uuid:event_id>/reverse", fulfillment_views.reverse_view),
    path("api/v1/app/orders/<uuid:order_id>/confirm-receipt", fulfillment_views.confirm_receipt_view),
    path("api/v1/app/orders/<uuid:order_id>/tracking", fulfillment_views.tracking_view),
    path("api/v1/payments/wechat/notify", wechat_views.wechat_notification_view),
    path("api/v1/app/orders/<uuid:order_id>/wechat/prepay", wechat_views.wechat_prepay_view),
    path("api/v1/app/orders/<uuid:order_id>/wechat/query", wechat_views.wechat_query_view),
    path("api/v1/app/payments/offline-policy", payment_views.public_offline_policy_view),
    path("api/v1/app/orders/<uuid:order_id>/payment-report", payment_views.payment_report_view),
    path("api/v1/admin/payments/offline-policy", payment_views.offline_policy_view),
    path("api/v1/admin/orders", admin_order_views.orders_view),
    path("api/v1/admin/orders/<uuid:order_id>", admin_order_views.order_detail_view),
    path("api/v1/admin/orders/<uuid:order_id>/offline-reconciliations", payment_views.prepare_reconciliation_view),
    path("api/v1/admin/payments/offline-reconciliations/<uuid:reconciliation_id>/confirm", payment_views.confirm_reconciliation_view),
    path("api/v1/app/auth/wechat", customer_views.wechat_login_view),
    path("api/v1/app/auth/logout", customer_views.logout_view),
    path("api/v1/app/me", customer_views.me_view),
    path("api/v1/app/addresses", customer_views.addresses_view),
    path("api/v1/app/addresses/<uuid:address_id>", customer_views.address_detail_view),
    path("api/v1/app/checkout/quotes", checkout_views.quotes_view),
    path("api/v1/app/orders", order_views.orders_view),
    path("api/v1/app/orders/<uuid:order_id>", order_views.order_detail_view),
    path("api/v1/app/orders/<uuid:order_id>/cancel", order_views.order_cancel_view),
    path("api/v1/admin/auth/csrf", views.csrf_token),
    path("api/v1/admin/auth/login", views.login_view),
    path("api/v1/admin/auth/confirm", views.confirm_view),
    path("api/v1/admin/auth/logout", views.logout_view),
    path("api/v1/admin/me", views.me_view),
    path("api/v1/admin/accounts", views.accounts_view),
    path("api/v1/admin/accounts/<uuid:account_id>", views.account_detail_view),
    path("api/v1/admin/permission-groups", views.groups_view),
    path("api/v1/admin/permission-groups/<uuid:group_id>", views.group_detail_view),
    path("api/v1/admin/audit-logs", audit_read.audit_view),
    path("api/v1/admin/business-summary", business_read.summary_view),
    path("api/v1/admin/warehouses", inventory_views.warehouses_view),
    path("api/v1/admin/settlement/shipping-policy", shipping_views.shipping_policy_view),
    path("api/v1/admin/inventory/skus", inventory_views.skus_view),
    path("api/v1/admin/inventory/balances", inventory_views.balances_view),
    path("api/v1/admin/inventory/inbounds", inventory_views.inbounds_view),
    path("api/v1/admin/inventory/inbounds/<uuid:inbound_id>", inventory_views.inbound_detail_view),
    path("api/v1/admin/inventory/inbounds/<uuid:inbound_id>/confirm", inventory_views.inbound_confirm_view),
    path("api/v1/admin/inventory/outbounds", inventory_views.outbounds_view),
    path("api/v1/admin/inventory/outbounds/<uuid:outbound_id>", inventory_views.outbound_detail_view),
    path("api/v1/admin/inventory/outbounds/<uuid:outbound_id>/confirm", inventory_views.outbound_confirm_view),
    path("api/v1/admin/inventory/stocktakes", inventory_views.stocktakes_view),
    path("api/v1/admin/inventory/stocktakes/<uuid:stocktake_id>", inventory_views.stocktake_detail_view),
    path("api/v1/admin/inventory/stocktakes/<uuid:stocktake_id>/submit", inventory_views.stocktake_submit_view),
    path("api/v1/admin/inventory/stocktakes/<uuid:stocktake_id>/return", inventory_views.stocktake_return_view),
    path("api/v1/admin/inventory/stocktakes/<uuid:stocktake_id>/approve", inventory_views.stocktake_approve_view),
    path("api/v1/admin/inventory/ledgers", inventory_views.ledgers_view),
    path("api/v1/admin/inventory/ledgers/<uuid:ledger_id>", inventory_views.ledger_detail_view),
    path("api/v1/admin/categories", catalog_views.categories_view),
    path("api/v1/admin/categories/<uuid:category_id>", catalog_views.category_detail_view),
    path("api/v1/admin/member-grades", catalog_views.grades_view),
    path("api/v1/admin/assets", media_views.assets_view),
    path("api/v1/admin/assets/<uuid:asset_id>", media_views.asset_delete_view),
    path("api/v1/admin/assets/<uuid:asset_id>/references", media_views.asset_references_view),
    path("api/v1/admin/assets/<uuid:asset_id>/file", media_views.admin_asset_file_view),
    path("api/v1/admin/sku-rows", catalog_views.sku_rows_view),
    path("api/v1/admin/sku-rows/batch-status", catalog_views.batch_status_view),
    path("api/v1/admin/products/batch-category/preview", catalog_views.batch_category_preview_view),
    path("api/v1/admin/products/batch-category", catalog_views.batch_category_view),
    path("api/v1/admin/products", catalog_views.products_view),
    path("api/v1/admin/products/<uuid:product_id>", catalog_views.product_detail_view),
    path("api/v1/admin/products/<uuid:product_id>/specs/preview", catalog_views.product_specs_preview_view),
    path("api/v1/admin/products/<uuid:product_id>/specs", catalog_views.product_specs_view),
    path("api/v1/admin/skus/<uuid:sku_id>/status", catalog_views.sku_status_view),
    path("api/v1/admin/skus/<uuid:sku_id>/price", catalog_views.sku_price_view),
    path("api/v1/admin/skus/<uuid:sku_id>/grade-prices", catalog_views.sku_prices_view),
    path("api/v1/admin/skus/<uuid:sku_id>/unit", catalog_views.sku_unit_view),
    path("api/v1/admin/pages/home/versions", history.page_versions_view),
    path("api/v1/admin/pages/home/versions/<uuid:version_id>", history.page_versions_view),
    path("api/v1/admin/pages/home/rollback", history.page_rollback_view),
    path("api/v1/admin/pages/<uuid:page_id>/versions", history.page_versions_view),
    path("api/v1/admin/pages/<uuid:page_id>/versions/<uuid:version_id>", history.page_versions_view),
    path("api/v1/admin/pages/<uuid:page_id>/rollback", history.page_rollback_view),
    path("api/v1/admin/startup/versions", history.startup_versions_view),
    path("api/v1/admin/startup/versions/<uuid:version_id>", history.startup_versions_view),
    path("api/v1/admin/startup/rollback", history.startup_rollback_view),
    path("api/v1/admin/pages/home/draft", page_views.home_draft_view),
    path("api/v1/admin/pages/home/preview", page_views.home_preview_view),
    path("api/v1/admin/pages/home/publish", page_views.home_publish_view),
    path("api/v1/admin/pages", page_views.pages_view),
    path("api/v1/admin/pages/<uuid:page_id>/draft", page_views.micro_draft_view),
    path("api/v1/admin/pages/<uuid:page_id>/preview", page_views.micro_preview_view),
    path("api/v1/admin/pages/<uuid:page_id>/publish", page_views.micro_publish_view),
    path("api/v1/admin/startup/draft", startup_views.draft_view),
    path("api/v1/admin/startup/preview", startup_views.preview_view),
    path("api/v1/admin/startup/publish", startup_views.publish_view),
    path("api/v1/app/home", page_views.public_home_view),
    path("api/v1/app/pages/<uuid:page_id>", page_views.public_micro_view),
    path("api/v1/app/startup", startup_views.public_view),
    path("api/v1/app/categories", catalog_views.public_categories_view),
    path("api/v1/app/products", catalog_views.public_products_view),
    path("api/v1/app/products/<uuid:product_id>", catalog_views.public_product_detail_view),
    path("api/v1/app/assets/<uuid:asset_id>/file", media_views.public_asset_file_view),
]
