# Generated by Django 5.2.17 on 2026-09-25 22:38

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_sku_driven_product_sale'),
        ('customers', '0001_initial'),
        ('inventory', '0006_inventoryreservationevent_inventoryreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=40, unique=True)),
                ('quote_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='PENDING_PAYMENT', max_length=16)),
                ('payment_method', models.CharField(choices=[('WECHAT', 'WeChat'), ('OFFLINE', 'Offline')], max_length=8)),
                ('address_snapshot', models.JSONField(default=dict)),
                ('goods_total_fen', models.BigIntegerField()),
                ('shipping_fee_fen', models.BigIntegerField()),
                ('payable_fen', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'customer_order',
            },
        ),
        migrations.CreateModel(
            name='OrderIdempotency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(default='CREATE_ORDER', max_length=32)),
                ('key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'db_table': 'order_idempotency',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=120)),
                ('sku_code', models.CharField(max_length=64)),
                ('specs_snapshot', models.JSONField(default=list)),
                ('fulfillment_kind', models.CharField(max_length=6)),
                ('base_unit', models.CharField(max_length=30)),
                ('sale_unit', models.CharField(max_length=30)),
                ('ratio', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('base_quantity', models.PositiveBigIntegerField()),
                ('unit_price_fen', models.BigIntegerField()),
                ('goods_amount_fen', models.BigIntegerField()),
                ('payable_fen', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
                ('unit_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.skuunitversion')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'customer_order_line',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['member', '-created_at'], name='order_member_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='order_status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('goods_total_fen__gte', 0)), name='order_goods_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_fee_fen__gte', 0)), name='order_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fen__gte', 0)), name='order_payable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fen', django.db.models.expressions.CombinedExpression(models.F('goods_total_fen'), '+', models.F('shipping_fee_fen')))), name='order_total_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='orderidempotency',
            constraint=models.UniqueConstraint(fields=('member', 'scope', 'key'), name='order_actor_scope_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='order_line_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='order_line_base_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_fen__gte', 0)), name='order_line_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('goods_amount_fen__gte', 0)), name='order_line_goods_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fen__gte', 0)), name='order_line_payable_nonnegative'),
        ),
    ]
