# Generated by Django 5.2.17 on 2026-09-26 00:15

import django.db.models.expressions
from django.db import migrations, models


UPDATED_IMMUTABILITY = """
CREATE OR REPLACE FUNCTION order_reject_financial_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    IF ROW(NEW.order_no, NEW.member_id, NEW.quote_id, NEW.payment_method,
           NEW.address_snapshot, NEW.goods_total_fen, NEW.shipping_fee_fen,
           NEW.shipping_policy_revision, NEW.coupon_id, NEW.coupon_discount_fen,
           NEW.points_to_use, NEW.points_discount_fen, NEW.payable_fen,
           NEW.expires_at, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.order_no, OLD.member_id, OLD.quote_id, OLD.payment_method,
           OLD.address_snapshot, OLD.goods_total_fen, OLD.shipping_fee_fen,
           OLD.shipping_policy_revision, OLD.coupon_id, OLD.coupon_discount_fen,
           OLD.points_to_use, OLD.points_discount_fen, OLD.payable_fen,
           OLD.expires_at, OLD.created_at) THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    RETURN NEW;
END;
$$;
"""

PREVIOUS_IMMUTABILITY = """
CREATE OR REPLACE FUNCTION order_reject_financial_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    IF ROW(NEW.order_no, NEW.member_id, NEW.quote_id, NEW.payment_method,
           NEW.address_snapshot, NEW.goods_total_fen, NEW.shipping_fee_fen,
           NEW.payable_fen, NEW.expires_at, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.order_no, OLD.member_id, OLD.quote_id, OLD.payment_method,
           OLD.address_snapshot, OLD.goods_total_fen, OLD.shipping_fee_fen,
           OLD.payable_fen, OLD.expires_at, OLD.created_at) THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sku_driven_product_sale'),
        ('customers', '0001_initial'),
        ('inventory', '0007_inventoryreservation_order_line_and_more'),
        ('checkout', '0003_settlement_quote'),
        ('shipping', '0001_initial'),
        ('benefits', '0001_initial'),
        ('orders', '0002_immutable_order_snapshots'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_total_matches_parts',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_fen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='points_discount_fen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_to_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_policy_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='coupon_discount_fen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderline',
            name='points_discount_fen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount_fen__gte', 0)), name='order_coupon_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('points_discount_fen__gte', 0)), name='order_points_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount_fen__lte', models.F('goods_total_fen'))), name='order_coupon_within_goods'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('points_discount_fen__lte', django.db.models.expressions.CombinedExpression(models.F('goods_total_fen'), '-', models.F('coupon_discount_fen')))), name='order_points_within_goods'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('points_discount_fen', models.F('points_to_use'))), name='order_points_ratio_v1'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fen', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('goods_total_fen'), '+', models.F('shipping_fee_fen')), '-', models.F('coupon_discount_fen')), '-', models.F('points_discount_fen')))), name='order_total_matches_parts'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount_fen__gte', 0)), name='order_line_coupon_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('points_discount_fen__gte', 0)), name='order_line_points_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount_fen__lte', models.F('goods_amount_fen'))), name='order_line_coupon_within_goods'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('points_discount_fen__lte', django.db.models.expressions.CombinedExpression(models.F('goods_amount_fen'), '-', models.F('coupon_discount_fen')))), name='order_line_points_within_goods'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('payable_fen', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('goods_amount_fen'), '-', models.F('coupon_discount_fen')), '-', models.F('points_discount_fen')))), name='order_line_total_matches_parts'),
        ),
        migrations.RunSQL(UPDATED_IMMUTABILITY, PREVIOUS_IMMUTABILITY),
    ]
