# Generated by Django 5.2.17 on 2026-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_settlement_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('paid_at__isnull', True), ('status', 'PENDING_PAYMENT')), models.Q(('closed_at__isnull', True), ('paid_at__isnull', False), ('status', 'PAID')), models.Q(('closed_at__isnull', False), ('paid_at__isnull', True), ('status', 'CLOSED')), _connector='OR'), name='order_payment_state_time_consistent'),
        ),
    ]
