# Generated by Django 5.2.17 on 2026-09-26 03:04

from django.db import migrations, models


PREVIOUS_IMMUTABILITY = """
CREATE OR REPLACE FUNCTION order_reject_financial_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    IF ROW(NEW.order_no, NEW.member_id, NEW.quote_id, NEW.payment_method,
           NEW.address_snapshot, NEW.goods_total_fen, NEW.shipping_fee_fen,
           NEW.shipping_policy_revision, NEW.coupon_id, NEW.coupon_discount_fen,
           NEW.points_to_use, NEW.points_discount_fen, NEW.payable_fen,
           NEW.expires_at, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.order_no, OLD.member_id, OLD.quote_id, OLD.payment_method,
           OLD.address_snapshot, OLD.goods_total_fen, OLD.shipping_fee_fen,
           OLD.shipping_policy_revision, OLD.coupon_id, OLD.coupon_discount_fen,
           OLD.points_to_use, OLD.points_discount_fen, OLD.payable_fen,
           OLD.expires_at, OLD.created_at) THEN
        RAISE EXCEPTION 'order snapshot is immutable';
    END IF;
    RETURN NEW;
END;
$$;
"""

UPDATED_IMMUTABILITY = PREVIOUS_IMMUTABILITY.replace("NEW.expires_at, NEW.created_at", "NEW.payment_instructions, NEW.expires_at, NEW.created_at").replace("OLD.expires_at, OLD.created_at", "OLD.payment_instructions, OLD.expires_at, OLD.created_at")

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_payment_state_time_consistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_instructions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunSQL(UPDATED_IMMUTABILITY, PREVIOUS_IMMUTABILITY),
    ]
