# Generated by Django 5.2.17 on 2026-09-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0005_order_payment_instructions_order_revision'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', '-id'], name='order_admin_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status', '-created_at'], name='order_method_status_idx'),
        ),
    ]
