# Generated by Django 5.2.17 on 2026-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_admin_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='redeem_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
