# Generated by Django 5.2.17 on 2026-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderline_redeem_valid_until'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_points_ratio_v1',
        ),
        migrations.AddField(
            model_name='order',
            name='benefit_policy_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
