# Generated by Django 5.2.17 on 2026-09-27 07:00

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('customers', '0006_operation_indexes'),
        ('inventory', '0010_returndisposition_and_more'),
        ('orders', '0009_benefit_policy_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_kind',
            field=models.CharField(default='CASH', max_length=6),
        ),
        migrations.AddField(
            model_name='orderline',
            name='points_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderline',
            name='points_unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WECHAT', 'WeChat'), ('OFFLINE', 'Offline'), ('POINTS', 'Points')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_kind', 'CASH'), ('payment_method__in', ['OFFLINE', 'WECHAT'])), models.Q(('coupon_discount_fen', 0), ('coupon_id__isnull', True), ('goods_total_fen', 0), ('order_kind', 'POINTS'), ('payable_fen', 0), ('payment_method', 'POINTS'), ('points_discount_fen', 0), ('points_to_use__gte', 1), ('points_to_use__lte', 99000000), ('shipping_fee_fen', 0)), _connector='OR'), name='order_kind_payment_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('points_total', 0), ('points_unit_price', 0)), models.Q(('coupon_discount_fen', 0), ('goods_amount_fen', 0), ('payable_fen', 0), ('points_discount_fen', 0), ('points_total', django.db.models.expressions.CombinedExpression(models.F('points_unit_price'), '*', models.F('quantity'))), ('points_unit_price__gte', 1), ('points_unit_price__lte', 1000000), ('quantity__lte', 99), ('unit_price_fen', 0)), _connector='OR'), name='order_line_points_valid'),
        ),
    ]
