# Generated by Django 5.2.17 on 2026-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_operation_indexes'),
        ('orders', '0013_exchange_immutable_event_proofs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'PAID')), fields=['paid_at'], name='order_paid_fact_idx'),
        ),
    ]
