# Generated by Django 5.2.17 on 2026-09-26 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_order_sale_ledger'),
        ('orders', '0007_orderline_redeem_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('code', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fulfillment_carrier',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_confirm_days', models.PositiveSmallIntegerField(default=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fulfillment_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='fulfillment_policy_singleton'), models.CheckConstraint(condition=models.Q(('auto_confirm_days__gte', 1), ('auto_confirm_days__lte', 30)), name='fulfillment_auto_days_bounded')],
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillmentSnapshot',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='fulfillment_snapshot', serialize=False, to='orders.order')),
                ('auto_confirm_days', models.PositiveSmallIntegerField()),
                ('policy_revision', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'fulfillment_order_snapshot',
                'constraints': [models.CheckConstraint(condition=models.Q(('auto_confirm_days__gte', 1), ('auto_confirm_days__lte', 30)), name='fulfillment_snapshot_days_bounded')],
            },
        ),
        migrations.CreateModel(
            name='RedeemVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=32, unique=True)),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('redeemed_quantity', models.PositiveIntegerField(default=0)),
                ('voided_quantity', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redeem_voucher', to='orders.orderline')),
            ],
            options={
                'db_table': 'fulfillment_redeem_voucher',
            },
        ),
        migrations.CreateModel(
            name='RedeemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('USE', 'Use'), ('REVERSE', 'Reverse')], max_length=7)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('request_key', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original_use', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='fulfillment.redeemevent')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fulfillment.redeemvoucher')),
            ],
            options={
                'db_table': 'fulfillment_redeem_event',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier_code', models.CharField(max_length=24)),
                ('carrier_name', models.CharField(max_length=80)),
                ('tracking_no', models.CharField(max_length=80)),
                ('shipped_at', models.DateTimeField()),
                ('auto_confirm_days_snapshot', models.PositiveSmallIntegerField()),
                ('auto_confirm_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_member', models.BooleanField(default=False)),
                ('request_key', models.UUIDField(unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.carrier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'fulfillment_shipment',
            },
        ),
        migrations.CreateModel(
            name='ShipmentCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_carrier_code', models.CharField(max_length=24)),
                ('old_carrier_name', models.CharField(max_length=80)),
                ('old_tracking_no', models.CharField(max_length=80)),
                ('new_carrier_code', models.CharField(max_length=24)),
                ('new_carrier_name', models.CharField(max_length=80)),
                ('new_tracking_no', models.CharField(max_length=80)),
                ('reason', models.CharField(max_length=500)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='fulfillment.shipment')),
            ],
            options={
                'db_table': 'fulfillment_shipment_correction',
            },
        ),
        migrations.CreateModel(
            name='RedeemLookupFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_digest', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fulfillment_redeem_lookup_failure',
                'indexes': [models.Index(fields=['actor', '-occurred_at'], name='redeem_lookup_actor_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='redeemvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('redeemed_quantity__gte', 0)), name='voucher_redeemed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='redeemvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('voided_quantity__gte', 0)), name='voucher_voided_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='redeemevent',
            index=models.Index(fields=['voucher', '-occurred_at'], name='redeem_event_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='redeemevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='redeem_event_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='redeemevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key__isnull', False)), fields=('voucher', 'request_key'), name='redeem_voucher_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='redeemevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'USE'), ('original_use__isnull', True), ('reason', ''), ('request_key__isnull', False)), models.Q(('kind', 'REVERSE'), ('original_use__isnull', False), ('request_key__isnull', True)), _connector='OR'), name='redeem_event_kind_shape'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('auto_confirm_days_snapshot__gte', 1), ('auto_confirm_days_snapshot__lte', 30)), name='shipment_auto_days_bounded'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_at__isnull', True), ('confirmed_at__gte', models.F('shipped_at')), _connector='OR'), name='shipment_confirm_after_ship'),
        ),
        migrations.AddIndex(
            model_name='shipmentcorrection',
            index=models.Index(fields=['shipment', '-corrected_at'], name='shipment_correction_recent_idx'),
        ),
    ]
