# Generated by Django 5.2.17 on 2026-10-10 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_member_profile_quota'),
        ('fulfillment', '0005_voucher_refund_event'),
        ('orders', '0014_order_order_paid_fact_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDelivery',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='store_delivery', serialize=False, to='orders.order')),
                ('mode', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=8)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('IN_TRANSIT', 'In transit'), ('COMPLETED', 'Completed')], max_length=12)),
                ('nonce', models.CharField(max_length=32)),
                ('prepared_at', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfillment_store_delivery',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dispatched_at__isnull', True), ('mode', 'PICKUP'), ('status__in', ['READY', 'COMPLETED'])), ('mode', 'DELIVERY'), _connector='OR'), name='store_delivery_mode_shape'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', True), ('status__in', ['READY', 'IN_TRANSIT'])), _connector='OR'), name='store_delivery_completion_shape')],
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=12)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_digest', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_delivery_events', to='orders.order')),
            ],
            options={
                'db_table': 'fulfillment_store_delivery_event',
            },
        ),
    ]
