# Generated by Django 5.2.17 on 2026-09-25 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.UUIDField(blank=True, null=True)),
                ('address_id', models.UUIDField(blank=True, null=True)),
                ('lines', models.JSONField(default=list)),
                ('goods_total_fen', models.BigIntegerField()),
                ('payable_fen', models.BigIntegerField()),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'checkout_quote',
                'constraints': [models.CheckConstraint(condition=models.Q(('goods_total_fen__gte', 0)), name='quote_goods_nonnegative'), models.CheckConstraint(condition=models.Q(('payable_fen__gte', 0)), name='quote_payable_nonnegative')],
            },
        ),
    ]
