# Generated by Django 5.2.17 on 2026-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutquote',
            name='source_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='checkoutquote',
            index=models.Index(fields=['source_digest', '-created_at'], name='quote_source_created_idx'),
        ),
    ]
