# Generated by Django 5.2.17 on 2026-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_settlement_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutquote',
            name='benefit_policy_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
