# Generated by Django 5.2.17 on 2026-09-26 00:12

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('FULL_REDUCTION', 'Full reduction'), ('CASH', 'Cash')], max_length=20)),
                ('min_goods_fen', models.BigIntegerField(default=0)),
                ('discount_fen', models.BigIntegerField()),
                ('product_ids', models.JSONField(default=list)),
                ('redeem_eligible', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'benefit_coupon_campaign',
                'constraints': [models.CheckConstraint(condition=models.Q(('min_goods_fen__gte', 0)), name='coupon_min_nonnegative'), models.CheckConstraint(condition=models.Q(('discount_fen__gt', 0)), name='coupon_discount_positive'), models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='coupon_valid_window'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'FULL_REDUCTION'), ('min_goods_fen__gt', 0)), models.Q(('kind', 'CASH'), ('min_goods_fen', 0)), _connector='OR'), name='coupon_kind_threshold_valid')],
            },
        ),
        migrations.CreateModel(
            name='PointsGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ref', models.CharField(max_length=120, unique=True)),
                ('original_points', models.BigIntegerField()),
                ('available_points', models.BigIntegerField()),
                ('reserved_points', models.BigIntegerField(default=0)),
                ('consumed_points', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_points_grant',
            },
        ),
        migrations.CreateModel(
            name='PointsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('GRANT', 'Grant'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('CONSUME', 'Consume')], max_length=7)),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.pointsgrant')),
            ],
            options={
                'db_table': 'benefit_points_event',
            },
        ),
        migrations.CreateModel(
            name='PointsReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('CONSUMED', 'Consumed')], default='RESERVED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.pointsgrant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_points_reservation',
            },
        ),
        migrations.CreateModel(
            name='MemberCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used')], default='AVAILABLE', max_length=9)),
                ('reserved_order_id', models.UUIDField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.couponcampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_member_coupon',
                'indexes': [models.Index(fields=['member', 'status', 'issued_at'], name='coupon_member_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reserved_order_id__isnull', False)), fields=('reserved_order_id',), name='coupon_one_per_order'), models.CheckConstraint(condition=models.Q(models.Q(('reserved_order_id__isnull', True), ('status', 'AVAILABLE')), models.Q(('reserved_order_id__isnull', False), ('status__in', ['RESERVED', 'USED'])), _connector='OR'), name='coupon_order_status_consistent')],
            },
        ),
        migrations.AddIndex(
            model_name='pointsgrant',
            index=models.Index(fields=['member', 'expires_at', 'id'], name='points_member_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsgrant',
            constraint=models.CheckConstraint(condition=models.Q(('original_points__gt', 0)), name='points_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointsgrant',
            constraint=models.CheckConstraint(condition=models.Q(('available_points__gte', 0)), name='points_available_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pointsgrant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_points__gte', 0)), name='points_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pointsgrant',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_points__gte', 0)), name='points_consumed_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pointsgrant',
            constraint=models.CheckConstraint(condition=models.Q(('original_points', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_points'), '+', models.F('reserved_points')), '+', models.F('consumed_points')))), name='points_grant_conserved'),
        ),
        migrations.AddIndex(
            model_name='pointsevent',
            index=models.Index(fields=['member', '-created_at'], name='points_member_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='points_event_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointsevent',
            constraint=models.UniqueConstraint(condition=models.Q(('order_id__isnull', False)), fields=('grant', 'order_id', 'kind'), name='points_once_per_transition'),
        ),
        migrations.AddIndex(
            model_name='pointsreservation',
            index=models.Index(fields=['order_id', 'status'], name='points_order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointsreservation',
            constraint=models.UniqueConstraint(fields=('order_id', 'grant'), name='points_order_grant_unique'),
        ),
        migrations.AddConstraint(
            model_name='pointsreservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='points_reservation_positive'),
        ),
    ]
