# Generated by Django 5.2.17 on 2026-09-26 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_immutable_points_event'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('CONSUME', 'Consume')], max_length=7)),
                ('discount_fen', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.membercoupon')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_coupon_event',
                'indexes': [models.Index(fields=['member', '-created_at'], name='coupon_member_event_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_fen__gt', 0)), name='coupon_event_discount_positive'), models.UniqueConstraint(fields=('coupon', 'order_id', 'kind'), name='coupon_once_per_transition')],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION benefit_coupon_event_reject_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'coupon event is immutable';
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER benefit_coupon_event_immutable
              BEFORE UPDATE OR DELETE ON benefit_coupon_event
              FOR EACH ROW EXECUTE FUNCTION benefit_coupon_event_reject_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER benefit_coupon_event_immutable ON benefit_coupon_event;
            DROP FUNCTION benefit_coupon_event_reject_mutation();
            """,
        ),
    ]
