# Generated by Django 5.2.17 on 2026-09-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_couponevent'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAccount',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='points_account', serialize=False, to='customers.member')),
                ('settled_points', models.BigIntegerField(default=0)),
                ('frozen_points', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'benefit_points_account',
                'constraints': [models.CheckConstraint(condition=models.Q(('frozen_points__gte', 0)), name='points_account_frozen_nonnegative')],
            },
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO benefit_points_account
                (member_id, settled_points, frozen_points, updated_at)
            SELECT member.id,
                   COALESCE(SUM(lot.available_points + lot.reserved_points), 0),
                   COALESCE(SUM(lot.reserved_points), 0),
                   CURRENT_TIMESTAMP
            FROM customer_member AS member
            LEFT JOIN benefit_points_grant AS lot ON lot.member_id = member.id
            GROUP BY member.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
