# Generated by Django 5.2.17 on 2026-09-27 04:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_pointsaccount'),
        ('customers', '0002_gradethreshold_memberconsumption_consumptionorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBenefitSettlement',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('earned_points', models.PositiveBigIntegerField(default=0)),
                ('returned_points', models.PositiveBigIntegerField(default=0)),
                ('refunded_lines', models.JSONField(default=list)),
                ('coupon_restored', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'benefit_order_settlement',
            },
        ),
        migrations.CreateModel(
            name='PointsPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('earn_unit_fen', models.PositiveIntegerField(default=100)),
                ('earn_points', models.PositiveIntegerField(default=1)),
                ('valid_days', models.PositiveIntegerField(default=365)),
                ('refund_valid_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'db_table': 'benefit_points_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='points_policy_singleton'), models.CheckConstraint(condition=models.Q(('earn_points__gt', 0), ('earn_unit_fen__gt', 0), ('refund_valid_days__gt', 0), ('valid_days__gt', 0)), name='points_policy_values_positive')],
            },
        ),
        migrations.CreateModel(
            name='BenefitLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(null=True)),
                ('kind', models.CharField(max_length=16)),
                ('amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('source_ref', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='benefits.pointsgrant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_lifecycle_ledger',
                'indexes': [models.Index(fields=['member', '-created_at'], name='benefit_lifecycle_member_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderBenefitSnapshot',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('policy_revision', models.PositiveIntegerField()),
                ('earn_unit_fen', models.PositiveIntegerField()),
                ('earn_points', models.PositiveIntegerField()),
                ('valid_days', models.PositiveIntegerField()),
                ('refund_valid_days', models.PositiveIntegerField()),
                ('grade_thresholds', models.JSONField(default=list)),
                ('line_snapshot', models.JSONField(default=list)),
                ('coupon_id', models.UUIDField(null=True)),
                ('coupon_valid_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'benefit_order_snapshot',
                'constraints': [models.CheckConstraint(condition=models.Q(('earn_points__gt', 0), ('earn_unit_fen__gt', 0), ('refund_valid_days__gt', 0), ('valid_days__gt', 0)), name='points_snapshot_values_positive')],
            },
        ),
    ]
