# Generated by Django 5.2.17 on 2026-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_orderbenefitsettlement_pointspolicy_benefitledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbenefitsettlement',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
