# Generated by Django 5.2.17 on 2026-09-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_orderbenefitsettlement_credited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponevent',
            name='kind',
            field=models.CharField(choices=[('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('CONSUME', 'Consume'), ('RESTORE', 'Restore')], max_length=7),
        ),
    ]
