# Generated by Django 5.2.17 on 2026-09-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0007_alter_couponevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercoupon',
            name='restored_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
