# Generated by Django 5.2.17 on 2026-09-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0009_lifecycle_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitledger',
            name='cause_ref',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
