# Generated by Django 5.2.17 on 2026-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0010_benefitledger_cause_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointspolicy',
            name='deduct_fen',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pointspolicy',
            name='deduct_points',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pointspolicy',
            name='max_percent',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddConstraint(
            model_name='pointspolicy',
            constraint=models.CheckConstraint(condition=models.Q(('deduct_fen__gt', 0), ('deduct_points__gt', 0), ('max_percent__gte', 1), ('max_percent__lte', 100)), name='points_deduct_policy_positive'),
        ),
    ]
