# Generated by Django 5.2.17 on 2026-09-27 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0011_pointspolicy_deduct_fen_pointspolicy_deduct_points_and_more'),
        ('customers', '0006_operation_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_count', models.PositiveIntegerField(default=0)),
                ('admin_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'benefit_coupon_allocation',
            },
        ),
        migrations.CreateModel(
            name='CouponIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=5)),
                ('request_key', models.UUIDField()),
                ('body_hash', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'benefit_coupon_issuance',
            },
        ),
        migrations.CreateModel(
            name='CouponOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('action', models.CharField(max_length=40)),
                ('body_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'benefit_coupon_operation',
            },
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='claim_mode',
            field=models.CharField(choices=[('SELF', 'Self'), ('ADMIN', 'Admin'), ('BOTH', 'Both')], default='BOTH', max_length=5),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='issuance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='self_claim_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('LEGACY', 'Legacy')], default='LEGACY', max_length=9),
        ),
        migrations.AddField(
            model_name='couponcampaign',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='couponcampaign',
            index=models.Index(fields=['status', 'issuance_enabled', 'valid_until'], name='coupon_distribution_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PUBLISHED', 'LEGACY'])), name='coupon_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('claim_mode__in', ['SELF', 'ADMIN', 'BOTH'])), name='coupon_claim_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__lte', models.F('total_quantity'))), name='coupon_quantity_conserved'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('self_claim_limit__gte', 1)), name='coupon_self_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='couponcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'LEGACY'), ('total_quantity__gte', 1), _connector='OR'), name='coupon_issuable_quantity_positive'),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.couponcampaign'),
        ),
        migrations.AddField(
            model_name='couponallocation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member'),
        ),
        migrations.AddField(
            model_name='couponissuance',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponissuance',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.couponcampaign'),
        ),
        migrations.AddField(
            model_name='couponissuance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member'),
        ),
        migrations.AddField(
            model_name='membercoupon',
            name='issuance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='benefits.couponissuance'),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benefits.couponcampaign'),
        ),
        migrations.AddConstraint(
            model_name='couponallocation',
            constraint=models.UniqueConstraint(fields=('member', 'campaign'), name='coupon_allocation_unique'),
        ),
        migrations.AddIndex(
            model_name='couponissuance',
            index=models.Index(fields=['campaign', '-created_at'], name='coupon_issuance_campaign_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['SELF', 'ADMIN'])), name='coupon_issuance_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='coupon_issuance_quantity_valid'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SELF')), fields=('member', 'request_key'), name='coupon_member_claim_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.UniqueConstraint(condition=models.Q(('actor__isnull', False), ('kind', 'ADMIN')), fields=('actor', 'request_key'), name='coupon_actor_issue_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('kind', 'SELF')), models.Q(('actor__isnull', False), ('kind', 'ADMIN')), _connector='OR'), name='coupon_issuance_actor_valid'),
        ),
        migrations.AddConstraint(
            model_name='couponoperation',
            constraint=models.UniqueConstraint(fields=('actor', 'request_key'), name='coupon_operation_actor_key_unique'),
        ),
    ]
