# Generated by Django 5.2.17 on 2026-09-27 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0013_coupon_operation_guards'),
        ('customers', '0006_operation_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='couponissuance',
            name='coupon_actor_issue_key_unique',
        ),
        migrations.AddField(
            model_name='couponissuance',
            name='requires_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='couponissuance',
            index=models.Index(fields=['campaign', 'member', 'kind'], name='coupon_issuance_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponissuance',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ADMIN')), fields=('actor', 'request_key'), name='coupon_actor_issue_key_unique'),
        ),
    ]
