# Generated by Django 5.2.17 on 2026-09-28 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=40)),
                ('source_revision', models.CharField(blank=True, max_length=64)),
                ('source_digest', models.CharField(max_length=64, unique=True)),
                ('package_sha256', models.CharField(max_length=64, unique=True)),
                ('package_bytes', models.PositiveIntegerField()),
                ('file_count', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=200, unique=True)),
                ('storage_status', models.CharField(default='READY', max_length=8)),
                ('platform_status', models.CharField(default='NOT_CONFIGURED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mini_code_version',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('storage_status', 'READY')), name='mini_code_storage_ready'), models.CheckConstraint(condition=models.Q(('platform_status', 'NOT_CONFIGURED')), name='mini_code_platform_unconfigured'), models.CheckConstraint(condition=models.Q(('package_bytes__gt', 0)), name='mini_code_package_nonempty'), models.CheckConstraint(condition=models.Q(('file_count__gt', 0)), name='mini_code_files_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='CodeBuildJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='STARTED', max_length=10)),
                ('failure_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_jobs', to='code_versions.codeversion')),
            ],
            options={
                'db_table': 'mini_code_build_job',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['STARTED', 'SUCCEEDED', 'FAILED'])), name='mini_code_job_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('failure_code', ''), ('status', 'STARTED'), ('version__isnull', True)), models.Q(('completed_at__isnull', False), ('failure_code', ''), ('status', 'SUCCEEDED'), ('version__isnull', False)), models.Q(('completed_at__isnull', False), ('status', 'FAILED'), ('version__isnull', True), models.Q(('failure_code', ''), _negated=True)), _connector='OR'), name='mini_code_job_state_shape')],
            },
        ),
    ]
