# Generated by Django 5.2.17 on 2026-09-28 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_versions', '0002_immutable_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebuildjob',
            name='source_revision',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='CodeSourceProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_revision', models.CharField(max_length=64, unique=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provenances', to='code_versions.codeversion')),
            ],
            options={
                'db_table': 'mini_code_source_provenance',
                'ordering': ['-verified_at', '-id'],
                'indexes': [models.Index(fields=['version', '-verified_at', '-id'], name='mini_code_prov_latest_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION mini_code_source_provenance_immutable() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'mini code source provenances are immutable';
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER mini_code_source_provenance_no_update
                BEFORE UPDATE OR DELETE ON mini_code_source_provenance
                FOR EACH ROW EXECUTE FUNCTION mini_code_source_provenance_immutable();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS mini_code_source_provenance_no_update
                ON mini_code_source_provenance;
            DROP FUNCTION IF EXISTS mini_code_source_provenance_immutable();
            """,
        ),
    ]
