# Generated by Django 5.2.17 on 2026-09-29 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_developer_key(apps, schema_editor):
    apps.get_model('code_versions', 'DeveloperUploadKey').objects.using(
        schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('code_versions', '0004_codeuploadkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperUploadKey',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(blank=True, max_length=18)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mini_developer_upload_key',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='mini_developer_key_singleton')],
            },
        ),
        migrations.CreateModel(
            name='ReleaseUploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=18)),
                ('developer_app_id', models.CharField(max_length=18)),
                ('channel', models.CharField(default='CI_DIRECT', max_length=16)),
                ('package_sha256', models.CharField(max_length=64)),
                ('staged_digest', models.CharField(blank=True, max_length=64)),
                ('key_revision', models.PositiveIntegerField()),
                ('upload_version', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_jobs', to='code_versions.codeversion')),
            ],
            options={
                'db_table': 'mini_code_upload_job',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN', 'RESOLVED'])), name='mini_code_upload_status_valid'), models.CheckConstraint(condition=models.Q(('channel__in', ['CI_DIRECT', 'DIRECT_COMMIT'])), name='mini_code_upload_channel_valid'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'UNKNOWN'])), fields=('app_id',), name='mini_code_one_active_upload')],
            },
        ),
        migrations.RunPython(seed_developer_key, migrations.RunPython.noop),
    ]
