# Generated by Django 5.2.17 on 2026-09-29 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_versions', '0005_developeruploadkey_releaseuploadjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseReviewJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.CharField(max_length=18)),
                ('user_version', models.CharField(max_length=40)),
                ('item_list', models.JSONField()),
                ('version_desc', models.CharField(max_length=200)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('audit_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='SUBMITTING', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('resolution_note', models.CharField(blank=True, max_length=500)),
                ('release_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_jobs', to='code_versions.releaseuploadjob')),
            ],
            options={
                'db_table': 'mini_code_review_job',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['SUBMITTING', 'SUBMITTED', 'REVIEWING', 'APPROVED', 'REJECTED', 'FAILED', 'UNKNOWN', 'RELEASING', 'RELEASE_UNKNOWN', 'RELEASE_REQUESTED', 'CLOSED_UNVERIFIED'])), name='mini_code_review_status_valid'), models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTING', 'SUBMITTED', 'REVIEWING', 'APPROVED', 'UNKNOWN', 'RELEASING', 'RELEASE_UNKNOWN', 'RELEASE_REQUESTED'])), fields=('app_id',), name='mini_code_one_active_review')],
            },
        ),
    ]
