<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue'
import {api,confirmedWrite,type Account} from '../../api'
import {amount} from './types'
interface Rule {skuId:string;productName:string;specKey:string;specLabel?:string;skuCode:string;saleUnit:string;purchaseCostFen:number|null;platformShareBps:number|null;revision:number;requiresReconfiguration?:boolean}
const props=defineProps<{account:Account}>()
const items=ref<Rule[]>([]),total=ref(0),page=ref(1),search=ref('')
const loading=ref(false),busy=ref(false),needsRead=ref(false),confirming=ref(false)
const error=ref(''),notice=ref(''),password=ref(''),cost=ref(''),share=ref(''),selected=ref<Rule|null>(null)
let epoch=0
const permitted=computed(()=>props.account.permissionCodes.includes('stores.manage'))
function hundredths(value:string,max:number){if(!/^\d+(\.\d{1,2})?$/.test(value))return null;const [whole,decimal='']=value.split('.');const result=Number(whole)*100+Number(decimal.padEnd(2,'0'));return Number.isSafeInteger(result)&&result<=max?result:null}
const costFen=computed(()=>hundredths(cost.value,9900000000)),shareBps=computed(()=>hundredths(share.value,10000))
const allowed=computed(()=>permitted.value&&selected.value&&costFen.value!==null&&shareBps.value!==null&&!busy.value&&!loading.value&&!needsRead.value)
function clearConfirmation(){password.value='';confirming.value=false}
async function load(){if(!permitted.value||busy.value)return;const current=++epoch;loading.value=true;error.value='';clearConfirmation();selected.value=null;try{const result=await api<{items:Rule[];total:number}>(`/stores/profit-rules?search=${encodeURIComponent(search.value.trim())}&page=${page.value}&pageSize=20`);if(current===epoch){if(!Array.isArray(result.items)||!Number.isInteger(result.total))throw new Error("Unexpected result");items.value=result.items;total.value=result.total;needsRead.value=false}}catch{if(current===epoch){items.value=[];error.value='规格分润规则读取失败，请重新读取。'}}finally{if(current===epoch)loading.value=false}}
function edit(row:Rule){if(busy.value||loading.value||needsRead.value)return;selected.value={...row};cost.value=row.requiresReconfiguration||row.purchaseCostFen==null?'':(row.purchaseCostFen/100).toFixed(2);share.value=row.requiresReconfiguration||row.platformShareBps==null?'':String(row.platformShareBps/100);error.value='';notice.value='';clearConfirmation()}
function begin(){if(allowed.value){confirming.value=true;password.value=''}}
async function save(){if(!allowed.value||!confirming.value||!password.value||!selected.value)return;const row={...selected.value},body={expectedRevision:row.revision,purchaseCostFen:costFen.value!,platformShareBps:shareBps.value!},current=++epoch;busy.value=true;error.value='';try{const result=await confirmedWrite<Rule>('stores.profit.configure',password.value,`/stores/profit-rules/${encodeURIComponent(row.skuId)}`,'PUT',body,row.skuId,row.revision);if(current===epoch){if(result.skuId!==row.skuId||result.revision!==row.revision+1||result.purchaseCostFen!==body.purchaseCostFen||result.platformShareBps!==body.platformShareBps)throw new Error('Unexpected result');items.value=items.value.map(item=>item.skuId===result.skuId?result:item);selected.value=null;notice.value='规格分润规则已保存，仅影响后续订单；已有订单保持原快照。'}}catch{if(current===epoch){error.value='保存结果未确认，请重新读取规则并核对后再操作。';needsRead.value=true}}finally{if(current===epoch){busy.value=false;clearConfirmation()}}}
watch(()=>JSON.stringify([props.account.accountId,props.account.permissionCodes]),()=>{epoch++;items.value=[];selected.value=null;busy.value=false;loading.value=false;clearConfirmation();void load()})
onMounted(load);onUnmounted(()=>{epoch++;clearConfirmation()})
</script>
<template>
<section v-if="permitted" class="panel store-section" aria-labelledby="store-profit-title">
<h2 id="store-profit-title">商品规格进货价与分润</h2><p>按销售规格统一设置门店进货成本和平台分成比例。成本以每个销售单位计，不按库存基础单位计。</p>
<p>平台利润＝（订单实付－进货成本）×平台分成比例；门店结算＝进货成本＋门店利润－运费。运费由门店承担，金额以订单快照为准。</p>
<form class="store-search" aria-label="搜索规格分润规则" @submit.prevent="page=1;load()"><label for="store-rule-search">商品 / 规格 <input id="store-rule-search" v-model="search" type="search" maxlength="100" :disabled="busy||loading" /></label><button class="secondary-button" :disabled="busy||loading">查询</button><button type="button" class="secondary-button" :disabled="busy||loading" @click="load">重新读取规则</button></form>
<p v-if="loading" role="status">正在读取规格分润规则…</p><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<p v-if="!loading&&!error&&!items.length" class="empty-state">暂无符合条件的规格。请调整搜索条件，或先创建商品规格。</p>
<div v-if="items.length" class="table-wrap" tabindex="0" aria-label="商品规格分润列表，可横向滚动"><table><thead><tr><th>商品与规格</th><th>门店进货价</th><th>平台分成比例</th><th>操作</th></tr></thead><tbody><tr v-for="row in items" :key="row.skuId"><td>{{row.productName}}<small>{{row.specLabel||'默认规格'}} · {{row.skuCode}}</small><small v-if="row.requiresReconfiguration">销售单位已变化，请重新保存进货价与分成规则。</small></td><td>{{row.requiresReconfiguration?'需重新配置':row.purchaseCostFen==null?'未配置':amount(row.purchaseCostFen)}} / 每{{row.saleUnit}}</td><td>{{row.requiresReconfiguration?'需重新配置':row.platformShareBps==null?'未配置':`${row.platformShareBps/100}%`}}</td><td><button class="text-button" data-action="edit-rule" :disabled="busy||loading||needsRead||confirming" @click="edit(row)">设置分润</button></td></tr></tbody></table></div>
<div class="store-pagination"><span>共 {{total}} 个规格</span><button class="secondary-button" :disabled="page<=1||busy||loading" @click="page--;load()">上一页</button><button class="secondary-button" :disabled="page*20>=total||busy||loading" @click="page++;load()">下一页</button></div>
<form v-if="selected" class="store-form store-section" aria-label="规格分润设置" @submit.prevent="begin"><h3 class="wide">{{selected.productName}} · {{selected.specLabel||'默认规格'}}</h3><p v-if="selected.requiresReconfiguration" class="wide" role="alert">销售单位已变化，原规则不能用于当前规格。请按当前销售单位重新填写进货价与平台分成比例。</p><label for="store-purchase-cost">门店进货价（元 / 每{{selected.saleUnit}}）<input id="store-purchase-cost" v-model="cost" inputmode="decimal" maxlength="16" :disabled="busy||confirming" /><small>非负金额，最多两位小数。</small></label><label for="store-platform-share">平台分成比例（%）<input id="store-platform-share" v-model="share" inputmode="decimal" maxlength="6" :disabled="busy||confirming" /><small>0–100，最多两位小数。</small></label><p v-if="costFen===null||shareBps===null" class="wide" role="status">请填写有效的进货价和平台分成比例。</p><div class="store-actions wide"><button class="primary-button" data-action="save-rule" :disabled="!allowed||confirming">保存规格分润</button><button type="button" class="secondary-button" :disabled="busy" @click="selected=null;clearConfirmation()">取消编辑</button></div></form>
<form v-if="confirming" class="store-section" aria-label="确认保存规格分润" @submit.prevent="save"><h3>确认保存规格分润</h3><p>本次设置仅影响后续订单。请输入当前账号密码确认。</p><label for="store-profit-password">当前账号密码 <input id="store-profit-password" v-model="password" type="password" autocomplete="current-password" :disabled="busy" /></label><div class="store-actions"><button class="primary-button" :disabled="busy||!password">{{busy?'正在保存…':'确认保存分润'}}</button><button type="button" class="secondary-button" :disabled="busy" @click="clearConfirmation">取消确认</button></div></form>
</section>
</template>
