import {afterEach,describe,expect,it,vi} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import StoreProfitRulesPanel from '../../src/views/stores/StoreProfitRulesPanel.vue'
import {api,confirmedWrite,type Account} from '../../src/api'
vi.mock('../../src/api',()=>({api:vi.fn(),confirmedWrite:vi.fn()}))
const account={accountId:'admin',permissionCodes:['stores.manage']} as Account
const row={skuId:'sku-1',productName:'老挝啤酒',specKey:'synthetic-axis-id:synthetic-option-id',specLabel:'330ml / 箱',skuCode:'BEER-BOX',saleUnit:'箱',purchaseCostFen:null,platformShareBps:null,revision:0}
const wrappers:ReturnType<typeof mount>[]=[]
afterEach(()=>{wrappers.splice(0).forEach(w=>w.unmount());vi.resetAllMocks()})
async function setup(){vi.mocked(api).mockResolvedValue({items:[row],total:1,page:1,pageSize:20});const w=mount(StoreProfitRulesPanel,{props:{account}});wrappers.push(w);await flushPromises();return w}
describe('SKU store profit rules',()=>{
 it('shows unconfigured per-sale-unit costs and searches server rows',async()=>{const w=await setup();expect(w.text()).toContain('每箱');expect(w.text()).toContain('330ml / 箱');expect(w.text()).not.toContain('synthetic-axis-id');expect(w.text()).toContain('未配置');await w.get('input[type="search"]').setValue('啤酒');await w.get('form[aria-label="搜索规格分润规则"]').trigger('submit');await flushPromises();expect(vi.mocked(api).mock.lastCall?.[0]).toContain('search=%E5%95%A4%E9%85%92')})
 it('confirms exact fen and basis point values and clears confirmation',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60.00');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockResolvedValue({...row,purchaseCostFen:6000,platformShareBps:2000,revision:1});await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.profit.configure','synthetic-password','/stores/profit-rules/sku-1','PUT',{expectedRevision:0,purchaseCostFen:6000,platformShareBps:2000},'sku-1',0);expect(w.find('#store-profit-password').exists()).toBe(false);expect(w.text()).toContain('规格分润规则已保存')})
 it('rejects invalid currency and shares rather than rounding user input',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');for(const invalid of ['-1','1.001','1e2','']){await w.get('#store-purchase-cost').setValue(invalid);await w.get('#store-platform-share').setValue('20');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()}await w.get('#store-purchase-cost').setValue('60');for(const invalid of ['100.01','-1','20.001']){await w.get('#store-platform-share').setValue(invalid);expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()}})
 it('requires readback after unknown write and removes password from errors',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockRejectedValue(new Error('synthetic-password'));await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(w.text()).toContain('重新读取');expect(w.text()).not.toContain('synthetic-password');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()})
 it('clears stale prices after a sales unit version change and requires new inputs',async()=>{vi.mocked(api).mockResolvedValue({items:[{...row,purchaseCostFen:6000,platformShareBps:2000,revision:3,requiresReconfiguration:true}],total:1});const w=mount(StoreProfitRulesPanel,{props:{account}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('需重新配置');expect(w.text()).not.toContain('¥60.00');await w.get('button[data-action="edit-rule"]').trigger('click');expect(w.get('#store-purchase-cost').element).toHaveProperty('value','');expect(w.get('#store-platform-share').element).toHaveProperty('value','');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined();expect(w.text()).toContain('原规则不能用于当前规格')})

 it('uses a readable default when a specification label is absent',async()=>{vi.mocked(api).mockResolvedValue({items:[{...row,specLabel:undefined}],total:1});const w=mount(StoreProfitRulesPanel,{props:{account}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('默认规格');expect(w.text()).not.toContain('synthetic-axis-id');await w.get('button[data-action="edit-rule"]').trigger('click');expect(w.get('h3').text()).toContain('默认规格')})

})
