import {afterEach,describe,expect,it,vi} from 'vitest'
import {defineComponent} from 'vue'
import {webcrypto} from 'node:crypto'
import {mount,flushPromises} from '@vue/test-utils'
import StoreProfitRulesPanel from '../../src/views/stores/StoreProfitRulesPanel.vue'
import {api,confirmedWrite,type Account} from '../../src/api'
vi.mock('../../src/api',()=>({api:vi.fn(),confirmedWrite:vi.fn()}))
const account={accountId:'admin',permissionCodes:['stores.manage']} as Account
const row={skuId:'sku-1',productName:'老挝啤酒',specKey:'synthetic-axis-id:synthetic-option-id',specLabel:'330ml / 箱',skuCode:'BEER-BOX',saleUnit:'箱',purchaseCostFen:null,platformShareBps:null,revision:0}
const dialogStub=defineComponent({props:['modelValue','title'],template:'<section v-if="modelValue" role="dialog"><h2>{{title}}</h2><slot/><slot name="footer"/></section>'})
const mountOptions={global:{stubs:{ElDialog:dialogStub}}}
const wrappers:ReturnType<typeof mount>[]=[]
afterEach(()=>{vi.unstubAllGlobals();wrappers.splice(0).forEach(w=>w.unmount());vi.resetAllMocks()})
async function setup(){vi.mocked(api).mockResolvedValue({items:[row],total:1,page:1,pageSize:20});const w=mount(StoreProfitRulesPanel,{...mountOptions,props:{account}});wrappers.push(w);await flushPromises();return w}
describe('SKU store profit rules',()=>{
 it('shows unconfigured per-sale-unit costs and searches server rows',async()=>{const w=await setup();expect(w.text()).toContain('每箱');expect(w.text()).toContain('330ml / 箱');expect(w.text()).not.toContain('synthetic-axis-id');expect(w.text()).toContain('未配置');await w.get('input[type="search"]').setValue('啤酒');await w.get('form[aria-label="搜索规格分润规则"]').trigger('submit');await flushPromises();expect(vi.mocked(api).mock.lastCall?.[0]).toContain('search=%E5%95%A4%E9%85%92')})
 it('confirms exact fen and basis point values and clears confirmation',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60.00');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockResolvedValue({...row,purchaseCostFen:6000,platformShareBps:2000,revision:1});await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.profit.configure','synthetic-password','/stores/profit-rules/sku-1','PUT',{expectedRevision:0,purchaseCostFen:6000,platformShareBps:2000},'sku-1',0);expect(w.find('#store-profit-password').exists()).toBe(false);expect(w.text()).toContain('规格分润规则已保存')})
 it('rejects invalid currency and shares rather than rounding user input',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');for(const invalid of ['-1','1.001','1e2','']){await w.get('#store-purchase-cost').setValue(invalid);await w.get('#store-platform-share').setValue('20');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()}await w.get('#store-purchase-cost').setValue('60');for(const invalid of ['100.01','-1','20.001']){await w.get('#store-platform-share').setValue(invalid);expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()}})
 it('requires readback after unknown write and removes password from errors',async()=>{const w=await setup();await w.get('button[data-action="edit-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockRejectedValue(new Error('synthetic-password'));await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(w.text()).toContain('重新读取');expect(w.text()).not.toContain('synthetic-password');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined()})
 it('clears stale prices after a sales unit version change and requires new inputs',async()=>{vi.mocked(api).mockResolvedValue({items:[{...row,purchaseCostFen:6000,platformShareBps:2000,revision:3,requiresReconfiguration:true}],total:1});const w=mount(StoreProfitRulesPanel,{...mountOptions,props:{account}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('需重新配置');expect(w.text()).not.toContain('¥60.00');await w.get('button[data-action="edit-rule"]').trigger('click');expect(w.get('#store-purchase-cost').element).toHaveProperty('value','');expect(w.get('#store-platform-share').element).toHaveProperty('value','');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined();expect(w.text()).toContain('原规则不能用于当前规格')})

 it('edits only inside an accessible modal and closes without writing',async()=>{const w=await setup();expect(w.find('[role="dialog"]').exists()).toBe(false);await w.get('button[data-action="edit-rule"]').trigger('click');expect(w.get('[role="dialog"] #store-purchase-cost').exists()).toBe(true);await w.get('button[data-action="close-rule"]').trigger('click');expect(w.find('[role="dialog"]').exists()).toBe(false);expect(confirmedWrite).not.toHaveBeenCalled()})
 it('atomically submits selected revisions with a bound batch confirmation',async()=>{vi.stubGlobal('crypto',webcrypto);vi.mocked(api).mockResolvedValue({items:[{...row,skuId:'00000000-0000-0000-0000-000000000002'},{...row,skuId:'00000000-0000-0000-0000-000000000001',revision:2}],total:2});const w=mount(StoreProfitRulesPanel,{...mountOptions,props:{account}});wrappers.push(w);await flushPromises();await w.get('input[data-action="select-page"]').setValue(true);await w.get('button[data-action="batch-rule"]').trigger('click');expect(w.get('[role="dialog"]').text()).toContain('2 个规格');await w.get('#store-purchase-cost').setValue('60');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');const saved=[{...row,skuId:'00000000-0000-0000-0000-000000000001',purchaseCostFen:6000,platformShareBps:2000,revision:3},{...row,skuId:'00000000-0000-0000-0000-000000000002',purchaseCostFen:6000,platformShareBps:2000,revision:1}];vi.mocked(confirmedWrite).mockResolvedValue({items:saved});await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.profit.batch.configure','synthetic-password','/stores/profit-rules','POST',{items:[{skuId:'00000000-0000-0000-0000-000000000001',expectedRevision:2},{skuId:'00000000-0000-0000-0000-000000000002',expectedRevision:0}],purchaseCostFen:6000,platformShareBps:2000},expect.stringMatching(/^[0-9a-f]{64}$/),0);expect(w.text()).toContain('已保存 2 个规格');expect(w.find('[role="dialog"]').exists()).toBe(false)})
 it('keeps the modal and inputs after a batch conflict and blocks resubmission until readback',async()=>{vi.stubGlobal('crypto',webcrypto);const w=await setup();await w.get('input[data-action="select-page"]').setValue(true);await w.get('button[data-action="batch-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockRejectedValue(new Error('revision conflict'));await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(w.get('[role="dialog"]').text()).toContain('重新读取规则');expect(w.get('#store-purchase-cost').element).toHaveProperty('value','60');expect(w.get('button[data-action="save-rule"]').attributes('disabled')).toBeDefined();expect(w.find('#store-profit-password').exists()).toBe(false);await w.get('button[data-action="close-rule"]').trigger('click');await w.get('form[aria-label="搜索规格分润规则"]').trigger('submit');await flushPromises();await w.get('input[data-action="select-page"]').setValue(true);expect(w.get('button[data-action="batch-rule"]').attributes('disabled')).toBeUndefined()})
 it('never treats a partial batch response as successful',async()=>{vi.stubGlobal('crypto',webcrypto);const w=await setup();await w.get('input[data-action="select-page"]').setValue(true);await w.get('button[data-action="batch-rule"]').trigger('click');await w.get('#store-purchase-cost').setValue('60');await w.get('#store-platform-share').setValue('20');await w.get('form[aria-label="规格分润设置"]').trigger('submit');await w.get('#store-profit-password').setValue('synthetic-password');vi.mocked(confirmedWrite).mockResolvedValue({items:[]});await w.get('form[aria-label="确认保存规格分润"]').trigger('submit');await flushPromises();expect(w.text()).toContain('保存结果未确认');expect(w.text()).not.toContain('已保存 0 个规格')})
 it('has no configuration surface without permission',async()=>{const w=mount(StoreProfitRulesPanel,{...mountOptions,props:{account:{...account,permissionCodes:[]}}});wrappers.push(w);await flushPromises();expect(w.find('section').exists()).toBe(false);expect(api).not.toHaveBeenCalled()})
 it('clears current-page selection when the search result changes',async()=>{const w=await setup();await w.get('input[data-action="select-page"]').setValue(true);expect(w.get('button[data-action="batch-rule"]').attributes('disabled')).toBeUndefined();await w.get('form[aria-label="搜索规格分润规则"]').trigger('submit');await flushPromises();expect(w.get('button[data-action="batch-rule"]').attributes('disabled')).toBeDefined()})
 it('uses a readable default when a specification label is absent',async()=>{vi.mocked(api).mockResolvedValue({items:[{...row,specLabel:undefined}],total:1});const w=mount(StoreProfitRulesPanel,{...mountOptions,props:{account}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('默认规格');expect(w.text()).not.toContain('synthetic-axis-id');await w.get('button[data-action="edit-rule"]').trigger('click');expect(w.get('h3').text()).toContain('默认规格')})

})
