import {afterEach,describe,expect,it,vi} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import {createRouter,createMemoryHistory} from 'vue-router'
import StoreAccountDetailView from '../../src/views/stores/StoreAccountDetailView.vue'
import {api,type Account} from '../../src/api'
vi.mock('../../src/api',()=>({api:vi.fn(),confirmedWrite:vi.fn()}))
const wrappers:ReturnType<typeof mount>[]=[]
afterEach(()=>{wrappers.splice(0).forEach(w=>w.unmount());vi.resetAllMocks()})
describe('actual store finance account',()=>{
 it('shows actual calculated income, exceptions and masked payout details',async()=>{vi.mocked(api).mockResolvedValue({storeId:'s1',storeName:'湘江路店',settlementReady:true,withdrawalReady:true,reason:'',balance:{pendingFen:0,availableFen:8200,frozenFen:1000,paidFen:0},income:[{id:'i1',orderId:'o1',orderNo:'ORD001',paidFen:10000,costFen:6000,platformFen:800,freightFen:1000,storeFen:8200,status:'SETTLED',reason:'',availableAt:null,settledAt:null},{id:'i2',orderId:'o2',orderNo:'ORD002',paidFen:100,costFen:null,platformFen:null,freightFen:0,storeFen:null,status:'HELD',reason:'负利润待核对',availableAt:null,settledAt:null}],withdrawals:[{id:'w1',amountFen:1000,payeeName:'测试店长',bankName:'测试银行',bankAccount:'****1234',status:'APPROVED_PENDING_PAYMENT',revision:1,reason:'',createdAt:'2026-10-10T10:00:00Z',paidAt:null,paymentReference:''}]});const router=createRouter({history:createMemoryHistory(),routes:[{path:'/stores/accounts/:storeId',component:StoreAccountDetailView}]});await router.push('/stores/accounts/s1');const w=mount(StoreAccountDetailView,{props:{account:{accountId:'a1',permissionCodes:['stores.accounts.read']} as Account},global:{plugins:[router]}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('¥82.00');expect(w.text()).toContain('¥8.00');expect(w.text()).toContain('前置仓承担运费');expect(w.text()).toContain('待人工核对');expect(w.text()).toContain('****1234');expect(w.text()).toContain('审核通过，待线下发放');expect(w.text()).not.toContain('登记线下发放')})
 it('clears previous account content and offers retry after read failure',async()=>{vi.mocked(api).mockRejectedValue(new Error('账户暂不可读'));const router=createRouter({history:createMemoryHistory(),routes:[{path:'/stores/accounts/:storeId',component:StoreAccountDetailView}]});await router.push('/stores/accounts/s1');const w=mount(StoreAccountDetailView,{props:{account:{accountId:'a1',permissionCodes:['stores.accounts.read']} as Account},global:{plugins:[router]}});wrappers.push(w);await flushPromises();expect(w.text()).toContain('账户暂不可读');vi.mocked(api).mockResolvedValue({storeId:'s1',storeName:'湘江路店',settlementReady:true,withdrawalReady:true,reason:'',balance:{pendingFen:0,availableFen:0,frozenFen:0,paidFen:0},income:[],withdrawals:[]});await w.findAll('button').find(b=>b.text()==='重试')!.trigger('click');await flushPromises();expect(w.text()).toContain('暂无提现申请');expect(w.text()).toContain('暂无结算收入明细')})

})
