import {afterEach,describe,expect,it,vi} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
import StoreWithdrawalReview from '../../src/views/stores/StoreWithdrawalReview.vue'
import {confirmedWrite,type Account} from '../../src/api'
vi.mock('../../src/api',()=>({confirmedWrite:vi.fn()}))
const account={accountId:'admin',permissionCodes:['stores.accounts.manage']} as Account
const item={id:'w1',amountFen:9200,payeeName:'测试店长',bankName:'测试银行',bankAccount:'****1234',status:'PENDING_REVIEW',revision:1,reason:'',createdAt:'2026-10-10',paidAt:null,paymentReference:''}
const wrappers:ReturnType<typeof mount>[]=[]
afterEach(()=>{wrappers.splice(0).forEach(w=>w.unmount());vi.resetAllMocks()})
function setup(status='PENDING_REVIEW',permissions=account){const w=mount(StoreWithdrawalReview,{props:{account:permissions,storeId:'s1',item:{...item,status}}});wrappers.push(w);return w}
describe('platform offline withdrawal review',()=>{
 it('requires rejection reason and password and confirms scoped revision',async()=>{const w=setup();await w.get('button[data-action="reject"]').trigger('click');expect(w.get('button[type="submit"]').attributes('disabled')).toBeDefined();await w.get('#withdrawal-reason-w1').setValue('收款信息有误');await w.get('#withdrawal-password-w1').setValue('synthetic-password');vi.mocked(confirmedWrite).mockResolvedValue({...item,status:'REJECTED',revision:2});await w.get('form').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.withdrawal.review','synthetic-password','/stores/s1/withdrawals/w1/review','POST',{expectedRevision:1,decision:'REJECT',reason:'收款信息有误'},'w1',1);expect(w.emitted('refresh')).toHaveLength(1);expect(w.find('input[type="password"]').exists()).toBe(false)})
 it('separates approval from actual offline payment with mandatory voucher',async()=>{const w=setup('APPROVED_PENDING_PAYMENT');expect(w.text()).toContain('登记线下发放');await w.get('button[data-action="pay"]').trigger('click');await w.get('#withdrawal-password-w1').setValue('synthetic-password');expect(w.get('button[type="submit"]').attributes('disabled')).toBeDefined();await w.get('#withdrawal-reference-w1').setValue('银行流水-001');vi.mocked(confirmedWrite).mockResolvedValue({...item,status:'PAID',revision:2});await w.get('form').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.withdrawal.pay','synthetic-password','/stores/s1/withdrawals/w1/pay','POST',{expectedRevision:1,paymentReference:'银行流水-001',reason:''},'w1',1)})
 it('confirms full payee access and clears sensitive details on close',async()=>{const w=setup('APPROVED_PENDING_PAYMENT');await w.get('button[data-action="payee"]').trigger('click');await w.get('#withdrawal-password-w1').setValue('synthetic-password');vi.mocked(confirmedWrite).mockResolvedValue({payeeName:'测试店长',bankName:'测试银行',bankAccount:'synthetic-full-account'});await w.get('form').trigger('submit');await flushPromises();expect(confirmedWrite).toHaveBeenCalledWith('stores.withdrawal.payee','synthetic-password','/stores/s1/withdrawals/w1/payee','POST',{expectedRevision:1},'w1',1);expect(w.text()).toContain('synthetic-full-account');await w.findAll('button').find(b=>b.text()==='隐藏收款信息')!.trigger('click');expect(w.text()).not.toContain('synthetic-full-account')})
 it('hides money actions without live permission and closes on revocation',async()=>{const w=setup();await w.get('button[data-action="approve"]').trigger('click');await w.get('#withdrawal-password-w1').setValue('synthetic-password');await w.setProps({account:{accountId:'admin',permissionCodes:['stores.accounts.read']} as Account});expect(w.find('form').exists()).toBe(false);expect(w.find('button').exists()).toBe(false);expect(confirmedWrite).not.toHaveBeenCalled()})
 it('disables repeated actions after unknown outcome and requests readback',async()=>{const w=setup();await w.get('button[data-action="approve"]').trigger('click');await w.get('#withdrawal-password-w1').setValue('synthetic-password');vi.mocked(confirmedWrite).mockRejectedValue(new Error('synthetic-password'));await w.get('form').trigger('submit');await flushPromises();expect(w.text()).toContain('重新读取');expect(w.text()).not.toContain('synthetic-password');expect(w.get('button[data-action="approve"]').attributes('disabled')).toBeDefined()})
})
