# Generated by Django 5.2.17 on 2026-09-27 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('customers', '0006_operation_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_price', models.PositiveIntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=8)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
            ],
            options={
                'db_table': 'points_exchange_offer',
            },
        ),
        migrations.CreateModel(
            name='ExchangeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('action', models.CharField(max_length=12)),
                ('digest', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points_exchange.exchangeoffer')),
            ],
            options={
                'db_table': 'points_exchange_operation',
            },
        ),
        migrations.CreateModel(
            name='ExchangeQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_id', models.UUIDField(null=True)),
                ('snapshot', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points_exchange.exchangeoffer')),
            ],
            options={
                'db_table': 'points_exchange_quote',
            },
        ),
        migrations.AddIndex(
            model_name='exchangeoffer',
            index=models.Index(fields=['status', '-created_at'], name='exchange_offer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangeoffer',
            constraint=models.CheckConstraint(condition=models.Q(('points_price__gte', 1), ('points_price__lte', 1000000)), name='exchange_price_bounded'),
        ),
        migrations.AddConstraint(
            model_name='exchangeoffer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ON_SALE', 'OFF_SALE'])), name='exchange_offer_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='exchangeoperation',
            constraint=models.UniqueConstraint(fields=('actor', 'key'), name='exchange_actor_key_unique'),
        ),
        migrations.AddIndex(
            model_name='exchangequote',
            index=models.Index(fields=['member', '-created_at'], name='exchange_quote_member_idx'),
        ),
    ]
