# Generated by Django 5.2.17 on 2026-09-27 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeThreshold',
            fields=[
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='catalog.membergrade')),
                ('minimum_spend_fen', models.PositiveBigIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'customer_grade_threshold',
            },
        ),
        migrations.CreateModel(
            name='MemberConsumption',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='customers.member')),
                ('effective_spend_fen', models.PositiveBigIntegerField(default=0)),
                ('grade_effective_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'customer_member_consumption',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionOrder',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('effective_spend_fen', models.PositiveBigIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'customer_consumption_order',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('amount_fen', models.BigIntegerField()),
                ('balance_fen', models.PositiveBigIntegerField()),
                ('grade_id_before', models.UUIDField()),
                ('grade_id_after', models.UUIDField()),
                ('source_ref', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'customer_consumption_event',
                'indexes': [models.Index(fields=['member', '-created_at'], name='consume_member_time_idx')],
            },
        ),
    ]
