# Generated by Django 5.2.17 on 2026-09-27 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_gradethreshold_memberconsumption_consumptionorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRuleChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(unique=True)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_member_rule_change',
                'constraints': [models.UniqueConstraint(fields=('actor', 'request_key'), name='member_rule_actor_key_unique')],
            },
        ),
    ]
