# Generated by Django 5.2.17 on 2026-09-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_member_rule_change_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberconsumption',
            name='grade_policy_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberconsumption',
            name='grade_thresholds',
            field=models.JSONField(default=list),
        ),
    ]
