# Generated by Django 5.2.17 on 2026-09-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('customers', '0005_active_grade_rules'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['-created_at', '-id'], name='member_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['grade', 'enabled', '-created_at'], name='member_grade_state_idx'),
        ),
    ]
