# Generated by Django 5.2.17 on 2026-09-30 14:46

import customers.profile
import secrets
import string
from zoneinfo import ZoneInfo
from django.db import migrations, models


def populate_numbers(apps, schema_editor):
    Member = apps.get_model("customers", "Member")
    allocated = set()
    current_stamp = None
    for row in Member.objects.using(schema_editor.connection.alias).order_by("created_at", "id").iterator():
        stamp = row.created_at.astimezone(ZoneInfo('Asia/Shanghai')).strftime('%Y%m%d%H%M%S')
        if stamp != current_stamp:
            allocated = set()
            current_stamp = stamp
        for attempt in range(1000):
            suffix = [secrets.choice(string.ascii_letters), secrets.choice(string.digits),
                      secrets.choice(string.ascii_letters + string.digits)]
            secrets.SystemRandom().shuffle(suffix)
            number = 'm' + stamp + ''.join(suffix)
            if number not in allocated:
                break
        else:
            raise RuntimeError("Member number allocation exhausted")
        allocated.add(number)
        Member.objects.using(schema_editor.connection.alias).filter(pk=row.pk).update(member_no=number)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_operation_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar_path',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='member_no',
            field=models.CharField(editable=False, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='member', name='member_no',
            field=models.CharField(default=customers.profile.member_number, editable=False, max_length=18),
        ),
        migrations.AddConstraint(
            model_name='member', constraint=models.UniqueConstraint(fields=['member_no'], name='unique_member_number'),
        ),
    ]
