# Generated by Django 5.2.17 on 2026-09-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_member_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfileQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=16)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.member')),
            ],
            options={
                'db_table': 'customer_profile_quota',
                'constraints': [models.UniqueConstraint(fields=('member', 'scope'), name='member_profile_quota_scope')],
            },
        ),
    ]
