# Generated by Django 5.2.17 on 2026-09-25 12:10

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_alter_asset_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_no', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=9)),
                ('reason', models.CharField(max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('confirmation_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_inbounds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inbounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_inbound',
            },
        ),
        migrations.CreateModel(
            name='InboundLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('operation_unit', models.CharField(max_length=30)),
                ('ratio', models.PositiveIntegerField()),
                ('base_quantity', models.PositiveBigIntegerField()),
                ('base_unit', models.CharField(max_length=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.inbounddocument')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
                ('unit_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.skuunitversion')),
            ],
            options={
                'db_table': 'inventory_inbound_line',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouse',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='warehouse_code_upper_unique'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_warehouse')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_unit', models.CharField(max_length=30)),
                ('operation_quantity', models.PositiveBigIntegerField()),
                ('ratio', models.PositiveIntegerField()),
                ('delta_base_units', models.BigIntegerField()),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inbound_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.inboundline')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
                ('unit_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.skuunitversion')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_ledger',
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand_base_units', models.BigIntegerField(default=0)),
                ('reserved_base_units', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_balance',
            },
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.UniqueConstraint(fields=('document', 'sku'), name='inbound_line_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inbound_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.CheckConstraint(condition=models.Q(('ratio__gt', 0)), name='inbound_ratio_positive'),
        ),
        migrations.AddConstraint(
            model_name='inboundline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='inbound_base_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['warehouse', 'sku', '-occurred_at'], name='ledger_wh_sku_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(('operation_quantity__gt', 0)), name='ledger_operation_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(('delta_base_units__gt', 0)), name='ledger_inbound_delta_positive'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['sku', 'warehouse'], name='inventory_balance_sku_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'sku'), name='inventory_balance_wh_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_base_units__gte', 0)), name='inventory_on_hand_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_base_units__gte', 0)), name='inventory_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_base_units__lte', models.F('on_hand_base_units'))), name='inventory_reserved_not_over_hand'),
        ),
        migrations.AddIndex(
            model_name='inbounddocument',
            index=models.Index(fields=['warehouse', 'status', '-created_at'], name='inbound_wh_status_created_idx'),
        ),
    ]
