# Generated by Django 5.2.17 on 2026-09-25 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_immutable_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounddocument',
            name='creation_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inbounddocument',
            name='creation_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='inbounddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('created_by', 'creation_key'), name='inbound_actor_creation_key_unique'),
        ),
    ]
