# Generated by Django 5.2.17 on 2026-09-25 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_asset_kind'),
        ('inventory', '0003_inbounddocument_creation_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_no', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=9)),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damage'), ('SAMPLE', 'Sample'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('creation_key', models.UUIDField()),
                ('creation_digest', models.CharField(max_length=64)),
                ('confirmation_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_outbound',
            },
        ),
        migrations.CreateModel(
            name='OutboundLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('operation_unit', models.CharField(max_length=30)),
                ('ratio', models.PositiveIntegerField()),
                ('base_quantity', models.PositiveBigIntegerField()),
                ('base_unit', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'inventory_outbound_line',
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_inbound_delta_positive',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=8),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='inbound_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inboundline'),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_outbounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_outbounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbounddocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='outboundline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.outbounddocument'),
        ),
        migrations.AddField(
            model_name='outboundline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku'),
        ),
        migrations.AddField(
            model_name='outboundline',
            name='unit_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.skuunitversion'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='outbound_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.outboundline'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['movement_type', '-occurred_at'], name='ledger_type_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('outbound_line__isnull', True)), models.Q(('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('outbound_line__isnull', False)), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
        migrations.AddIndex(
            model_name='outbounddocument',
            index=models.Index(fields=['warehouse', 'status', '-created_at'], name='outbound_wh_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='outbounddocument',
            constraint=models.UniqueConstraint(fields=('created_by', 'creation_key'), name='outbound_actor_creation_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.UniqueConstraint(fields=('document', 'sku'), name='outbound_line_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='outbound_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.CheckConstraint(condition=models.Q(('ratio__gt', 0)), name='outbound_ratio_positive'),
        ),
        migrations.AddConstraint(
            model_name='outboundline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='outbound_base_quantity_positive'),
        ),
    ]
