# Generated by Django 5.2.17 on 2026-09-25 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_asset_kind'),
        ('inventory', '0004_outbounddocument_outboundline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField(unique=True)),
                ('action', models.CharField(max_length=16)),
                ('request_digest', models.CharField(max_length=64)),
                ('result_revision', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_stocktake_action',
            },
        ),
        migrations.CreateModel(
            name='StocktakeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_no', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('COUNTING', 'Counting'), ('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved')], default='COUNTING', max_length=14)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('creation_key', models.UUIDField()),
                ('creation_digest', models.CharField(max_length=64)),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_stocktake',
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_unit', models.CharField(max_length=30)),
                ('book_at_start_base_units', models.BigIntegerField()),
                ('book_at_submit_base_units', models.BigIntegerField(blank=True, null=True)),
                ('reserved_at_submit_base_units', models.BigIntegerField(blank=True, null=True)),
                ('balance_updated_at_at_submit', models.DateTimeField(blank=True, null=True)),
                ('counted_base_units', models.BigIntegerField(blank=True, null=True)),
                ('delta_base_units', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'inventory_stocktake_line',
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_direction_and_source_valid',
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment')], default='INBOUND', max_length=10),
        ),
        migrations.AddField(
            model_name='stocktakeaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stocktakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_stocktakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakedocument',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_stocktakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakedocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktakeaction',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocktakedocument'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.stocktakedocument'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='unit_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.skuunitversion'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='stocktake_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocktakeline'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('outbound_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('inbound_line__isnull', True), ('movement_type', 'ADJUSTMENT'), ('outbound_line__isnull', True), ('stocktake_line__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
        migrations.AddIndex(
            model_name='stocktakedocument',
            index=models.Index(fields=['warehouse', 'status', '-created_at'], name='stocktake_wh_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakedocument',
            constraint=models.UniqueConstraint(fields=('created_by', 'creation_key'), name='stocktake_actor_creation_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.UniqueConstraint(fields=('document', 'sku'), name='stocktake_line_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.CheckConstraint(condition=models.Q(('book_at_start_base_units__gte', 0)), name='stocktake_start_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_base_units__isnull', True), ('counted_base_units__gte', 0), _connector='OR'), name='stocktake_count_nonnegative'),
        ),
    ]
