# Generated by Django 5.2.17 on 2026-09-25 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktake_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('CONSUME', 'Consume')], max_length=8)),
                ('base_quantity', models.PositiveBigIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_reservation_event',
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_quantity', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CONSUMED', 'Consumed')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybalance')),
            ],
            options={
                'db_table': 'inventory_reservation',
            },
        ),
    ]
