# Generated by Django 5.2.17 on 2026-09-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryreservationevent_inventoryreservation'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='order_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='inventoryreservationevent',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.inventoryreservation'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='reservation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservationevent',
            constraint=models.UniqueConstraint(fields=('reservation', 'action'), name='reservation_action_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservationevent',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='reservation_event_quantity_positive'),
        ),
    ]
