# Generated by Django 5.2.17 on 2026-09-26 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sku_driven_product_sale'),
        ('inventory', '0007_inventoryreservation_order_line_and_more'),
        ('orders', '0003_settlement_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_direction_and_source_valid',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='order_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.orderline'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale')], default='INBOUND', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('inbound_line__isnull', True), ('movement_type', 'ADJUSTMENT'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), models.Q(('actor__isnull', True), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'SALE'), ('order_line__isnull', False), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
    ]
