# Generated by Django 5.2.17 on 2026-09-27 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('inventory', '0008_order_sale_ledger'),
        ('orders', '0007_orderline_redeem_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_direction_and_source_valid',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='refund_case_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='refund_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_ledgers', to='orders.orderline'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('REFUND', 'Unshipped refund')], default='INBOUND', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('inbound_line__isnull', True), ('movement_type', 'ADJUSTMENT'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), models.Q(('actor__isnull', True), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'SALE'), ('order_line__isnull', False), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('delta_base_units__gt', 0), ('inbound_line__isnull', True), ('movement_type', 'REFUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('refund_case_id__isnull', False), ('refund_order_line__isnull', False), ('stocktake_line__isnull', True)), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'REFUND'), ('refund_case_id__isnull', False), ('refund_order_line__isnull', False)), models.Q(models.Q(('movement_type', 'REFUND'), _negated=True), ('refund_case_id__isnull', True), ('refund_order_line__isnull', True)), _connector='OR'), name='ledger_refund_source_shape'),
        ),
    ]
