# Generated by Django 5.2.17 on 2026-09-27 03:57

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_redeem_valid_until'),
        ('inventory', '0009_remove_inventoryledger_ledger_direction_and_source_valid_and_more'),
        ('orders', '0007_orderline_redeem_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(unique=True)),
                ('acceptance_id', models.UUIDField(unique=True)),
                ('received_quantity', models.PositiveIntegerField()),
                ('salable_quantity', models.PositiveIntegerField()),
                ('damaged_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_return_disposition',
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_direction_and_source_valid',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='return_case_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='return_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_ledgers', to='orders.orderline'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('REFUND', 'Unshipped refund'), ('RETURN', 'Accepted return')], default='INBOUND', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('inbound_line__isnull', True), ('movement_type', 'ADJUSTMENT'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), models.Q(('actor__isnull', True), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'SALE'), ('order_line__isnull', False), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('delta_base_units__gt', 0), ('inbound_line__isnull', True), ('movement_type', 'REFUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('refund_case_id__isnull', False), ('refund_order_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', True), ('movement_type', 'RETURN'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('return_case_id__isnull', False), ('return_order_line__isnull', False), ('stocktake_line__isnull', True)), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RETURN'), ('return_case_id__isnull', False), ('return_order_line__isnull', False)), models.Q(models.Q(('movement_type', 'RETURN'), _negated=True), ('return_case_id__isnull', True), ('return_order_line__isnull', True)), _connector='OR'), name='ledger_return_source_shape'),
        ),
        migrations.AddField(
            model_name='returndisposition',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returndisposition',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderline'),
        ),
        migrations.AddConstraint(
            model_name='returndisposition',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity', django.db.models.expressions.CombinedExpression(models.F('salable_quantity'), '+', models.F('damaged_quantity')))), name='return_disposition_quantities'),
        ),
    ]
