# Generated by Django 5.2.17 on 2026-10-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_unit_conversion'),
        ('customers', '0009_address_location'),
        ('inventory', '0012_pool_evidence_guards'),
        ('orders', '0014_order_order_paid_fact_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryledger',
            name='ledger_direction_and_source_valid',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='store_adjustment_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='store_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.member'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('REFUND', 'Unshipped refund'), ('RETURN', 'Accepted return'), ('STORE_SET', 'Store available stock set')], default='INBOUND', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'STORE_SET'), ('store_adjustment_id__isnull', False), ('store_member__isnull', False)), models.Q(models.Q(('movement_type', 'STORE_SET'), _negated=True), ('store_adjustment_id__isnull', True), ('store_member__isnull', True)), _connector='OR'), name='ledger_store_source_shape'),
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('inbound_line__isnull', True), ('movement_type', 'STORE_SET'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', True), ('store_adjustment_id__isnull', False), ('store_member__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', False), ('movement_type', 'INBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'OUTBOUND'), ('order_line__isnull', True), ('outbound_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('inbound_line__isnull', True), ('movement_type', 'ADJUSTMENT'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('stocktake_line__isnull', False), models.Q(('delta_base_units__gt', 0), ('delta_base_units__lt', 0), _connector='OR')), models.Q(('actor__isnull', True), ('delta_base_units__lt', 0), ('inbound_line__isnull', True), ('movement_type', 'SALE'), ('order_line__isnull', False), ('outbound_line__isnull', True), ('stocktake_line__isnull', True)), models.Q(('delta_base_units__gt', 0), ('inbound_line__isnull', True), ('movement_type', 'REFUND'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('refund_case_id__isnull', False), ('refund_order_line__isnull', False), ('stocktake_line__isnull', True)), models.Q(('actor__isnull', False), ('delta_base_units__gt', 0), ('inbound_line__isnull', True), ('movement_type', 'RETURN'), ('order_line__isnull', True), ('outbound_line__isnull', True), ('return_case_id__isnull', False), ('return_order_line__isnull', False), ('stocktake_line__isnull', True)), _connector='OR'), name='ledger_direction_and_source_valid'),
        ),
    ]
