<script setup lang="ts">
import {computed,ref,watch,onUnmounted} from 'vue'
import {ElCheckbox,ElTag} from 'element-plus'
import 'element-plus/theme-chalk/el-checkbox.css'
import 'element-plus/theme-chalk/el-tag.css'
import {api,type Account} from '../../api'
import {campaignError,type CampaignForm} from './form.mjs'
const props=defineProps<{modelValue:CampaignForm;account:Account;disabled:boolean;productNames:{id:string;name:string}[]}>(),emit=defineEmits<{ 'update:modelValue':[CampaignForm] }>()
const form=computed({get:()=>props.modelValue,set:v=>emit('update:modelValue',v)}),keyword=ref(''),searching=ref(false),searchError=ref(''),products=ref<{id:string;name:string}[]>([]),productPage=ref(1),productTotal=ref(0)
const names=ref<{id:string;name:string}[]>([])
watch(()=>props.productNames,v=>{names.value=[...v]},{immediate:true})
const validation=computed(()=>campaignError(form.value))
let sequence=0
function update(key:keyof CampaignForm,value:unknown){form.value={...form.value,[key]:value}}
async function search(reset=true){if(props.disabled||!props.account.permissionCodes.includes('coupon.manage'))return;if(reset)productPage.value=1;const seq=++sequence;searching.value=true;searchError.value='';products.value=[];try{const r=await api<{items:{id:string;name:string}[];pagination:{total:number}}>(`/coupon-product-options?q=${encodeURIComponent(keyword.value.trim())}&page=${productPage.value}&pageSize=20`);if(seq!==sequence)return;products.value=r.items;productTotal.value=r.pagination.total;names.value=Array.from(new Map([...names.value,...products.value].map(p=>[p.id,p])).values())}catch(e){if(seq===sequence)searchError.value=e instanceof Error?e.message:'商品查询失败。'}finally{if(seq===sequence)searching.value=false}}
function toggle(p:{id:string;name:string}){const ids=form.value.productIds;update('productIds',ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}
watch(()=>`${props.account.accountId}:${props.account.permissionCodes.join(',')}`,()=>{sequence++;keyword.value='';products.value=[];searchError.value='';searching.value=false})
onUnmounted(()=>sequence++)
</script>
<template><fieldset class="coupon-fields" :disabled="disabled"><section class="panel"><h2>优惠规则</h2><div class="coupon-form-grid"><label>活动编码<el-input :model-value="form.code" @update:model-value="update('code',$event)" maxlength="64" placeholder="例如 SPRING_2026" :disabled="disabled"/></label><label>活动名称<el-input :model-value="form.title" @update:model-value="update('title',$event)" maxlength="100" :disabled="disabled"/></label><label>优惠类型<el-select :model-value="form.kind" @update:model-value="update('kind',$event)" :disabled="disabled"><el-option value="FULL_REDUCTION" label="满减券"/><el-option value="CASH" label="现金券"/></el-select></label><label v-if="form.kind==='FULL_REDUCTION'">商品金额门槛（元）<el-input :model-value="form.minimum" @update:model-value="update('minimum',$event)" inputmode="decimal" :disabled="disabled"/></label><label>优惠金额（元）<el-input :model-value="form.discount" @update:model-value="update('discount',$event)" inputmode="decimal" :disabled="disabled"/></label></div><p class="coupon-note">优惠金额由服务端按商品成交金额试算，不抵扣运费。</p><el-checkbox :model-value="form.redeemEligible" @update:model-value="update('redeemEligible',$event)" :disabled="disabled">允许用于核销商品</el-checkbox></section>
<section class="panel"><h2>适用商品</h2><p class="coupon-note">未选择商品代表全场；最多指定 100 个商品。发布后范围固定。</p><div v-if="account.permissionCodes.includes('coupon.manage')" class="coupon-filters"><label>搜索商品<el-input v-model="keyword" maxlength="100" :disabled="disabled" @keyup.enter.prevent="search" placeholder="商品名称或编码"/></label><el-button :loading="searching" :disabled="disabled" @click="search">查询商品</el-button></div><p v-else class="notice">指定商品需要优惠券管理权限。当前已有范围可保留。</p><p v-if="searchError" class="error" role="alert">{{searchError}}</p><p v-if="!searching&&keyword&&products.length===0&&!searchError" class="coupon-note">没有匹配商品，请调整查询。</p><div class="coupon-selection"><el-checkbox v-for="p in products" :key="p.id" :model-value="form.productIds.includes(p.id)" :disabled="disabled||(!form.productIds.includes(p.id)&&form.productIds.length>=100)" @change="toggle(p)">{{p.name}}</el-checkbox></div><div v-if="products.length" class="coupon-actions"><el-button :disabled="disabled||searching||productPage<=1" @click="productPage--;search(false)">上一页商品</el-button><span>第 {{productPage}} 页 · {{productTotal}} 个商品</span><el-button :disabled="disabled||searching||productPage*20>=productTotal" @click="productPage++;search(false)">下一页商品</el-button></div><div class="coupon-selection"><el-tag v-for="id in form.productIds" :key="id" :closable="!disabled" @close="update('productIds',form.productIds.filter(x=>x!==id))">{{names.find(p=>p.id===id)?.name||id}}</el-tag></div></section>
<section class="panel"><h2>期限与发放</h2><div class="coupon-form-grid"><label>开始时间<el-input :model-value="form.validFrom" @update:model-value="update('validFrom',$event)" type="datetime-local" :disabled="disabled"/></label><label>截止时间<el-input :model-value="form.validUntil" @update:model-value="update('validUntil',$event)" type="datetime-local" :disabled="disabled"/></label><label>总数量<el-input :model-value="form.totalQuantity" @update:model-value="update('totalQuantity',$event)" inputmode="numeric" :disabled="disabled"/></label><label>每人主动领取上限<el-input :model-value="form.selfClaimLimit" @update:model-value="update('selfClaimLimit',$event)" inputmode="numeric" :disabled="disabled"/></label><label>领取方式<el-select :model-value="form.claimMode" @update:model-value="update('claimMode',$event)" :disabled="disabled"><el-option value="SELF" label="用户主动领取"/><el-option value="ADMIN" label="后台发放"/><el-option value="BOTH" label="领取与后台发放"/></el-select></label></div><el-checkbox :model-value="form.issuanceEnabled" @update:model-value="update('issuanceEnabled',$event)" :disabled="disabled">发布后允许新增领取及发放</el-checkbox><p class="coupon-note">后台发放占总量，不计入主动领取上限。暂停发放不会影响已发出的券。</p></section><p v-if="validation" class="notice error" role="status">{{validation}}</p></fieldset></template>
