<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue'
import {api,type Account} from '../../api'
import {type Campaign,type Issuance,type Page,date} from './types'
import {issueError} from './form.mjs'
import {useCouponOperation} from './operation'
const props=defineProps<{campaign:Campaign;account:Account;disabled:boolean}>(),emit=defineEmits<{changed:[];busy:[boolean]}>()
const data=ref<Page<Issuance>|null>(null),loading=ref(false),readError=ref(''),page=ref(1),search=ref(''),members=ref<{id:string;enabled:boolean}[]>([]),memberId=ref(''),memberLoading=ref(false),memberError=ref(''),quantity=ref('1'),reason=ref(''),showForm=ref(false)
const canIssue=computed(()=>props.account.permissionCodes.includes('coupon.issue')&&props.account.permissionCodes.includes('member.read')),canRepeat=computed(()=>props.account.permissionCodes.includes('coupon.issue.repeat'))
const available=computed(()=>props.campaign.status==='PUBLISHED'&&props.campaign.issuanceEnabled&&props.campaign.claimMode!=='SELF'&&props.campaign.remainingQuantity>0&&Date.parse(props.campaign.validFrom)<=Date.now()&&Date.parse(props.campaign.validUntil)>Date.now())
const validation=computed(()=>issueError(memberId.value,quantity.value,reason.value,canRepeat.value))
const {pending,busy,error,notice,password,storageError,verified,recover,write}=useCouponOperation(()=>props.account,()=>`${props.campaign.id}:issue`,async()=>{showForm.value=false;memberId.value='';quantity.value='1';reason.value='';await load();emit('changed')},()=>showForm.value&&!!(memberId.value||reason.value))
watch(busy,v=>emit('busy',v))
let seq=0,memberSeq=0
async function load(){const n=++seq;loading.value=true;readError.value='';data.value=null;try{const r=await api<Page<Issuance>>(`/coupon-campaigns/${props.campaign.id}/issuances?page=${page.value}&pageSize=20`);if(n===seq)data.value=r}catch(e){if(n===seq)readError.value=e instanceof Error?e.message:'发放记录读取失败。'}finally{if(n===seq)loading.value=false}}
async function findMember(){if(!canIssue.value||busy.value)return;const n=++memberSeq;memberLoading.value=true;memberError.value='';members.value=[];memberId.value='';try{const r=await api<Page<{id:string;enabled:boolean}>>(`/members?search=${encodeURIComponent(search.value.trim())}&enabled=true&page=1&pageSize=20`);if(n===memberSeq)members.value=r.items}catch(e){if(n===memberSeq)memberError.value=e instanceof Error?e.message:'会员查询失败。'}finally{if(n===memberSeq)memberLoading.value=false}}
async function issue(){if(!props.disabled&&canIssue.value&&available.value&&!validation.value)await write(`/coupon-campaigns/${props.campaign.id}/issuances`,'POST',{expectedRevision:props.campaign.revision,memberId:memberId.value,quantity:Number(quantity.value),reason:reason.value.trim()},'coupon.issue','coupon.issue')}
async function retry(){if(!pending.value||!canIssue.value)return;const p=pending.value;await write(p.path,p.method,p.body,p.action,'coupon.issue')}
onMounted(load);onUnmounted(()=>{seq++;memberSeq++;emit('busy',false)});watch(()=>`${props.account.accountId}:${props.account.permissionCodes.join(',')}:${props.campaign.id}`,()=>{seq++;memberSeq++;showForm.value=false;search.value='';members.value=[];memberId.value='';reason.value='';quantity.value='1';void load()})
</script>
<template><section class="panel" style="margin-top:24px"><div class="panel-heading"><div><h2>领取与发放记录</h2><p class="coupon-note">后台发放占总量，不占主动领取限额。重复发放需额外权限及原因。</p></div><el-button v-if="canIssue&&campaign.status!=='LEGACY'" :disabled="disabled||busy||!available||!!pending||!!storageError" @click="showForm=!showForm;password=''">向会员发券</el-button></div><p v-if="!canIssue&&campaign.status==='PUBLISHED'" class="coupon-note">发券需要发券权限和会员读取权限。</p><p v-if="canIssue&&!available&&campaign.status==='PUBLISHED'" class="coupon-note">活动未生效、已结束、暂停、仅允许主动领取或余量不足，当前不可发券。</p><p v-if="error||storageError" role="alert" class="notice error">{{error||storageError}}</p><p v-if="notice" role="status" class="notice">{{notice}}</p><div v-if="pending" class="notice"><p>发券结果待确认，原请求已保留。先读取结果，再重试。</p><el-button :loading="busy" @click="recover">读取发券结果</el-button><template v-if="verified"><label>当前账号密码<el-input v-model="password" type="password" autocomplete="current-password"/></label><el-button :disabled="busy||!password||disabled||!canIssue" @click="retry">原请求重试</el-button></template></div>
<form v-if="showForm&&!pending" class="coupon-confirm" @submit.prevent="issue"><h2>发放给会员</h2><div class="coupon-filters"><label>会员编号<el-input v-model="search" maxlength="64" :disabled="busy||disabled" placeholder="输入编号或片段" @keyup.enter.prevent="findMember"/></label><el-button :loading="memberLoading" :disabled="busy||disabled" @click="findMember">查询会员</el-button></div><p v-if="memberError" class="error" role="alert">{{memberError}}</p><p v-if="members.length===0&&search&&!memberLoading&&!memberError" class="coupon-note">最多显示 20 位，请缩小查询范围。</p><div class="coupon-form-grid"><label>选择会员<el-select v-model="memberId" :disabled="busy||disabled"><el-option v-for="m in members" :key="m.id" :value="m.id" :label="`会员 ${m.id}`" :disabled="!m.enabled"/></el-select></label><label>发放数量<el-input v-model="quantity" inputmode="numeric" :disabled="busy||disabled"/></label><label>发放原因<el-input v-model="reason" type="textarea" maxlength="200" :disabled="busy||disabled" placeholder="重复发放必须填写；由服务端核验是否重复"/></label><label>当前账号密码（二次确认）<el-input v-model="password" type="password" autocomplete="current-password" :disabled="busy||disabled"/></label></div><p v-if="validation" class="error" role="status">{{validation}}</p><div class="coupon-actions"><el-button type="primary" native-type="submit" :loading="busy" :disabled="disabled||!!validation||!password||!!storageError">确认发放</el-button><el-button :disabled="busy" @click="showForm=false;password=''">取消</el-button></div></form>
<p v-if="loading" role="status">正在读取记录…</p><div v-else-if="readError" class="notice error" role="alert">{{readError}} <el-button @click="load">重新读取</el-button></div><template v-else-if="data"><div class="table-scroll"><table class="data-table"><thead><tr><th>会员</th><th>来源</th><th>数量</th><th>操作人</th><th>原因</th><th>时间</th></tr></thead><tbody><tr v-for="i in data.items" :key="i.id"><td><RouterLink v-if="account.permissionCodes.includes('member.read')" :to="`/members/${i.memberId}`" class="text-link">{{i.memberLabel}}</RouterLink><span v-else>{{i.memberLabel}}</span></td><td>{{i.kind==='SELF'?'用户领取':'后台发放'}}</td><td>{{i.quantity}}</td><td>{{i.actorLabel||'会员本人'}}</td><td>{{i.reason||'—'}}</td><td>{{date(i.createdAt)}}</td></tr><tr v-if="!data.items.length"><td colspan="6" class="empty-state">暂无领取或发放记录。</td></tr></tbody></table></div><div class="pagination"><span>共 {{data.pagination.total}} 条 · 第 {{page}} 页</span><el-button :disabled="loading||page<=1||busy" @click="page--;load()">上一页</el-button><el-button :disabled="loading||page*20>=data.pagination.total||busy" @click="page++;load()">下一页</el-button></div></template></section></template>
