<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue'
import {api,type Account} from '../api'
import {type Campaign,type Page,money,date,status,mode} from './coupons/types'
import './coupons/coupons.css'
const props=defineProps<{account:Account}>(),data=ref<Page<Campaign>|null>(null),loading=ref(false),error=ref(''),q=ref(''),filter=ref(''),page=ref(1)
let sequence=0
async function load(reset=false){if(reset)page.value=1;const seq=++sequence;loading.value=true;error.value='';data.value=null;try{const query=new URLSearchParams({q:q.value.trim(),status:filter.value,page:String(page.value),pageSize:'20'});const r=await api<Page<Campaign>>(`/coupon-campaigns?${query}`);if(seq===sequence)data.value=r}catch(e){if(seq===sequence)error.value=e instanceof Error?e.message:'活动读取失败。'}finally{if(seq===sequence)loading.value=false}}
onMounted(()=>load());onUnmounted(()=>sequence++);watch(()=>`${props.account.accountId}:${props.account.permissionCodes.join(',')}`,()=>{q.value='';filter.value='';void load(true)})
</script>
<template><section class="page-content coupon-page"><header class="page-heading"><div><h1>优惠券活动</h1><p>设置券规则、查看发放进度；发布后金额、期限和适用范围固定。</p></div><RouterLink v-if="account.permissionCodes.includes('coupon.manage')" to="/coupons/new" class="primary-button">创建活动</RouterLink></header>
<form class="coupon-filters" @submit.prevent="load(true)"><label>活动名称或编码<el-input v-model="q" maxlength="100" clearable placeholder="查询优惠券活动"/></label><label>活动状态<el-select v-model="filter"><el-option label="全部状态" value=""/><el-option label="草稿" value="DRAFT"/><el-option label="已发布" value="PUBLISHED"/><el-option label="历史活动" value="LEGACY"/></el-select></label><el-button native-type="submit" :loading="loading">查询</el-button></form>
<p v-if="loading" role="status">正在读取活动…</p><div v-else-if="error" class="notice error" role="alert">{{error}} <el-button @click="load()">重新读取</el-button></div><template v-else-if="data"><div class="panel table-scroll"><table class="data-table"><thead><tr><th>活动</th><th>优惠规则</th><th>有效期</th><th>发放进度</th><th>领取方式</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="c in data.items" :key="c.id"><td><strong>{{c.title}}</strong><small>{{c.code}}</small></td><td>{{c.kind==='CASH'?'现金券':`满 ${money(c.minGoodsFen)}`}} 减 {{money(c.discountFen)}}<small>{{c.productIds.length?`指定 ${c.productIds.length} 个商品`:'全场商品'}} · {{c.redeemEligible?'可用于核销商品':'不用于核销商品'}}</small></td><td>{{date(c.validFrom)}}<small>至 {{date(c.validUntil)}}</small></td><td><span v-if="c.status==='LEGACY'">历史发放额度未登记</span><template v-else>{{c.issuedQuantity}} / {{c.totalQuantity}}<small>剩余 {{c.remainingQuantity}}</small></template></td><td>{{mode(c.claimMode)}}</td><td><span class="badge">{{status(c.status)}}</span><small v-if="c.status==='PUBLISHED'">{{c.issuanceEnabled?'发放开启':'已暂停新增'}}</small></td><td><RouterLink :to="`/coupons/${c.id}`" class="text-link">查看活动</RouterLink></td></tr><tr v-if="!data.items.length"><td colspan="7" class="empty-state">暂无匹配活动。可调整筛选条件。</td></tr></tbody></table></div><div class="pagination"><span>共 {{data.pagination.total}} 个活动 · 第 {{page}} 页</span><el-button :disabled="page<=1" @click="page--;load()">上一页</el-button><el-button :disabled="page*20>=data.pagination.total" @click="page++;load()">下一页</el-button></div></template></section></template>
