<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,type Account} from '../api'
import { confirmAction as confirmDiscard } from '../shared/confirm'
import CouponRulePreview from './coupons/CouponRulePreview.vue'
import CampaignEditor from './coupons/CampaignEditor.vue'
import CouponIssuancePanel from './coupons/CouponIssuancePanel.vue'
import {campaignBody,campaignError,type CampaignForm} from './coupons/form.mjs'
import {useCouponOperation} from './coupons/operation'
import {type Campaign,money,date,mode} from './coupons/types'
import { campaignLifecycle } from './coupons/lifecycle.mjs'
import { useCampaignClock } from './coupons/clock'
const now = useCampaignClock()
import './coupons/coupons.css'
const props=defineProps<{account:Account}>(),route=useRoute(),router=useRouter(),campaign=ref<Campaign|null>(null),loading=ref(false),loadError=ref(''),saved=ref(''),confirm=ref(''),issueBusy=ref(false)
const target=computed(()=>String(route.params.campaignId||'new')),isNew=computed(()=>target.value==='new')
const empty=():CampaignForm=>({code:'',title:'',kind:'FULL_REDUCTION',minimum:'100',discount:'10',productIds:[],redeemEligible:false,validFrom:'',validUntil:'',totalQuantity:'100',selfClaimLimit:'1',claimMode:'BOTH',issuanceEnabled:true})
const form=ref<CampaignForm>(empty())
const dirty=computed(()=>saved.value!==JSON.stringify(form.value)),canManage=computed(()=>props.account.permissionCodes.includes('coupon.manage')),canPublish=computed(()=>props.account.permissionCodes.includes('coupon.publish'))
const {pending,busy,error,notice,password,storageError,verified,recover,write}=useCouponOperation(()=>props.account,()=>target.value,async result=>{confirm.value='';const r=result as Campaign;if(r?.id){campaign.value=r;assign(r);if(isNew.value){saved.value=JSON.stringify(form.value);await router.replace(`/coupons/${r.id}`)}}else await load(false)},()=>dirty.value)
let sequence=0
const local=(v:string)=>{const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function assign(c:Campaign){form.value={code:c.code,title:c.title,kind:c.kind,minimum:(c.minGoodsFen/100).toFixed(2),discount:(c.discountFen/100).toFixed(2),productIds:[...c.productIds],redeemEligible:c.redeemEligible,validFrom:local(c.validFrom),validUntil:local(c.validUntil),totalQuantity:String(c.totalQuantity),selfClaimLimit:String(c.selfClaimLimit),claimMode:c.claimMode,issuanceEnabled:c.issuanceEnabled};saved.value=JSON.stringify(form.value)}
async function load(ask=true){if(busy.value||issueBusy.value)return;if(ask&&dirty.value&&!pending.value){const originalTarget=target.value,originalAccount=props.account.accountId,originalForm=JSON.stringify(form.value);if(!await confirmDiscard('刷新将放弃未保存修改，是否继续？'))return;if(busy.value||issueBusy.value||pending.value||originalTarget!==target.value||originalAccount!==props.account.accountId||originalForm!==JSON.stringify(form.value))return;}const seq=++sequence;loadError.value='';loading.value=true;campaign.value=null;try{if(isNew.value){form.value=empty();saved.value=JSON.stringify(form.value);return}const r=await api<Campaign>(`/coupon-campaigns/${target.value}`);if(seq===sequence)assign(campaign.value=r)}catch(e){if(seq===sequence)loadError.value=e instanceof Error?e.message:'活动读取失败。'}finally{if(seq===sequence)loading.value=false}}
function begin(action:string){if(busy.value||issueBusy.value||pending.value||storageError.value)return;password.value='';confirm.value=action}
async function save(){if(!pending.value&&campaignError(form.value))return;await write(`/coupon-campaigns${isNew.value?'':`/${target.value}`}`,isNew.value?'POST':'PUT',campaignBody(form.value,isNew.value?undefined:campaign.value?.revision))}
async function confirmAction(){if(!campaign.value)return;const c=campaign.value;await write(`/coupon-campaigns/${c.id}/${confirm.value}`, 'POST',confirm.value==='publish'?{expectedRevision:c.revision}:{expectedRevision:c.revision,issuanceEnabled:!c.issuanceEnabled},'coupon.publish','coupon.publish')}
async function retry(){if(!pending.value)return;const p=pending.value;await write(p.path,p.method,p.body,p.action,p.action==='coupon.publish'?'coupon.publish':'coupon.manage')}
onMounted(()=>load(false));onUnmounted(()=>sequence++);watch(()=>`${target.value}:${props.account.accountId}:${props.account.permissionCodes.join(',')}`,()=>{sequence++;confirm.value='';password.value='';form.value=empty();saved.value=JSON.stringify(form.value);void load(false)})
</script>
<template><section class="page-content coupon-page"><header class="page-heading"><div><RouterLink to="/coupons" class="text-link">返回活动列表</RouterLink><h1>{{isNew?'创建优惠券活动':campaign?.title||'优惠券活动'}}</h1><p>发布前保存草稿；发布后保留券面规则，暂停只停止新增领取及发券。</p></div><el-button :disabled="busy||issueBusy||loading" @click="load()">刷新活动</el-button></header>
<p v-if="loading" role="status">正在读取活动…</p><div v-if="loadError" class="notice error" role="alert">{{loadError}} <el-button @click="load(false)">重新读取</el-button></div><p v-if="error||storageError" class="notice error" role="alert">{{error||storageError}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
<section v-if="pending" class="panel"><h2>操作结果待确认</h2><p>已锁定原请求。读取其最终结果后，可继续使用原请求身份重试。</p><el-button :loading="busy" @click="recover">读取操作结果</el-button><template v-if="verified"><label v-if="pending.action">当前账号密码<el-input v-model="password" type="password" autocomplete="current-password"/></label><el-button :disabled="busy||!!storageError" @click="retry">原请求重试</el-button></template></section>
<template v-if="!loading&&!loadError&&(isNew||campaign)"><form v-if="isNew||campaign?.status==='DRAFT'" @submit.prevent="save"><CampaignEditor v-model="form" :account="account" :disabled="busy||!!pending||!canManage" :product-names="campaign?.productNames||[]"/><div class="coupon-actions"><el-button v-if="canManage" native-type="submit" type="primary" :loading="busy" :disabled="!!pending||!!storageError||!!campaignError(form)||!dirty">{{isNew?'保存草稿':'保存修改'}}</el-button><el-button v-if="campaign&&canPublish" :disabled="busy||issueBusy||!!pending||dirty||!!storageError" @click="begin('publish')">发布活动</el-button><span v-if="!canManage" class="coupon-note">当前账号只可查看活动。</span><span v-if="campaign&&dirty" class="coupon-note">先保存修改，再发布。</span></div></form>
<div v-else-if="campaign" class="coupon-layout"><section class="panel"><h2>券面规则</h2><p class="coupon-note">{{campaign.status==='LEGACY'?'历史活动仅供查看，不能修改券面规则。':campaignLifecycle(campaign,now).label==='已结束'?'活动已结束，券面规则保留，不再新增领取与发放。':'活动已发布，优惠金额、有效期、总数量和商品范围固定，仅可暂停或恢复新增发放。'}}</p><CouponRulePreview :title="campaign.title" :kind="campaign.kind" :minimum="String(campaign.minGoodsFen/100)" :discount="String(campaign.discountFen/100)" :product-count="campaign.productIds.length"/><dl class="coupon-summary"><dt>活动状态</dt><dd>{{campaignLifecycle(campaign,now).label}} · 修订 {{campaign.revision}}</dd><dt>活动编码</dt><dd>{{campaign.code}}</dd><dt>优惠金额</dt><dd>{{campaign.kind==='CASH'?`现金券 ${money(campaign.discountFen)}`:`满 ${money(campaign.minGoodsFen)} 减 ${money(campaign.discountFen)}`}}</dd><dt>适用商品</dt><dd>{{campaign.productNames.length?campaign.productNames.map(p=>p.name).join('、'):'全场商品'}}<small>{{campaign.redeemEligible?'允许用于核销商品':'不用于核销商品'}}</small></dd><dt>有效期</dt><dd>{{date(campaign.validFrom)}} 至 {{date(campaign.validUntil)}}</dd><dt>领取方式</dt><dd>{{mode(campaign.claimMode)}} · 主动领取每人 {{campaign.selfClaimLimit}} 张</dd></dl></section><section class="panel"><h2>发放进度</h2><p v-if="campaign.status==='LEGACY'">历史发放额度未登记</p><template v-else><p>已发 <strong>{{campaign.issuedQuantity}}</strong> / {{campaign.totalQuantity}}，剩余 {{campaign.remainingQuantity}} 张</p><progress v-if="campaign.totalQuantity>0" :value="campaign.issuedQuantity" :max="campaign.totalQuantity" aria-label="活动发放进度"/><p>{{campaignLifecycle(campaign,now).reason || (campaign.claimMode==='SELF'?'允许用户主动领取；不支持后台发券':campaign.claimMode==='ADMIN'?'允许后台发放；不支持用户主动领取':'允许新增领取与发放')}}</p></template><p class="coupon-note">已发券保持原有规则，暂停不撤回用户已有权益。</p><el-button v-if="campaign.status==='PUBLISHED'&&canPublish" :disabled="busy||issueBusy||!!pending||!!storageError||campaignLifecycle(campaign,now).label==='已结束'" @click="begin('distribution')">{{campaign.issuanceEnabled?'暂停新增发放':'恢复新增发放'}}</el-button><p v-if="campaign.status==='LEGACY'" class="coupon-note">历史活动仅可查看，不提供发布或发放操作。</p></section></div>
<section v-if="confirm" class="panel coupon-confirm"><h2>{{confirm==='publish'?'确认发布活动':campaign?.issuanceEnabled?'确认暂停新增发放':'确认恢复新增发放'}}</h2><p>{{confirm==='publish'?'发布后金额、期限、数量及商品范围固定。请核对券面规则。':'操作只改变新增领取和发放，已有券不变。'}}</p><label>当前账号密码（二次确认）<el-input v-model="password" type="password" autocomplete="current-password" :disabled="busy"/></label><div class="coupon-actions"><el-button type="primary" :loading="busy" :disabled="!password" @click="confirmAction">确认操作</el-button><el-button :disabled="busy" @click="confirm='';password=''">取消</el-button></div></section>
<CouponIssuancePanel v-if="campaign" :campaign="campaign" :account="account" :disabled="busy||!!pending||!!confirm||dirty" @changed="load(false)" @busy="issueBusy=$event"/></template></section></template>
