<script setup lang="ts">
import {ref,onMounted,onUnmounted,watch} from 'vue'
import {api,type Account} from '../api'
import {type Offer,type Page,offerStatus,specs} from './exchange/types'
import './exchange/exchange.css'
const props=defineProps<{account:Account}>(),data=ref<Page<Offer>|null>(null),loading=ref(false),error=ref(''),q=ref(''),status=ref(''),page=ref(1)
let generation=0
async function load(reset=false){if(reset)page.value=1;const seq=++generation;loading.value=true;error.value='';data.value=null;try{const params=new URLSearchParams({q:q.value.trim(),status:status.value,page:String(page.value),pageSize:'20'});const r=await api<Page<Offer>>(`/exchange-offers?${params}`);if(seq===generation)data.value=r}catch(e){if(seq===generation)error.value=e instanceof Error?e.message:'兑换商品读取失败。'}finally{if(seq===generation)loading.value=false}}
onMounted(()=>load());onUnmounted(()=>generation++);watch(()=>`${props.account.accountId}:${props.account.permissionCodes.join(',')}`,()=>{q.value='';status.value='';void load(true)})
</script>
<template><section class="page-content exchange-page"><header class="page-heading"><div><h1>积分商城商品</h1><p>复用现有 SKU 与库存，设置独立兑换积分；配送包含在积分售价中。</p></div><RouterLink v-if="account.permissionCodes.includes('exchange.manage')" to="/exchange-offers/new" class="primary-button">添加兑换商品</RouterLink></header><form class="exchange-filters" @submit.prevent="load(true)"><label>商品名称或 SKU 编码<el-input v-model="q" maxlength="100" clearable/></label><label>兑换状态<el-select v-model="status"><el-option value="" label="全部状态"/><el-option value="DRAFT" label="草稿"/><el-option value="ON_SALE" label="兑换开启"/><el-option value="OFF_SALE" label="兑换暂停"/></el-select></label><el-button native-type="submit" :loading="loading">查询</el-button></form><p v-if="loading" role="status">正在读取兑换商品…</p><div v-else-if="error" class="notice error" role="alert">{{error}} <el-button @click="load()">重新读取</el-button></div><template v-else-if="data"><div class="panel table-wrap" tabindex="0" aria-label="积分商城商品，可横向滚动"><table><thead><tr><th>商品 / SKU</th><th>兑换积分</th><th>履约方式</th><th>可兑数量</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="offer in data.items" :key="offer.id"><td><div class="exchange-product"><img v-if="offer.imageUrl" :src="offer.imageUrl" alt="" @error="($event.target as HTMLImageElement).hidden=true"/><div><strong>{{offer.productName}}</strong><small>{{offer.skuCode}} · {{specs(offer.specs)}}</small></div></div></td><td class="exchange-points">{{offer.pointsPrice}} 积分 / {{offer.saleUnit}}</td><td>{{offer.fulfillmentKind==='SHIP'?'快递 · 配送已含':'到店核销'}}<small v-if="offer.fulfillmentKind==='REDEEM'">有效至 {{offer.redeemValidUntil||'未设置'}}</small></td><td>{{offer.availableQuantity??'待核查'}} {{offer.saleUnit}}</td><td><span class="badge">{{offerStatus(offer.status)}}</span></td><td><RouterLink :to="`/exchange-offers/${offer.id}`" class="text-link">查看配置</RouterLink></td></tr><tr v-if="!data.items.length"><td colspan="6" class="empty-state">没有匹配的兑换商品，可调整筛选条件。</td></tr></tbody></table></div><div class="exchange-pagination"><span>共 {{data.pagination.total}} 个 · 第 {{page}} 页</span><el-button :disabled="page<=1" @click="page--;load()">上一页</el-button><el-button :disabled="page*20>=data.pagination.total" @click="page++;load()">下一页</el-button></div></template></section></template>
