<script setup lang="ts">
import { confirmAction } from '../shared/confirm'

import {computed,onMounted,onUnmounted,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {api,type Account} from '../api'
import {type Offer,type ExchangeSku,type Page,specs,offerStatus} from './exchange/types'
import {offerError,offerBody} from './exchange/form.mjs'
import {useExchangeOperation} from './exchange/operation'
import './exchange/exchange.css'
const props=defineProps<{account:Account}>(),route=useRoute(),router=useRouter(),offer=ref<Offer|null>(null),loading=ref(false),loadError=ref(''),skuId=ref(''),price=ref(''),saved=ref(''),confirm=ref(false)
const query=ref(''),skus=ref<Page<ExchangeSku>|null>(null),skuPage=ref(1),skuLoading=ref(false),skuError=ref('')
const target=computed(()=>String(route.params.offerId||'new')),isNew=computed(()=>target.value==='new'),canManage=computed(()=>props.account.permissionCodes.includes('exchange.manage')),canPublish=computed(()=>props.account.permissionCodes.includes('exchange.publish'))
const dirty=computed(()=>saved.value!==JSON.stringify([skuId.value,price.value])),selected=computed(()=>skus.value?.items.find(s=>s.id===skuId.value)),validation=computed(()=>offerError(skuId.value,price.value))
const {pending,busy,error,notice,password,storageError,verified,recover,write}=useExchangeOperation(()=>props.account,()=>target.value,async result=>{const r=result as Offer;confirm.value=false;offer.value=r;assign(r);if(isNew.value)await router.replace(`/exchange-offers/${r.id}`)},()=>dirty.value)
let generation=0,skuGeneration=0
function assign(r:Offer){skuId.value=r.skuId;price.value=String(r.pointsPrice);saved.value=JSON.stringify([skuId.value,price.value])}
async function load(ask=true){if(busy.value)return;if(ask&&dirty.value&&!pending.value&&!await confirmAction('刷新将放弃未保存修改，是否继续？'))return;const seq=++generation;loading.value=true;loadError.value='';offer.value=null;try{if(isNew.value){skuId.value='';price.value='';saved.value=JSON.stringify(['','']);return}const r=await api<Offer>(`/exchange-offers/${target.value}`);if(seq===generation)assign(offer.value=r)}catch(e){if(seq===generation)loadError.value=e instanceof Error?e.message:'兑换配置读取失败。'}finally{if(seq===generation)loading.value=false}}
async function search(reset=true){if(busy.value||pending.value||!canManage.value)return;if(reset)skuPage.value=1;const seq=++skuGeneration;skuLoading.value=true;skuError.value='';try{const r=await api<Page<ExchangeSku>>(`/exchange-sku-options?q=${encodeURIComponent(query.value.trim())}&page=${skuPage.value}&pageSize=20`);if(seq===skuGeneration)skus.value=r}catch(e){if(seq===skuGeneration){skus.value=null;skuError.value=e instanceof Error?e.message:'SKU 查询失败。'}}finally{if(seq===skuGeneration)skuLoading.value=false}}
async function save(){if(validation.value||(!isNew.value&&!offer.value))return;await write(`/exchange-offers${isNew.value?'':`/${target.value}`}`,isNew.value?'POST':'PUT',offerBody(skuId.value,price.value,isNew.value?undefined:offer.value?.revision))}
async function availability(){if(!offer.value)return;await write(`/exchange-offers/${target.value}/availability`,'POST',{expectedRevision:offer.value.revision,status:offer.value.status==='ON_SALE'?'OFF_SALE':'ON_SALE'},'exchange.publish','exchange.publish')}
async function retry(){if(!pending.value)return;const p=pending.value;await write(p.path,p.method,p.body,p.action,p.action?'exchange.publish':'exchange.manage')}
onMounted(()=>load(false));onUnmounted(()=>{generation++;skuGeneration++});watch(()=>`${target.value}:${props.account.accountId}:${props.account.permissionCodes.join(',')}`,()=>{generation++;skuGeneration++;confirm.value=false;skus.value=null;query.value='';skuError.value='';skuLoading.value=false;skuId.value='';price.value='';saved.value=JSON.stringify(['','']);void load(false)})
</script>
<template><section class="page-content exchange-page"><header class="page-heading"><div><RouterLink to="/exchange-offers" class="text-link">返回积分商城商品</RouterLink><h1>{{isNew?'添加兑换商品':offer?.productName||'兑换商品配置'}}</h1><p>积分售价独立配置，商品信息和库存沿用 SKU。已成交兑换保留原积分快照。</p></div><el-button :disabled="busy||loading" @click="load()">刷新配置</el-button></header><p v-if="loading" role="status">正在读取配置…</p><div v-if="loadError" class="notice error" role="alert">{{loadError}} <el-button @click="load(false)">重新读取</el-button></div><p v-if="storageError||error" class="notice error" role="alert">{{storageError||error}}</p><p v-if="notice" class="notice" role="status">{{notice}}</p>
<section v-if="pending" class="panel"><h2>操作结果待确认</h2><p>原请求内容和身份已固定，请先查询最终结果。</p><el-button :loading="busy" @click="recover">读取操作结果</el-button><template v-if="verified"><label v-if="pending.action">当前账号密码<el-input v-model="password" type="password" autocomplete="current-password"/></label><el-button :disabled="busy||!!storageError||(!!pending.action&&!password)" @click="retry">原请求重试</el-button></template></section>
<template v-if="!loading&&!loadError&&(isNew||offer)"><section v-if="isNew" class="panel"><h2>选择现有 SKU</h2><p>同一 SKU 可关联一个兑换配置。库存与普通商品渠道共享。</p><form class="exchange-filters" @submit.prevent="search()"><label>商品名称或 SKU 编码<el-input v-model="query" maxlength="100" :disabled="busy||!!pending||!canManage"/></label><el-button native-type="submit" :loading="skuLoading" :disabled="busy||!!pending||!canManage">查询 SKU</el-button></form><p v-if="skuError" class="error" role="alert">{{skuError}} <el-button @click="search(false)">重试</el-button></p><p v-if="skuLoading" role="status">正在查询 SKU…</p><div v-if="skus&&!skuLoading" class="table-wrap" tabindex="0" aria-label="可选 SKU 列表"><table><thead><tr><th>选择</th><th>商品 / SKU</th><th>履约</th><th>当前资格</th></tr></thead><tbody><tr v-for="s in skus.items" :key="s.id"><td><input type="radio" name="exchange-sku" :value="s.id" v-model="skuId" :aria-label="`选择${s.productName} ${s.skuCode}`" :disabled="busy||!!pending||!canManage||!!s.existingOfferId"/></td><td>{{s.productName}}<small>{{s.skuCode}} · {{specs(s.specs)}}</small></td><td>{{s.fulfillmentKind==='SHIP'?'快递 · 配送已含':'到店核销'}}<small v-if="s.fulfillmentKind==='REDEEM'">有效至 {{s.redeemValidUntil||'未设置'}}</small></td><td><RouterLink v-if="s.existingOfferId" :to="`/exchange-offers/${s.existingOfferId}`" class="text-link">已有兑换配置</RouterLink><span v-else>{{s.catalogOnSale?'SKU 可售':'SKU 未满足可售条件'}}</span></td></tr><tr v-if="!skus.items.length"><td colspan="4" class="empty-state">没有匹配的 SKU，请调整查询。</td></tr></tbody></table></div><div v-if="skus" class="exchange-pagination"><span>第 {{skuPage}} 页 · {{skus.pagination.total}} 个</span><el-button :disabled="skuLoading||busy||!!pending||skuPage<=1" @click="skuPage--;search(false)">上一页</el-button><el-button :disabled="skuLoading||busy||!!pending||skuPage*20>=skus.pagination.total" @click="skuPage++;search(false)">下一页</el-button></div><p v-if="selected" class="notice">已选择 {{selected.productName}} · {{selected.skuCode}}</p></section>
<section v-else-if="offer" class="panel"><h2>商品与兑换资格</h2><dl class="exchange-facts"><dt>商品 / SKU</dt><dd>{{offer.productName}} · {{offer.skuCode}}<small>{{specs(offer.specs)}}</small></dd><dt>履约方式</dt><dd>{{offer.fulfillmentKind==='SHIP'?'快递 · 配送已含':'到店核销'}}<small v-if="offer.fulfillmentKind==='REDEEM'">核销截止 {{offer.redeemValidUntil||'未设置'}}</small></dd><dt>兑换状态</dt><dd>{{offerStatus(offer.status)}} · 修订 {{offer.revision}}</dd><dt>可兑数量</dt><dd>{{offer.availableQuantity??'待核查'}} {{offer.saleUnit}}</dd></dl><p class="exchange-note">开启兑换仍需商品、分类、SKU 和库存满足当前资格。该配置不会单独新增库存。</p></section>
<form class="panel exchange-price-form" @submit.prevent="save"><h2>兑换积分</h2><label>每 {{offer?.saleUnit||selected?.saleUnit||'个销售单位'}} 所需积分<el-input v-model="price" inputmode="numeric" maxlength="7" :disabled="busy||!!pending||!canManage" placeholder="1 至 1000000 的整数"/></label><p class="exchange-note">纯积分兑换，无现金收款；快递配送包含在积分售价中。改价将使未提交的旧报价重新报价，历史订单不改写。</p><p v-if="validation" class="error" role="status">{{validation}}</p><div class="exchange-actions"><el-button v-if="canManage" type="primary" native-type="submit" :loading="busy" :disabled="!!pending||!!storageError||!!validation||!dirty">{{isNew?'保存兑换草稿':'保存积分售价'}}</el-button><el-button v-if="offer&&canPublish" :disabled="busy||!!pending||!!storageError||dirty" @click="confirm=true;password=''">{{offer.status==='ON_SALE'?'暂停兑换':offer.status==='DRAFT'?'发布兑换':'恢复兑换'}}</el-button><span v-if="!canManage" class="exchange-note">当前账号只能查看配置。</span><span v-if="offer&&dirty" class="exchange-note">保存售价后再操作兑换状态。</span></div></form>
<section v-if="confirm&&offer" class="panel"><h2>{{offer.status==='ON_SALE'?'确认暂停兑换':'确认开启兑换'}}</h2><p>{{offer.productName}} · {{offer.skuCode}}，每 {{offer.saleUnit}} {{offer.pointsPrice}} 积分。状态变更不改变已成交订单。</p><label>当前账号密码（二次确认）<el-input v-model="password" type="password" autocomplete="current-password" :disabled="busy"/></label><div class="exchange-actions"><el-button type="primary" :loading="busy" :disabled="!password" @click="availability">确认操作</el-button><el-button :disabled="busy" @click="confirm=false;password=''">取消</el-button></div></section></template></section></template>
