# Generated by Django 5.2.17 on 2026-09-26 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_order_payment_state_time_consistent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('WECHAT', 'WeChat'), ('OFFLINE', 'Offline')], max_length=8)),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('external_trade_no', models.CharField(max_length=128)),
                ('amount_fen', models.BigIntegerField()),
                ('paid_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('WECHAT_NOTIFICATION', 'WeChat notification'), ('WECHAT_QUERY', 'WeChat query'), ('OFFLINE_RECONCILIATION', 'Offline reconciliation')], max_length=24)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'db_table': 'payment_receipt',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WECHAT', 'WeChat'), ('OFFLINE', 'Offline')], max_length=8)),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('event_id', models.CharField(max_length=128)),
                ('evidence_digest', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'payment_event',
            },
        ),
        migrations.CreateModel(
            name='PaymentAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('UNKNOWN_ORDER', 'Unknown order'), ('METHOD_MISMATCH', 'Method mismatch'), ('AMOUNT_MISMATCH', 'Amount mismatch'), ('CLOSED_ORDER', 'Closed order'), ('ALREADY_PAID', 'Already paid'), ('SETTLEMENT_FAILED', 'Settlement failed')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=200)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly', to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'payment_anomaly',
            },
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['order_no', '-recorded_at'], name='payment_receipt_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(fields=('channel', 'merchant_account_id', 'external_trade_no'), name='payment_external_trade_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='payment_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('channel', 'merchant_account_id', 'event_id'), name='payment_event_identity_unique'),
        ),
        migrations.AddIndex(
            model_name='paymentanomaly',
            index=models.Index(fields=['status', '-created_at'], name='payment_anomaly_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentanomaly',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'OPEN')), models.Q(('resolved_at__isnull', False), ('status', 'RESOLVED')), _connector='OR'), name='payment_anomaly_status_time'),
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION payment_receipt_reject_fact_mutation() RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'payment receipt is immutable';
                END IF;
                IF ROW(NEW.order_no, NEW.channel, NEW.merchant_account_id,
                       NEW.external_trade_no, NEW.amount_fen, NEW.paid_at,
                       NEW.source, NEW.recorded_at)
                   IS DISTINCT FROM
                   ROW(OLD.order_no, OLD.channel, OLD.merchant_account_id,
                       OLD.external_trade_no, OLD.amount_fen, OLD.paid_at,
                       OLD.source, OLD.recorded_at)
                   OR (OLD.order_id IS NOT NULL AND NEW.order_id IS DISTINCT FROM OLD.order_id)
                   OR (OLD.applied_at IS NOT NULL AND NEW.applied_at IS DISTINCT FROM OLD.applied_at) THEN
                    RAISE EXCEPTION 'payment receipt fact is immutable';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER payment_receipt_fact_immutable
              BEFORE UPDATE OR DELETE ON payment_receipt
              FOR EACH ROW EXECUTE FUNCTION payment_receipt_reject_fact_mutation();
            CREATE FUNCTION payment_event_reject_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'payment event is immutable';
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER payment_event_immutable
              BEFORE UPDATE OR DELETE ON payment_event
              FOR EACH ROW EXECUTE FUNCTION payment_event_reject_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER payment_event_immutable ON payment_event;
            DROP FUNCTION payment_event_reject_mutation();
            DROP TRIGGER payment_receipt_fact_immutable ON payment_receipt;
            DROP FUNCTION payment_receipt_reject_fact_mutation();
            """,
        ),
    ]
