# Generated by Django 5.2.17 on 2026-09-26 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentanomaly',
            name='reason',
            field=models.CharField(choices=[('UNKNOWN_ORDER', 'Unknown order'), ('METHOD_MISMATCH', 'Method mismatch'), ('AMOUNT_MISMATCH', 'Amount mismatch'), ('CLOSED_ORDER', 'Closed order'), ('ALREADY_PAID', 'Already paid'), ('SETTLEMENT_FAILED', 'Settlement failed'), ('IDENTIFIER_CONFLICT', 'Identifier conflict')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAnomalyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=12)),
                ('reason', models.CharField(choices=[('UNKNOWN_ORDER', 'Unknown order'), ('METHOD_MISMATCH', 'Method mismatch'), ('AMOUNT_MISMATCH', 'Amount mismatch'), ('CLOSED_ORDER', 'Closed order'), ('ALREADY_PAID', 'Already paid'), ('SETTLEMENT_FAILED', 'Settlement failed'), ('IDENTIFIER_CONFLICT', 'Identifier conflict')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], max_length=8)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='payments.paymentanomaly')),
            ],
            options={
                'db_table': 'payment_anomaly_event',
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER payment_anomaly_event_immutable
              BEFORE UPDATE OR DELETE ON payment_anomaly_event
              FOR EACH ROW EXECUTE FUNCTION payment_event_reject_mutation();
            """,
            reverse_sql="DROP TRIGGER payment_anomaly_event_immutable ON payment_anomaly_event;",
        ),
    ]
