# Generated by Django 5.2.17 on 2026-09-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentanomaly_reason_paymentanomalyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='ready_for_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
