# Generated by Django 5.2.17 on 2026-09-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_payment_state_time_consistent'),
        ('payments', '0003_paymentreceipt_ready_for_settlement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('applied_at__isnull', False)), fields=('order',), name='payment_order_once_applied'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('applied_at__isnull', True), ('order__isnull', False), _connector='OR'), name='payment_applied_has_order'),
        ),
    ]
