# Generated by Django 5.2.17 on 2026-09-26 03:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_policy(apps, schema_editor):
    apps.get_model('payments', 'OfflinePaymentPolicy').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


IMMUTABLE = """
CREATE FUNCTION offline_reject_report_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'member payment report is immutable'; END; $$;
CREATE TRIGGER offline_report_immutable BEFORE UPDATE OR DELETE ON offline_payment_report
FOR EACH ROW EXECUTE FUNCTION offline_reject_report_mutation();
CREATE FUNCTION offline_reject_reconciliation_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'offline reconciliation is immutable'; END IF;
  IF ROW(NEW.id, NEW.order_id, NEW.actor_id, NEW.key, NEW.expected_revision, NEW.merchant_account_id,
         NEW.external_trade_no, NEW.amount_fen, NEW.paid_at, NEW.note, NEW.created_at)
     IS DISTINCT FROM
     ROW(OLD.id, OLD.order_id, OLD.actor_id, OLD.key, OLD.expected_revision, OLD.merchant_account_id,
         OLD.external_trade_no, OLD.amount_fen, OLD.paid_at, OLD.note, OLD.created_at)
     OR (OLD.authorized_at IS NOT NULL AND NEW.authorized_at IS DISTINCT FROM OLD.authorized_at)
     OR (OLD.receipt_id IS NOT NULL AND NEW.receipt_id IS DISTINCT FROM OLD.receipt_id) THEN
    RAISE EXCEPTION 'offline reconciliation evidence is immutable';
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER offline_reconciliation_immutable BEFORE UPDATE OR DELETE ON offline_reconciliation
FOR EACH ROW EXECUTE FUNCTION offline_reject_reconciliation_mutation();
"""
DROP = """
DROP TRIGGER offline_report_immutable ON offline_payment_report;
DROP FUNCTION offline_reject_report_mutation();
DROP TRIGGER offline_reconciliation_immutable ON offline_reconciliation;
DROP FUNCTION offline_reject_reconciliation_mutation();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_instructions_order_revision'),
        ('payments', '0004_paymentreceipt_payment_order_once_applied_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePaymentPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('instructions', models.TextField(blank=True)),
                ('merchant_account_id', models.CharField(blank=True, max_length=80)),
                ('wechat_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('offline_timeout_minutes', models.PositiveIntegerField(default=1440)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offline_payment_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='offline_policy_singleton'), models.CheckConstraint(condition=models.Q(('offline_timeout_minutes__gte', 1), ('offline_timeout_minutes__lte', 10080), ('wechat_timeout_minutes__gte', 1), ('wechat_timeout_minutes__lte', 10080)), name='payment_timeouts_bounded')],
            },
        ),
        migrations.CreateModel(
            name='OfflinePaymentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('note', models.CharField(max_length=500)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reports', to='orders.order')),
            ],
            options={
                'db_table': 'offline_payment_report',
                'constraints': [models.UniqueConstraint(fields=('order', 'key'), name='offline_report_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfflineReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('expected_revision', models.PositiveIntegerField()),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('external_trade_no', models.CharField(max_length=128)),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('paid_at', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='DRAFT', max_length=16)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_reconciliations', to='orders.order')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'offline_reconciliation',
                'constraints': [models.UniqueConstraint(fields=('actor', 'key'), name='offline_reconciliation_actor_key'), models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='offline_reconciliation_positive')],
            },
        ),
        migrations.RunPython(seed_policy, migrations.RunPython.noop),
        migrations.RunSQL(IMMUTABLE, DROP),
    ]
