# Generated by Django 5.2.17 on 2026-09-26 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_admin_created_idx_and_more'),
        ('payments', '0005_offlinepaymentpolicy_offlinepaymentreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offlinereconciliation',
            index=models.Index(fields=['actor', '-created_at'], name='offline_actor_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='offlinereconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorized_at__isnull', True), ('outcome', 'DRAFT'), ('receipt__isnull', True)), models.Q(('authorized_at__isnull', False), ('outcome__in', ['AUTHORIZED', 'FAILED', 'PAID', 'ANOMALY', 'PENDING'])), _connector='OR'), name='offline_authorized_state_consistent'),
        ),
    ]
