# Generated by Django 5.2.17 on 2026-09-26 03:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0006_order_order_admin_created_idx_and_more'),
        ('payments', '0006_offlinereconciliation_offline_actor_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatPaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('out_trade_no', models.CharField(max_length=32, unique=True)),
                ('app_id', models.CharField(max_length=64)),
                ('merchant_id', models.CharField(max_length=80)),
                ('payer_openid', models.CharField(max_length=128)),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('prepay_id', models.CharField(blank=True, max_length=128)),
                ('prepay_expires_at', models.DateTimeField(null=True)),
                ('state', models.CharField(default='NEW', max_length=16)),
                ('trade_state', models.CharField(default='UNKNOWN', max_length=16)),
                ('close_requested', models.BooleanField(default=False)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wechat_attempt', to='orders.order')),
            ],
            options={
                'db_table': 'wechat_payment_attempt',
            },
        ),
        migrations.CreateModel(
            name='WechatOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PREPAY', 'Prepay'), ('QUERY', 'Query'), ('CLOSE', 'Close')], max_length=8)),
                ('result', models.CharField(default='STARTED', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='payments.wechatpaymentattempt')),
            ],
            options={
                'db_table': 'wechat_payment_operation',
            },
        ),
        migrations.CreateModel(
            name='WechatPrepayRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.wechatpaymentattempt')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'wechat_prepay_request',
            },
        ),
        migrations.AddIndex(
            model_name='wechatpaymentattempt',
            index=models.Index(fields=['state', 'next_check_at'], name='wechat_reconcile_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='wechat_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['NEW', 'PREPAYING', 'READY', 'UNKNOWN', 'PAID', 'ANOMALY', 'CLOSED', 'CLOSE_UNKNOWN'])), name='wechat_attempt_valid_state'),
        ),
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_token__isnull', True), ('lease_until__isnull', True)), models.Q(('lease_token__isnull', False), ('lease_until__isnull', False)), _connector='OR'), name='wechat_lease_consistent'),
        ),
        migrations.AddIndex(
            model_name='wechatoperation',
            index=models.Index(fields=['attempt', '-started_at'], name='wechat_operation_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='wechatoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('result', 'STARTED')), models.Q(('completed_at__isnull', False), ('result__in', ['SUCCEEDED', 'FAILED', 'SUPERSEDED'])), _connector='OR'), name='wechat_operation_result_time'),
        ),
        migrations.AddConstraint(
            model_name='wechatprepayrequest',
            constraint=models.UniqueConstraint(fields=('member', 'key'), name='wechat_member_prepay_key'),
        ),
    ]
