# Generated by Django 5.2.17 on 2026-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_admin_created_idx_and_more'),
        ('payments', '0008_wechat_immutable_evidence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('trade_state__in', ['UNKNOWN', 'SUCCESS', 'NOTPAY', 'USERPAYING', 'CLOSED', 'REVOKED', 'PAYERROR'])), name='wechat_trade_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('prepay_expires_at__isnull', True), ('prepay_id', '')), models.Q(models.Q(('prepay_id', ''), _negated=True), ('prepay_expires_at__isnull', False)), _connector='OR'), name='wechat_prepay_expiry_consistent'),
        ),
        migrations.AddConstraint(
            model_name='wechatpaymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('out_trade_no__regex', '^[A-Za-z0-9_-]{6,32}$')), name='wechat_external_order_valid'),
        ),
    ]
