# Generated by Django 5.2.17 on 2026-09-27 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0003_aftersalecase_aftersale_case_money_positive'),
        ('payments', '0009_wechatpaymentattempt_wechat_trade_state_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=8)),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('original_trade_no', models.CharField(max_length=128)),
                ('external_refund_no', models.CharField(max_length=128)),
                ('amount_fen', models.BigIntegerField()),
                ('refunded_at', models.DateTimeField()),
                ('source', models.CharField(max_length=24)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_evidence',
            },
        ),
        migrations.CreateModel(
            name='RefundIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_no', models.CharField(max_length=40, unique=True)),
                ('channel', models.CharField(max_length=8)),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('original_trade_no', models.CharField(max_length=128)),
                ('amount_fen', models.BigIntegerField()),
                ('request_key', models.UUIDField()),
                ('status', models.CharField(default='PREPARED', max_length=12)),
                ('active_operation_id', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('succeeded_at', models.DateTimeField(null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_intent', to='aftersales.aftersalecase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'refund_intent',
            },
        ),
        migrations.CreateModel(
            name='RefundHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.refundevidence')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='payments.refundintent')),
            ],
            options={
                'db_table': 'refund_history',
            },
        ),
        migrations.AddField(
            model_name='refundevidence',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='payments.refundintent'),
        ),
        migrations.CreateModel(
            name='RefundNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=8)),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('event_id', models.CharField(max_length=128)),
                ('evidence_digest', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.refundevidence')),
            ],
            options={
                'db_table': 'refund_notification',
            },
        ),
        migrations.CreateModel(
            name='RefundOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='PENDING', max_length=12)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='payments.refundintent')),
            ],
            options={
                'db_table': 'refund_operation',
            },
        ),
        migrations.CreateModel(
            name='RefundAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=24)),
                ('open', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly', to='payments.refundevidence')),
            ],
            options={
                'db_table': 'refund_anomaly',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('open', True), ('resolved_at__isnull', True)), models.Q(('open', False), ('resolved_at__isnull', False)), _connector='OR'), name='refund_anomaly_state_time')],
            },
        ),
        migrations.AddIndex(
            model_name='refundintent',
            index=models.Index(fields=['status', 'created_at'], name='refund_recovery_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.UniqueConstraint(fields=('created_by', 'request_key'), name='refund_actor_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='refund_intent_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['OFFLINE', 'WECHAT'])), name='refund_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PREPARED', 'PROCESSING', 'UNKNOWN', 'FAILED', 'SUCCEEDED'])), name='refund_intent_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUCCEEDED'), ('succeeded_at__isnull', False)), models.Q(models.Q(('status', 'SUCCEEDED'), _negated=True), ('succeeded_at__isnull', True)), _connector='OR'), name='refund_success_time'),
        ),
        migrations.AddConstraint(
            model_name='refundintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_operation_id__isnull', True), ('lease_until__isnull', True)), models.Q(('active_operation_id__isnull', False), ('lease_until__isnull', False)), _connector='OR'), name='refund_lease_shape'),
        ),
        migrations.AddConstraint(
            model_name='refundevidence',
            constraint=models.UniqueConstraint(fields=('channel', 'merchant_account_id', 'external_refund_no'), name='refund_external_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='refundevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('applied_at__isnull', False)), fields=('intent',), name='refund_intent_once_applied'),
        ),
        migrations.AddConstraint(
            model_name='refundevidence',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='refund_evidence_positive'),
        ),
        migrations.AddConstraint(
            model_name='refundevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel', 'OFFLINE'), ('confirmed_by__isnull', False), ('source', 'OFFLINE_RECONCILIATION')), models.Q(('channel', 'WECHAT'), ('confirmed_by__isnull', True), ('source__in', ['WECHAT_NOTIFICATION', 'WECHAT_QUERY'])), _connector='OR'), name='refund_evidence_source_shape'),
        ),
        migrations.AddConstraint(
            model_name='refundnotification',
            constraint=models.UniqueConstraint(fields=('channel', 'merchant_account_id', 'event_id'), name='refund_notify_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='refundoperation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['DISPATCH', 'QUERY'])), name='refund_operation_kind'),
        ),
        migrations.AddConstraint(
            model_name='refundoperation',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['PENDING', 'UNKNOWN', 'FAILED', 'PROCESSING', 'STALE'])), name='refund_operation_outcome'),
        ),
        migrations.AddConstraint(
            model_name='refundoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('outcome', 'PENDING')), models.Q(models.Q(('outcome', 'PENDING'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='refund_operation_time'),
        ),
    ]
