# Generated by Django 5.2.17 on 2026-09-27 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_refund_domain_side_effects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineRefundReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('expected_revision', models.PositiveIntegerField()),
                ('merchant_account_id', models.CharField(max_length=80)),
                ('external_refund_no', models.CharField(max_length=128)),
                ('amount_fen', models.BigIntegerField()),
                ('refunded_at', models.DateTimeField()),
                ('refund_method', models.CharField(max_length=20)),
                ('proof_reference', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(default='PENDING_CONFIRMATION', max_length=24)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_refund_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offline_reconciliation', to='payments.refundintent')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offline_refund_reconciliation',
                'constraints': [models.UniqueConstraint(fields=('prepared_by', 'request_key'), name='offline_refund_actor_key'), models.UniqueConstraint(fields=('merchant_account_id', 'external_refund_no'), name='offline_refund_transfer_unique'), models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='offline_refund_positive'), models.CheckConstraint(condition=models.Q(models.Q(('authorized_at__isnull', True), ('authorized_by__isnull', True)), models.Q(('authorized_at__isnull', False), ('authorized_by__isnull', False)), _connector='OR'), name='offline_refund_auth_shape'), models.CheckConstraint(condition=models.Q(('refund_method__in', ['BANK_TRANSFER', 'WECHAT_TRANSFER', 'ALIPAY_TRANSFER', 'CASH', 'OTHER'])), name='offline_refund_method')],
            },
        ),
    ]
