# Generated by Django 5.2.17 on 2026-09-27 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_offline_refund_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offlinerefundreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('authorized_at__isnull', True), ('outcome', 'PENDING_CONFIRMATION')), models.Q(('authorized_at__isnull', False), ('outcome__in', ['AUTHORIZED', 'SUCCEEDED', 'SETTLEMENT_FAILED', 'ANOMALY'])), _connector='OR'), name='offline_refund_outcome_shape'),
        ),
    ]
