# Generated by Django 5.2.17 on 2026-09-27 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_offlinerefundreconciliation_offline_refund_outcome_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatRefundNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=80)),
                ('event_id', models.CharField(max_length=128)),
                ('digest', models.CharField(max_length=64)),
                ('provider_status', models.CharField(max_length=12)),
                ('conflict', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wechat_notices', to='payments.refundintent')),
            ],
            options={
                'db_table': 'wechat_refund_notice',
                'constraints': [models.UniqueConstraint(fields=('merchant_id', 'event_id'), name='wechat_refund_notice_identity'), models.CheckConstraint(condition=models.Q(('provider_status__in', ['SUCCESS', 'CLOSED', 'ABNORMAL'])), name='wechat_refund_notice_status')],
            },
        ),
    ]
