# Generated by Django 5.2.17 on 2026-09-27 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_wechat_refund_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatrefundnotice',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='WechatRefundConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wechat_conflicts', to='payments.refundintent')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.wechatrefundnotice')),
            ],
            options={
                'db_table': 'wechat_refund_conflict',
                'constraints': [models.UniqueConstraint(fields=('notice', 'intent'), name='wechat_refund_conflict_once')],
            },
        ),
    ]
