# Generated by Django 5.2.17 on 2026-09-28 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0007_d3_settlement_guards'),
        ('payments', '0020_points_order_cash_binding_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refundintent',
            index=models.Index(condition=models.Q(('status', 'SUCCEEDED')), fields=['succeeded_at'], name='refund_success_fact_idx'),
        ),
    ]
