# Generated by Django 5.2.17 on 2026-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_refundintent_refund_success_fact_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepaymentpolicy',
            name='offline_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='offlinepaymentpolicy',
            name='wechat_enabled',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
