# Generated by Django 5.2.17 on 2026-10-10 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_address_location'),
        ('orders', '0016_store_snapshot_guard'),
        ('payments', '0022_offlinepaymentpolicy_offline_enabled_and_more'),
        ('stores', '0002_storemapconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWallet',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='wallet', serialize=False, to='stores.store')),
                ('available_fen', models.PositiveBigIntegerField(default=0)),
                ('frozen_fen', models.PositiveBigIntegerField(default=0)),
                ('paid_fen', models.PositiveBigIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StoreIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_fen', models.PositiveBigIntegerField(default=0)),
                ('cost_fen', models.PositiveBigIntegerField(default=0)),
                ('platform_fen', models.PositiveBigIntegerField(default=0)),
                ('freight_fen', models.PositiveBigIntegerField(default=0)),
                ('store_fen', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('available_at', models.DateTimeField(null=True)),
                ('settled_at', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store_income', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrderLineFinance',
            fields=[
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='store_finance', serialize=False, to='orders.orderline')),
                ('configured', models.BooleanField(default=False)),
                ('purchase_cost_fen', models.PositiveBigIntegerField(null=True)),
                ('platform_share_bps', models.PositiveSmallIntegerField(null=True)),
                ('policy_revision', models.PositiveIntegerField(null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('configured', False), ('platform_share_bps__isnull', True), ('policy_revision__isnull', True), ('purchase_cost_fen__isnull', True)), models.Q(('configured', True), ('platform_share_bps__lte', 10000), ('policy_revision__gte', 1), ('purchase_cost_fen__isnull', False)), _connector='OR'), name='store_order_finance_snapshot_valid')],
            },
        ),
        migrations.CreateModel(
            name='StoreWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('payee_name', models.CharField(max_length=80)),
                ('bank_name', models.CharField(max_length=120)),
                ('encrypted_bank_account', models.TextField()),
                ('bank_account_tail', models.CharField(max_length=4)),
                ('status', models.CharField(default='PENDING_REVIEW', max_length=24)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreWalletEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('actor_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.storeincome')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
                ('withdrawal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.storewithdrawal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storeincome',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SETTLED', 'HELD'])), name='store_income_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='storewithdrawal',
            constraint=models.UniqueConstraint(fields=('store', 'request_key'), name='store_withdrawal_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='storewithdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='store_withdrawal_positive'),
        ),
        migrations.AddConstraint(
            model_name='storewithdrawal',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_REVIEW', 'APPROVED_PENDING_PAYMENT', 'PAID', 'REJECTED'])), name='store_withdrawal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='storewalletevent',
            constraint=models.UniqueConstraint(fields=('income', 'kind'), name='store_income_event_once'),
        ),
        migrations.AddConstraint(
            model_name='storewalletevent',
            constraint=models.UniqueConstraint(fields=('withdrawal', 'kind'), name='store_withdrawal_event_once'),
        ),
    ]
