# Generated by Django 5.2.17 on 2026-10-10 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_store_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWithdrawalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.storewithdrawal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('withdrawal', 'action'), name='store_withdrawal_action_once')],
            },
        ),
    ]
