# Generated by Django 5.2.17 on 2026-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_withdrawal_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettlementCursor',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_created_at', models.DateTimeField(null=True)),
                ('last_order_id', models.UUIDField(null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='store_settlement_cursor_singleton')],
            },
        ),
    ]
