# Generated by Django 5.2.17 on 2026-10-10 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_address_location'),
        ('orders', '0016_store_snapshot_guard'),
        ('payments', '0026_store_finance_guards'),
        ('stores', '0003_store_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='storeorderlinefinance',
            name='store_order_finance_snapshot_valid',
        ),
        migrations.AddConstraint(
            model_name='storeorderlinefinance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('configured', False), ('platform_share_bps__isnull', True), ('policy_revision__isnull', True), ('purchase_cost_fen__isnull', True)), models.Q(('configured', True), ('platform_share_bps__isnull', False), ('platform_share_bps__lte', 10000), ('policy_revision__gte', 1), ('policy_revision__isnull', False), ('purchase_cost_fen__isnull', False)), _connector='OR'), name='store_order_finance_snapshot_valid'),
        ),
        migrations.AddConstraint(
            model_name='storewalletevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('income__isnull', False), ('kind', 'SETTLE'), ('withdrawal__isnull', True)), models.Q(('income__isnull', True), ('kind__in', ['FREEZE', 'RELEASE', 'OFFLINE_PAY']), ('withdrawal__isnull', False)), _connector='OR'), name='store_wallet_event_source_valid'),
        ),
    ]
