# Generated by Django 5.2.17 on 2026-10-10 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_product_unit_conversion'),
        ('customers', '0009_address_location'),
        ('inventory', '0012_pool_evidence_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('opening_hours', models.CharField(default='09:00–21:00', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('accepting_orders', models.BooleanField(default=True)),
                ('supported_modes', models.JSONField(default=list)),
                ('delivery_radius_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_fee_fen', models.PositiveIntegerField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='store', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_listings', to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequestQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_digest', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=80)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_digest', 'scope'), name='store_request_quota_unique')],
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_memberships', to='customers.member')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='stores.store')),
            ],
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='store_coordinate_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='store_product_unique'),
        ),
        migrations.AddConstraint(
            model_name='storestaff',
            constraint=models.UniqueConstraint(fields=('store', 'member'), name='store_staff_unique'),
        ),
    ]
