# Generated by Django 5.2.17 on 2026-10-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_unit_conversion'),
        ('stores', '0002_storemapconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSkuProfitRule',
            fields=[
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='catalog.sku')),
                ('unit_version', models.ForeignKey(null=True,on_delete=django.db.models.deletion.PROTECT,to='catalog.skuunitversion')),
                ('purchase_cost_fen', models.PositiveBigIntegerField()),
                ('platform_share_bps', models.PositiveSmallIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('platform_share_bps__lte', 10000)), name='store_profit_ratio_bounded')],
            },
        ),
    ]
