import test from 'node:test'
import assert from 'node:assert/strict'
import {recoveryDecision,resultMatches,definitiveRejection} from '../src/views/coupons/recovery.mjs'
const id='11a27082-c544-4ed8-8b70-3c1070bf560b',member='21a27082-c544-4ed8-8b70-3c1070bf560b',coupon='31a27082-c544-4ed8-8b70-3c1070bf560b'
const pending={path:`/coupon-campaigns/${id}/issuances`,method:'POST',action:'coupon.issue',body:{expectedRevision:2,memberId:member,quantity:1,reason:''}}
const campaign={code:'C',title:'Title',kind:'CASH',minGoodsFen:0,discountFen:100,productIds:[],productNames:[],redeemEligible:false,validFrom:'2026-10-01T00:00:00Z',validUntil:'2026-11-01T00:00:00Z',totalQuantity:100,selfClaimLimit:1,claimMode:'BOTH',issuanceEnabled:true,issuedQuantity:0,remainingQuantity:100}
const result={campaignId:id,memberId:member,quantity:1,couponIds:[coupon]}
test('only exact NOT_FOUND allows original request retry',()=>{assert.equal(recoveryDecision({status:'NOT_FOUND'},pending),'RETRY');for(const data of [{},{status:'PROCESSING'},{status:'COMPLETED'},{status:'COMPLETED',result:{}}])assert.equal(recoveryDecision(data,pending),'UNKNOWN');assert.equal(recoveryDecision({status:'COMPLETED',result},pending),'COMPLETED')})
test('issuance completion must match campaign member count and valid distinct coupons',()=>{assert.equal(resultMatches(pending,result),true);for(const patch of [{campaignId:member},{memberId:id},{quantity:2},{couponIds:[]},{couponIds:['bad']},{couponIds:[coupon,coupon]}])assert.equal(resultMatches(pending,{...result,...patch}),false)})
test('campaign publish and distribution must match identity revision and final state',()=>{const p={path:`/coupon-campaigns/${id}/publish`,method:'POST',action:'coupon.publish',body:{expectedRevision:2}};const r={...campaign,id,revision:3,status:'PUBLISHED'};assert.equal(resultMatches(p,r),true);for(const patch of [{id:member},{revision:2},{status:'DRAFT'}])assert.equal(resultMatches(p,{...r,...patch}),false);assert.equal(resultMatches({...p,path:`/coupon-campaigns/${id}/distribution`,body:{expectedRevision:2,issuanceEnabled:false}},{...r,issuanceEnabled:false}),true);assert.equal(resultMatches({...p,path:`/coupon-campaigns/${id}/distribution`,body:{expectedRevision:2,issuanceEnabled:false}},{...r,issuanceEnabled:true}),false)})
test('creation and editing completion must match saved terms',()=>{const body={code:'C',title:'Title',kind:'CASH',minGoodsFen:0,discountFen:100,productIds:[],redeemEligible:false,validFrom:'2026-10-01T00:00:00Z',validUntil:'2026-11-01T00:00:00Z',totalQuantity:100,selfClaimLimit:1,claimMode:'BOTH',issuanceEnabled:true};const p={path:'/coupon-campaigns',method:'POST',action:'',body};const r={...campaign,...body,id,revision:1,status:'DRAFT'};assert.equal(resultMatches(p,r),true);assert.equal(resultMatches(p,{...r,discountFen:200}),false);assert.equal(resultMatches({...p,path:`/coupon-campaigns/${id}`,method:'PUT',body:{...body,expectedRevision:4}},{...r,revision:5}),true)})
test('ambiguous throttle timeout and lost authorization preserve original identity',()=>{for(const status of [401,408,429,500,503])assert.equal(definitiveRejection(status),false);for(const status of [400,403,404,409,422])assert.equal(definitiveRejection(status),true)})
test('completion validates nested product DTO and malformed response safely',()=>{const body={...campaign,productIds:[coupon]};delete body.productNames;delete body.issuedQuantity;delete body.remainingQuantity;const p={path:'/coupon-campaigns',method:'POST',action:'',body},r={...campaign,...body,productNames:[{id:coupon,name:'商品'}],id,revision:1,status:'DRAFT'};assert.equal(resultMatches(p,r),true);for(const patch of [{productNames:[{id:'bad',name:'x'}]},{validUntil:'bad'},{productIds:[member]},{revision:'1'},{discountFen:'100'}])assert.equal(resultMatches(p,{...r,...patch}),false);assert.equal(recoveryDecision(null,p),'UNKNOWN');assert.equal(resultMatches(p,null),false);assert.equal(resultMatches({...p,path:'/other'},r),false)})
