import test from 'node:test'
import assert from 'node:assert/strict'
import {campaignError,campaignBody,issueError,pendingCoupon} from '../src/views/coupons/form.mjs'
const form={code:'SPRING',title:'春日礼券',kind:'FULL_REDUCTION',minimum:'100.00',discount:'10.01',productIds:[],redeemEligible:false,validFrom:'2026-10-01T00:00',validUntil:'2026-11-01T00:00',totalQuantity:'100',selfClaimLimit:'1',claimMode:'BOTH',issuanceEnabled:true}
test('campaign money is integer fen and cash threshold is zero',()=>{assert.equal(campaignError(form),'');assert.equal(campaignBody(form,2).discountFen,1001);assert.equal(campaignBody({...form,kind:'CASH'},2).minGoodsFen,0);for(const discount of ['1e2','1.001','-1','Infinity'])assert.ok(campaignError({...form,discount}))})
test('campaign bounds dates identities quantities and products',()=>{for(const patch of [{validUntil:form.validFrom},{totalQuantity:'0'},{selfClaimLimit:'101'},{code:''},{title:''},{productIds:['unsafe']},{totalQuantity:'1.5'}])assert.ok(campaignError({...form,...patch}));assert.ok(campaignError({...form,kind:'FULL_REDUCTION',minimum:'0'}))})
test('manual quantity and repeated grant cause cannot be omitted',()=>{assert.equal(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b','1','',false),'');assert.ok(issueError('bad','1','',false));assert.ok(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b','2','',true));assert.ok(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b','2','补偿',false));assert.equal(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b','2','补偿',true),'')})
test('unknown requests are actor scoped and frozen without passwords',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const p={key:'11a27082-c544-4ed8-8b70-3c1070bf560b',path:'/coupon-campaigns',method:'POST',body:campaignBody(form),action:''};pendingCoupon(storage,'a','new',p);assert.deepEqual(pendingCoupon(storage,'a','new'),p);assert.equal(pendingCoupon(storage,'b','new'),null);pendingCoupon(storage,'a','new',null);assert.equal(pendingCoupon(storage,'a','new'),null);map.set('mall:coupon:a:new','{"password":"secret"}');assert.equal(pendingCoupon(storage,'a','new'),null)})
test('campaign enum, validity, repeat and corrupt storage fail safely',()=>{for(const patch of [{kind:'OTHER'},{claimMode:'OTHER'},{validFrom:'bad'},{validUntil:'bad'},{selfClaimLimit:'0'},{totalQuantity:'1000001'},{productIds:Array(101).fill('11a27082-c544-4ed8-8b70-3c1070bf560b')},{title:'x'.repeat(101)},{code:'x'.repeat(65)}])assert.ok(campaignError({...form,...patch}));for(const q of ['0','101','1.5'])assert.ok(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b',q,'',true));assert.ok(issueError('11a27082-c544-4ed8-8b70-3c1070bf560b','1','x'.repeat(201),true));const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};for(const raw of ['{',JSON.stringify({key:'11a27082-c544-4ed8-8b70-3c1070bf560b',path:'/coupon-campaigns',method:'POST',body:[],action:''}),JSON.stringify({key:'11a27082-c544-4ed8-8b70-3c1070bf560b',path:'/coupon-campaigns',method:'POST',body:{expectedRevision:'bad'},action:''})]){map.set('mall:coupon:a:new',raw);assert.equal(pendingCoupon(storage,'a','new'),null)}})
