import test from 'node:test'
import assert from 'node:assert/strict'
import {offerError,offerBody,pendingExchange,resultMatches,recoveryDecision,definitiveRejection} from '../src/views/exchange/form.mjs'
const sku='11a27082-c544-4ed8-8b70-3c1070bf560b',id='21a27082-c544-4ed8-8b70-3c1070bf560b',product='31a27082-c544-4ed8-8b70-3c1070bf560b'
const offer={id,skuId:sku,productId:product,productName:'礼品',skuCode:'GIFT',specs:[{name:'规格',value:'一份'}],saleUnit:'份',fulfillmentKind:'SHIP',redeemValidUntil:null,pointsPrice:100,status:'DRAFT',revision:1,createdAt:'2026-09-27T00:00:00Z',imageUrl:'',availableQuantity:10}
test('offer price is a bounded integer and SKU is selected safely',()=>{assert.equal(offerError(sku,'100'),'');assert.deepEqual(offerBody(sku,'100'),{skuId:sku,pointsPrice:100});assert.deepEqual(offerBody(sku,'100',4),{expectedRevision:4,pointsPrice:100});for(const v of ['0','1.5','1000001','-1','1e2','bad'])assert.ok(offerError(sku,v));assert.ok(offerError('bad','100'))})
test('offer recovery binds original SKU price identity and exact revision',()=>{const p={key:sku,path:'/exchange-offers',method:'POST',action:'',body:{skuId:sku,pointsPrice:100}};assert.equal(resultMatches(p,offer),true);for(const patch of [{skuId:id},{pointsPrice:101},{id:'bad'},{revision:2},{status:'ON_SALE'}])assert.equal(resultMatches(p,{...offer,...patch}),false);assert.equal(recoveryDecision({status:'COMPLETED',result:offer},p),'COMPLETED');assert.equal(recoveryDecision({status:'NOT_FOUND'},p),'RETRY');for(const r of [{},{status:'PROCESSING'},{status:'COMPLETED',result:{}}])assert.equal(recoveryDecision(r,p),'UNKNOWN')})
test('edit and availability recovery validates request revision and final action',()=>{const p={key:sku,path:`/exchange-offers/${id}`,method:'PUT',action:'',body:{expectedRevision:1,pointsPrice:200}};assert.equal(resultMatches(p,{...offer,revision:2,pointsPrice:200}),true);assert.equal(resultMatches(p,{...offer,revision:2}),false);const a={...p,path:`/exchange-offers/${id}/availability`,method:'POST',action:'exchange.publish',body:{expectedRevision:1,status:'ON_SALE'}};assert.equal(resultMatches(a,{...offer,status:'ON_SALE',revision:2}),true);assert.equal(resultMatches(a,{...offer,status:'OFF_SALE',revision:2}),false);for(const status of [401,408,429,500])assert.equal(definitiveRejection(status),false);assert.equal(definitiveRejection(409),true)})
test('pending offer request is actor and object scoped and contains no password',()=>{const m=new Map(),s={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};const p={key:sku,path:'/exchange-offers',method:'POST',action:'',body:{skuId:sku,pointsPrice:100}};pendingExchange(s,'a','new',p);assert.deepEqual(pendingExchange(s,'a','new'),p);assert.equal(pendingExchange(s,'b','new'),null);pendingExchange(s,'a','new',null);assert.equal(pendingExchange(s,'a','new'),null);m.set('mall:exchange:a:new','{');assert.equal(pendingExchange(s,'a','new'),null)})
test('points orders have explicit settlement labels and never money as their main value',async()=>{const {isPointsOrder,orderSettlementValue,paymentMethodLabel}=await import('../src/shared/order-settlement.mjs');const {paymentStatus}=await import('../src/views/orders/offline-payment.mjs');const p={orderKind:'POINTS',paymentMethod:'POINTS',exchangePoints:420,status:'PAID',payableFen:0};assert.equal(isPointsOrder(p),true);assert.equal(orderSettlementValue(p),'420 积分');assert.equal(paymentMethodLabel(p),'纯积分兑换');assert.equal(paymentStatus(p),'已扣积分');assert.equal(orderSettlementValue({...p,orderKind:'CASH',paymentMethod:'OFFLINE',payableFen:1201}),'¥12.01');assert.equal(paymentMethodLabel({paymentMethod:'WECHAT'}),'微信支付');assert.equal(paymentStatus({...p,status:'CLOSED'}),'已关闭')})
test('unknown settlement values do not invent a zero and malformed offer payloads stay frozen',async()=>{const {orderSettlementValue,paymentMethodLabel}=await import('../src/shared/order-settlement.mjs');assert.equal(orderSettlementValue({paymentMethod:'POINTS'}),'待核查 积分');assert.equal(paymentMethodLabel({paymentMethod:'OFFLINE'}),'线下支付');assert.equal(paymentMethodLabel({paymentMethod:'OTHER'}),'待核查');const p={key:sku,path:'/exchange-offers',method:'POST',action:'',body:{skuId:sku,pointsPrice:100}};for(const patch of [{productId:'bad'},{specs:[{name:1,value:'x'}]},{createdAt:'bad'},{pointsPrice:0}])assert.equal(resultMatches(p,{...offer,...patch}),false);assert.equal(resultMatches(p,null),false);assert.equal(resultMatches({...p,path:'/bad'},offer),false);assert.equal(recoveryDecision(null,p),'UNKNOWN');const m=new Map(),s={getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};for(const value of [{...p,password:'bad'},{...p,body:[]},{...p,action:'bad'}]){m.set('mall:exchange:a:new',JSON.stringify(value));assert.equal(pendingExchange(s,'a','new'),null)}})
