import test from 'node:test'
import assert from 'node:assert/strict'
import { yuanToFen, ruleError, rulesBody, pendingRules } from '../src/views/customers/rules.mjs'
import {sourceReason} from '../src/views/customers/events.mjs'
const valid={grades:[{id:'a',amount:'0'},{id:'b',amount:'100'}],earnYuan:'1',earnPoints:'1',deductPoints:'100',deductYuan:'1',maxPercent:'50',validDays:'365',refundValidDays:'30',reason:'规则调整'}
test('money uses decimal strings and integer fen',()=>{assert.equal(yuanToFen('12.01'),1201);assert.equal(yuanToFen('0.10'),10);assert.equal(yuanToFen('1.001'),null);assert.equal(yuanToFen('-1'),null);assert.equal(yuanToFen('9999999999999999999'),null)})
test('thresholds must ascend and start at zero',()=>{assert.equal(ruleError(valid),'');assert.match(ruleError({...valid,grades:[...valid.grades,{id:'c',amount:'100'}]}),/递增/);assert.match(ruleError({...valid,earnPoints:'1.5'}),/整数/)})
test('body binds revision and exact integer amounts',()=>{const b=rulesBody(valid,4);assert.equal(b.expectedRevision,4);assert.equal(b.grades[0].minimumSpendFen,0);assert.equal(b.points.earnUnitFen,100)})
test('pending body and key are stable per account',()=>{const map=new Map(),s={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const x={key:'abc',body:rulesBody(valid,4)};pendingRules(s,'actor',x);assert.deepEqual(pendingRules(s,'actor'),x);assert.equal(pendingRules(s,'other'),null);pendingRules(s,'actor',null);assert.equal(pendingRules(s,'actor'),null)})
test('rule bounds prevent invalid ratios, dates and oversized amounts',()=>{for(const key of ['earnPoints','deductPoints','maxPercent','validDays','refundValidDays'])for(const value of ['0','-1','1000001','abc'])assert.notEqual(ruleError({...valid,[key]:value}),'');for(const key of ['earnYuan','deductYuan'])for(const value of ['0','10000.01','0.001'])assert.notEqual(ruleError({...valid,[key]:value}),'');assert.notEqual(ruleError({...valid,grades:[{id:'a',amount:'1'}]}),'');assert.notEqual(ruleError({...valid,grades:[{id:'a',amount:'0'},{id:'b',amount:'oops'}]}),'');assert.notEqual(ruleError({...valid,reason:' '}),'');assert.notEqual(ruleError({...valid,reason:'x'.repeat(201)}),'')})
test('corrupt persisted request cannot be submitted as a new body',()=>{const m=new Map(),s={getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};m.set('mall:member-rules:a','{');assert.equal(pendingRules(s,'a'),null);m.set('mall:member-rules:a',JSON.stringify({key:'k',body:{}}));assert.equal(pendingRules(s,'a'),null)})
test('public reasons explain completion, refund, reversal and expiry',()=>{assert.equal(sourceReason('ORDER_COMPLETED'),'订单履约完成');assert.equal(sourceReason('REFUND_COMPLETED'),'售后退款完成');assert.equal(sourceReason('FULFILLMENT_REVERSED'),'履约撤销');assert.equal(sourceReason('POINTS_EXPIRED'),'积分自然到期');assert.equal(sourceReason('ORDER_SETTLEMENT'),'订单权益结算');assert.equal(sourceReason('CLAWBACK'),'消费奖励扣回');assert.equal(sourceReason('UNKNOWN'),'其他积分变动')})
