const test=require('node:test'),assert=require('node:assert/strict'),storage=new Map()
global.getApp=()=>({globalData:{apiBaseUrl:'http://127.0.0.1:8000'}})
global.wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),removeStorageSync:k=>storage.delete(k),navigateTo(){},redirectTo(){},stopPullDownRefresh(){},showModal:({success})=>success({confirm:true})}
const offer={id:'e1',skuId:'s1',productId:'p1',productName:'积分好礼',skuCode:'sku',specs:[],saleUnit:'份',fulfillmentKind:'REDEEM',redeemValidUntil:'2027-12-31',pointsPrice:250,status:'ENABLED',revision:1,imageUrl:'/media/demo.jpg',availableQuantity:5}
const quote={quoteId:'q1',expiresAt:new Date(Date.now()+600000).toISOString(),orderKind:'POINTS',offerId:'e1',quantity:1,pointsUnitPrice:250,totalPoints:250,availablePoints:500,shippingFeeFen:0,ready:true,exchangeOrderAvailable:true,addressId:null,line:{...offer,name:offer.productName}}
const order={orderId:'o1',orderKind:'POINTS',paymentMethod:'POINTS',exchangePoints:250,status:'PAID',payableFen:0,goodsTotalFen:0,shippingFeeFen:0,couponDiscountFen:0,pointsDiscountFen:0,items:[{orderLineId:'l1',name:'积分好礼',quantity:1,pointsUnitPrice:250,pointsTotal:250,unitPriceFen:0,payableFen:0,fulfillmentKind:'REDEEM',specs:[],saleUnit:'份'}]}
const list=(items,page=1,total=items.length)=>({items,pagination:{page,pageSize:20,total}}),success=(r,data)=>r.success({statusCode:200,data:{success:true,data}}),failure=(r,status)=>r.success({statusCode:status,data:{success:false,error:{message:'拒绝',code:'BLOCKED'}}})
function page(name='detail'){storage.clear();storage.set('mall.memberToken','A');let d;global.Page=v=>d=v;const path=`../pages/exchange/${name}.js`;delete require.cache[require.resolve(path)];require(path);return {...d,data:structuredClone(d.data),setData(v){this.data={...this.data,...v}}}}
const ready=p=>{wx.request=r=>success(r,r.url.includes('/overview')?{id:'m1',points:{availablePoints:500}}:r.url.endsWith('/addresses')?[]:r.url.endsWith('/exchange-quotes')?quote:offer);return p.onLoad({id:'e1'})}
test('pure points helpers never convert by cash ratio and reject unsafe prices snapshots',()=>{const e=require('../lib/exchange'),r=e.presentOffer(offer);assert.equal(r.pointsLabel,'250 积分');assert.match(r.fulfillmentLabel,/核销/);assert.match(e.presentOffer({...offer,fulfillmentKind:'SHIP'}).deliveryCopy,/包邮/);assert.equal(e.presentQuote(quote).totalLabel,'250 积分');assert.throws(()=>e.presentOffer({...offer,pointsPrice:1.5}),/积分/);assert.throws(()=>e.presentQuote({...quote,totalPoints:249}),/积分/);assert.throws(()=>e.presentQuote({...quote,shippingFeeFen:1}),/积分/);assert.throws(()=>e.quantity('2.5'),/整数/);assert.throws(()=>e.quantity('100'),/99/)})
test('public exchange list paginates retries empty and hides stale responses',async()=>{const p=page('index');storage.clear();wx.request=r=>success(r,list([offer],1,2));await p.onShow();assert.equal(p.data.rows[0].pointsLabel,'250 积分');const rs=[];wx.request=r=>rs.push(r);const a=p.loadMore();p.loadMore();assert.equal(rs.length,1);rs[0].fail();await a;assert.ok(p.data.moreError);const b=p.loadMore();p.onHide();success(rs[1],list([offer],2,2));await b;assert.equal(p.data.rows.length,0);wx.request=r=>success(r,list([]));await p.onShow();assert.equal(p.data.state,'empty')})
test('quote requires本人 and revalidates quantity address and expiry before submission',async()=>{const p=page();await ready(p);await p.requestQuote();assert.equal(p.data.canSubmit,true);p.onQuantity({detail:{value:'2'}});assert.equal(p.data.quote,null);p.onQuantity({detail:{value:'1'}});wx.request=r=>success(r,{...quote,exchangeOrderAvailable:false});await p.requestQuote();assert.equal(p.data.canSubmit,false);assert.match(p.data.quoteWarning,/暂未开放/);wx.request=r=>success(r,{...quote,expiresAt:new Date(Date.now()-1).toISOString()});await p.requestQuote();assert.equal(p.data.canSubmit,false);storage.clear();let n=0;wx.request=()=>n++;await p.requestQuote();assert.equal(n,0)})
test('submission stores owner body UUID before POST and blocks duplicate click',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();const rs=[],urls=[];wx.redirectTo=v=>urls.push(v.url);wx.request=r=>rs.push(r);const a=p.submit();p.submit();assert.equal(rs.length,1);const saved=storage.get('mall.exchangeIntent.v1').m1;assert.deepEqual(saved.body,{quoteId:'q1'});assert.equal(saved.key,rs[0].header['Idempotency-Key']);success(rs[0],order);await a;assert.equal(p.data.state,'submitted');assert.equal(storage.get('mall.exchangeIntent.v1').m1,undefined);assert.match(urls[0],/orders\/detail\?id=o1&result=1/)})
test('UNKNOWN checks exact本人 receipt NOT_FOUND retries original body key, even expired quote',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();let r;wx.request=v=>r=v;const a=p.submit(),body=r.data,key=r.header['Idempotency-Key'];r.fail();await a;assert.ok(p.data.pending);const rs=[];wx.request=v=>rs.push(v);const b=p.retrySubmit();assert.match(rs[0].url,new RegExp(`/exchange-operations/${key}$`));success(rs[0],{status:'NOT_FOUND'});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(rs[1].data,body);assert.equal(rs[1].header['Idempotency-Key'],key);success(rs[1],order);await b;assert.equal(p.data.state,'submitted')})
test('COMPLETED recovery skips POST and rejects mismatched points result',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>r.fail();await p.submit();let posts=0;wx.request=r=>{if(r.method==='POST')posts++;success(r,{status:'COMPLETED',result:{...order,exchangePoints:251}})};await p.retrySubmit();assert.ok(p.data.pending);assert.equal(posts,0);wx.request=r=>success(r,{status:'COMPLETED',result:order});await p.retrySubmit();assert.equal(p.data.state,'submitted')})
test('persist failure prevents network; 403 is definite but 408 429 remain recoverable',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();let calls=0;wx.request=()=>calls++;const original=wx.setStorageSync;wx.setStorageSync=()=>{throw Error('disk')};await p.submit();wx.setStorageSync=original;assert.equal(calls,0);assert.match(p.data.submitError,/保存/);wx.request=r=>failure(r,403);await p.submit();assert.equal(p.data.pending,null);assert.equal(p.data.canSubmit,false);for(const code of [408,429]){wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>failure(r,code);await p.submit();assert.ok(p.data.pending);wx.request=r=>success(r,{status:'COMPLETED',result:order});await p.retrySubmit();p.setData({state:'ready'})}})
test('hidden submission owner durable intent survives but never restores old account',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();let r;wx.request=v=>r=v;const a=p.submit();p.onHide();success(r,order);await a;assert.equal(p.data.state,'loading');assert.ok(storage.get('mall.exchangeIntent.v1').m1);wx.request=v=>success(v,v.url.includes('/overview')?{id:'m2',points:{availablePoints:500}}:v.url.endsWith('/addresses')?[]:offer);storage.set('mall.memberToken','B');await p.onShow();assert.equal(p.data.pending,null);assert.ok(storage.get('mall.exchangeIntent.v1').m1)})
test('changed account during quote and before submit never sends new account old request',async()=>{const p=page();await ready(p);let r;wx.request=v=>r=v;const a=p.requestQuote();storage.set('mall.memberToken','B');success(r,quote);await a;assert.equal(p.data.quote,null);assert.equal(p.data.state,'auth');storage.set('mall.memberToken','A');await ready(p);wx.request=v=>success(v,quote);await p.requestQuote();storage.set('mall.memberToken','B');let n=0;wx.request=()=>n++;await p.submit();assert.equal(n,0)})
test('POINTS order presentation shows integer integral values without payment controls',()=>{const o=require('../lib/orders').present({...order,fulfillmentStatus:'WAITING_REDEMPTION'});assert.equal(o.isPoints,true);assert.equal(o.total,'250 积分');assert.equal(o.items[0].price,'250 积分');assert.equal(o.canReport,false);assert.equal(o.canPayWechat,false);assert.equal(o.canCancel,false);assert.match(o.resultTitle,/兑换成功/);assert.match(o.paymentLabel,/积分兑换/);assert.equal(o.canRequestExchangeCancel,true)})
test('SHIP quote includes selected address and rejects a mismatched address snapshot',async()=>{const p=page(),addr={id:'addr1',isDefault:true,recipientName:'本机测试',phone:'000',province:'测试',city:'测试',district:'测试',detail:'测试'};wx.request=r=>success(r,r.url.includes('/overview')?{id:'m1',points:{availablePoints:500}}:r.url.endsWith('/addresses')?[addr]:{...offer,fulfillmentKind:'SHIP'});await p.onLoad({id:'e1'});assert.equal(p.data.address.id,'addr1');wx.request=r=>{assert.equal(r.data.addressId,'addr1');success(r,{...quote,addressId:'other',line:{...quote.line,fulfillmentKind:'SHIP'}})};await p.requestQuote();assert.equal(p.data.quoteState,'error');assert.match(p.data.quoteError,/不一致/);wx.request=r=>success(r,{...quote,addressId:'addr1',line:{...quote.line,fulfillmentKind:'SHIP'},ready:false,blockedMessage:'库存不足'});await p.requestQuote();assert.equal(p.data.canSubmit,false);assert.match(p.data.quoteWarning,/库存/)})
test('public detail login and unavailable malformed auth network states are recoverable',async()=>{const p=page();storage.clear();wx.request=r=>success(r,offer);await p.onLoad({id:'e1'});assert.equal(p.data.availablePoints,null);await p.requestQuote();assert.match(p.data.quoteError,/登录/);wx.request=r=>failure(r,404);await p.refresh();assert.equal(p.data.state,'unavailable');wx.request=r=>r.fail();await p.refresh();assert.equal(p.data.state,'error');p.offerId='';let n=0;wx.request=()=>n++;await p.refresh();assert.equal(n,0);p.offerId='e1';storage.set('mall.memberToken','A');wx.request=r=>success(r,r.url.includes('/overview')?{}:r.url.endsWith('/addresses')?[]:offer);await p.refresh();assert.equal(p.data.state,'error');wx.request=r=>failure(r,401);await p.refresh();assert.equal(p.data.state,'auth');assert.equal(p.data.address,null)})
test('quantity validation stale requotes and submit expiry are guarded',async()=>{const p=page();await ready(p);p.onQuantity({detail:{value:'2.2'}});await p.requestQuote();assert.match(p.data.quoteError,/整数/);p.onQuantity({detail:{value:'1'}});const rs=[];wx.request=r=>rs.push(r);const a=p.requestQuote();p.onQuantity({detail:{value:'2'}});success(rs[0],quote);await a;assert.equal(p.data.quote,null);p.onQuantity({detail:{value:'1'}});wx.request=r=>failure(r,503);await p.requestQuote();assert.equal(p.data.quoteState,'error');wx.request=r=>success(r,quote);await p.requestQuote();p.setData({quote:{...p.data.quote,expiresAt:new Date(Date.now()-1).toISOString()}});let n=0;wx.request=()=>n++;await p.submit();assert.equal(n,0);assert.equal(p.data.canSubmit,false)})
test('load refresh generations unload and own pending on show preserve identity',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>r.fail();await p.submit();wx.request=r=>success(r,r.url.includes('/overview')?{id:'m1',points:{availablePoints:500}}:r.url.endsWith('/addresses')?[]:offer);p.shown=true;await p.onShow();assert.ok(p.data.pending);p.onQuantity({detail:{value:'9'}});assert.equal(p.data.quantity,'1');await p.requestQuote();const rs=[];wx.request=r=>rs.push(r);const a=p.refresh(),b=p.refresh();success(rs[2],{id:'m1',points:{availablePoints:500}});success(rs[3],[]);await new Promise(resolve=>setImmediate(resolve));success(rs[4],{...offer,productName:'new'});await b;success(rs[0],{id:'m1',points:{availablePoints:500}});success(rs[1],[]);await a;assert.equal(p.data.offer.productName,'new');const c=p.refresh();p.onUnload();success(rs[5],{id:'m1',points:{availablePoints:500}});success(rs[6],[]);await c;assert.equal(p.data.address,null)})
test('implemented entry routes and image fallback do not depend on cart or money',async()=>{const p=page(),urls=[];wx.navigateTo=v=>urls.push(v.url);await ready(p);p.chooseAddress();p.login();p.openOrders();p.openPoints();p.openMall();p.onImageError();assert.equal(p.data.failedImage,true);assert.deepEqual(urls,['/pages/addresses/addresses?select=1','/pages/login/login?returnTo=exchange','/pages/orders/list?orderKind=POINTS','/pages/member/points','/pages/exchange/index']);const l=page('index');wx.request=r=>success(r,list([offer]));await l.onShow();l.openOffer({currentTarget:{dataset:{id:'other'}}});l.openOffer({currentTarget:{dataset:{id:'e1'}}});l.openOrders();l.openPoints();l.onImageError({currentTarget:{dataset:{id:'e1'}}});assert.equal(l.data.failedImages.e1,true);let stopped=0;wx.stopPullDownRefresh=()=>stopped++;await l.onPullDownRefresh();l.onReachBottom();await ready(p);await p.onPullDownRefresh();assert.equal(stopped,2)})
test('malformed recovery and storage clear errors keep original key available',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>r.fail();await p.submit();const key=p.data.pending.key;wx.request=r=>success(r,{status:'FUTURE'});await p.retrySubmit();assert.equal(p.data.pending.key,key);const original=wx.setStorageSync;wx.setStorageSync=()=>{throw Error('disk')};wx.request=r=>success(r,{status:'COMPLETED',result:order});await p.retrySubmit();wx.setStorageSync=original;assert.equal(p.data.pending.key,key);wx.redirectTo=v=>v.fail();wx.request=r=>success(r,{status:'COMPLETED',result:order});await p.retrySubmit();assert.equal(p.data.state,'submitted');assert.match(p.data.submitError,/跳转失败/)})
test('POINTS aftersale uses exact refund integral fields and separates proposal from completion',()=>{const sale=require('../lib/aftersales'),base={caseId:'case',orderKind:'POINTS',status:'WAITING_REFUND',kind:'REFUND_ONLY',amountFen:0,quantity:2,fulfillmentKind:'REDEEM',requestedRefundPoints:500,effectiveRefundPoints:250,returnedPoints:0};const r=sale.presentCase(base);assert.equal(r.isPoints,true);assert.equal(r.amountLabel,'500 积分');assert.equal(r.effectivePointsLabel,'250 积分');assert.match(r.statusCopy,/等待平台确认/);assert.equal(sale.presentCase({...base,status:'COMPLETED',returnedPoints:250}).returnedPointsLabel,'250 积分');assert.throws(()=>sale.presentCase({...base,effectiveRefundPoints:undefined}),/兑换积分/)})
test('pending exact owner recovery remains available when public offer disappears',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>r.fail();await p.submit();const key=p.data.pending.key;wx.request=r=>r.url.includes('/overview')?success(r,{id:'m1',points:{availablePoints:250}}):r.url.endsWith('/addresses')?success(r,[]):failure(r,404);await p.refresh();assert.equal(p.data.state,'ready');assert.equal(p.data.offer,null);assert.equal(p.data.pending.key,key);const requests=[];wx.request=r=>{requests.push(r);success(r,{status:'COMPLETED',result:order})};await p.retrySubmit();assert.match(requests[0].url,new RegExp(`/exchange-operations/${key}$`));assert.equal(requests.length,1);assert.equal(p.data.state,'submitted')})

test('pending owner recovery ignores address service failure and never needs a new quote',async()=>{const p=page();await ready(p);wx.request=r=>success(r,quote);await p.requestQuote();wx.request=r=>r.fail();await p.submit();const key=p.data.pending.key;wx.request=r=>r.url.includes('/overview')?success(r,{id:'m1',points:{availablePoints:250}}):failure(r,503);await p.refresh();assert.equal(p.data.state,'ready');assert.equal(p.data.pending.key,key);assert.equal(p.data.offer,null);wx.request=r=>success(r,{status:'COMPLETED',result:order});await p.retrySubmit();assert.equal(p.data.state,'submitted')})

test('POINTS proposals do not claim approval before review and never use cash refund labels',()=>{const s=require('../lib/aftersales'),row={caseId:'c',orderKind:'POINTS',status:'PENDING_REVIEW',kind:'REFUND_ONLY',amountFen:0,quantity:1,requestedRefundPoints:500,effectiveRefundPoints:500,returnedPoints:0};assert.equal(s.presentCase(row).effectivePointsLabel,'待审核');assert.equal(s.presentCase(row).kindLabel,'仅退积分');assert.equal(s.presentCase({...row,status:'REJECTED'}).effectivePointsLabel,'未获准');assert.equal(s.presentCase({...row,status:'WAITING_REFUND',kind:'RETURN_REFUND'}).kindLabel,'退货退积分');assert.equal(s.optionLabel({kind:'REFUND_ONLY'},'SHIP','POINTS'),'仅退积分')})

test('POINTS waiting and event labels identify points return rather than cash',()=>{const s=require('../lib/aftersales');const row={caseId:'c',orderKind:'POINTS',status:'WAITING_REFUND',kind:'REFUND_ONLY',amountFen:0,quantity:1,requestedRefundPoints:500,effectiveRefundPoints:500,returnedPoints:0,events:[{status:'WAITING_REFUND'}]};const r=s.presentCase(row);assert.equal(r.statusLabel,'待退积分');assert.equal(r.events[0].statusLabel,'待退积分');assert.equal(s.presentCase({...row,orderKind:'CASH'}).statusLabel,'待退款')})
