const test = require('node:test')
const assert = require('node:assert/strict')
const storage = new Map()
global.wx = { getStorageSync: k => storage.get(k), setStorageSync: (k,v) => storage.set(k,v), removeStorageSync: k => storage.delete(k) }
const stores = require('../lib/stores')
const cart = require('../lib/cart')
test('consumer selection isolates carts and keeps legacy basket', () => {
 storage.clear(); cart.add({skuId:'a',quantity:1}); stores.select({id:'s1',name:'一店'}); assert.deepEqual(cart.read(),[])
 cart.add({skuId:'a',quantity:2}); stores.select({id:'s2',name:'二店'}); cart.add({skuId:'a',quantity:3})
 stores.select({id:'s1',name:'一店'}); assert.equal(cart.read()[0].quantity,2); stores.clear(); assert.equal(cart.read()[0].quantity,1)
 assert.equal(stores.managed(),null)
})
test('nearby ranking does not invent location and validates coordinates', () => {
 const rows=[{id:'a',latitude:0,longitude:1},{id:'b',latitude:0,longitude:0}]
 assert.equal(stores.rank(rows,{latitude:0,longitude:0})[0].id,'b'); assert.equal(stores.rank(rows,null)[0].distanceLabel,'')
 assert.equal(stores.distance({latitude:100,longitude:0},rows[0]),null)
})
test('shared base stock pools have one editor and stock validation is strict', () => {
 const product={id:'p',revision:2,onSale:true,skus:[{id:'s1',anchorSkuId:'s1',baseUnit:'瓶',ratio:1,availableBaseUnits:10},{id:'s2',anchorSkuId:'s1',baseUnit:'瓶',ratio:12,availableBaseUnits:10}]}
 const pools=stores.stockPools(product); assert.equal(pools.length,1)
 assert.deepEqual(stores.stockPatch(product,{'s1':'8'}),{revision:2,onSale:true,stock:[{skuId:'s1',availableBaseUnits:8,expectedAvailableBaseUnits:10}]})
 assert.throws(()=>stores.stockPatch(product,{'s1':'-2'}),/非负整数/)
 assert.throws(()=>stores.stockPatch(product,{'s1':'1.2'}),/非负整数/)
})
test('managed store context never changes consumer selection',()=>{storage.clear();stores.select({id:'a',name:'顾客门店'});stores.manage('b');assert.equal(stores.managed(),'b');assert.equal(stores.selected().id,'a')})
const api=require('../lib/api')
function mount(path){let config;global.Page=c=>config=c;delete require.cache[require.resolve(path)];require(path);return {...config,data:structuredClone(config.data),setData(v){this.data={...this.data,...v}}}}
test('delivery options whitelist supported modes and invalid store is rejected',()=>{assert.deepEqual(stores.modes({supportedModes:['PICKUP','bad']}),[{value:'PICKUP',label:'到店自提'}]);assert.throws(()=>stores.select({}),/有效门店/);assert.equal(stores.coordinates({latitude:null,longitude:0}),false)})
test('locator handles permission denied and nearby distance labels',async()=>{wx.getLocation=o=>o.fail();await assert.rejects(stores.locate(),/定位权限/);wx.getLocation=o=>o.success({latitude:0,longitude:0});assert.deepEqual(await stores.locate(),{latitude:0,longitude:0});assert.match(stores.rank([{latitude:0,longitude:.01}],{latitude:0,longitude:0})[0].distanceLabel,/km/);delete wx.getLocation;await assert.rejects(stores.locate(),/暂不可用/)})
test('store list queries server q and manual selection changes only consumer context',async()=>{const old=api.get;let query;api.get=async(p,q)=>{query=q;return {items:[{id:'s',name:'门店'}]}};const p=mount('../pages/stores/list.js');p.data.keyword='测试';await p.onLoad();assert.equal(query.q,'测试');wx.navigateBack=()=>{};p.choose({currentTarget:{dataset:{id:'s'}}});assert.equal(stores.selected().id,'s');api.get=old})
test('store center loads authorized store, groups stock and PATCHes current revision',async()=>{storage.clear();storage.set('mall.memberToken','member');const oldGet=api.get,oldPatch=api.patch;const product={id:'p',onSale:true,revision:4,skus:[{id:'sku',anchorSkuId:'sku',availableBaseUnits:8,baseUnit:'瓶'}]};let body;api.get=async(path)=>path.endsWith('/products')?{items:[product],total:1}: {items:[{id:'store',name:'店',permissions:['products']}]};api.patch=async(path,value)=>{body=value};wx.showToast=()=>{};const p=mount('../pages/store-center/index.js');await p.onShow();assert.equal(p.data.canProducts,true);p.data.section='products';await p.loadSection();p.stockInput({currentTarget:{dataset:{product:'p',pool:'sku'}},detail:{value:'7'}});await p.saveProduct({currentTarget:{dataset:{id:'p'}}});assert.equal(body.revision,4);assert.equal(body.stock[0].availableBaseUnits,7);await p.saveProduct({currentTarget:{dataset:{id:'p',toggle:true}}});assert.equal(body.onSale,false);p.onHide();assert.deepEqual(p.data.products,[]);api.get=oldGet;api.patch=oldPatch})
test('store order uncertain operation retries exact request and requires paid authority',async()=>{storage.clear();storage.set('mall.memberToken','member');const oldGet=api.get,oldPost=api.post;const order={orderId:'order',status:'PAID',revision:7,deliveryMode:'PICKUP',items:[],storeDelivery:{status:'WAITING_PICKUP'}};api.get=async()=>order;const p=mount('../pages/store-center/order.js');await p.onLoad({id:'order',storeId:'store'});assert.equal(p.data.canComplete,true);p.data.pickupCode='CUSTOMER';const attempts=[];api.post=async(path,body,headers)=>{attempts.push({body,headers});if(attempts.length===1)throw new Error('network');return {...order,revision:8,storeDelivery:{status:'COMPLETED'}}};await p.act({currentTarget:{dataset:{action:'COMPLETE'}}});assert.equal(p.data.uncertain,true);await p.send();assert.deepEqual(attempts[0],attempts[1]);assert.equal(attempts[0].body.pickupCode,'CUSTOMER');p.present({...order,status:'PENDING_PAYMENT'});assert.equal(p.data.canComplete,false);api.get=oldGet;api.post=oldPost})
test('store aftersale submits factual quantities and unknown result retries safely',async()=>{storage.clear();storage.set('mall.memberToken','member');const oldGet=api.get,oldPost=api.post;api.get=async()=>({caseId:'case',revision:2,canRecordReceipt:true});const p=mount('../pages/store-center/aftersale.js');await p.onLoad({id:'case',storeId:'s'});p.data.note='收到退货外观正常';p.data.receivedQuantity='2';p.data.salableQuantity='1';let body;api.post=async(_,v)=>{body=v};await p.record({currentTarget:{dataset:{kind:'RECEIPT'}}});assert.deepEqual(body,{kind:'RECEIPT',note:'收到退货外观正常',expectedRevision:2,receivedQuantity:2,salableQuantity:1});api.get=oldGet;api.post=oldPost})
test('home matches nearby accepting store and retains explicit unavailable choice without default stock',async()=>{
 storage.clear();const oldGet=api.get;wx.getLocation=o=>o.success({latitude:0,longitude:0});api.get=async()=>({items:[{id:'paused',acceptingOrders:false,supportedModes:['PICKUP'],latitude:0,longitude:0},{id:'open',name:'正常门店',acceptingOrders:true,supportedModes:['PICKUP'],latitude:0,longitude:.01}]});let p=mount('../pages/home/home.js');await p.loadStore();assert.equal(stores.selected().id,'open');assert.equal(p.data.store.name,'正常门店');api.get=async()=>{const e=new Error('门店已停用');e.statusCode=404;throw e};p=mount('../pages/home/home.js');p.homeToken=0;await p.loadStore();await p.loadHome();assert.equal(p.data.state,'error');assert.equal(stores.selected().id,'open');assert.deepEqual(p.data.components,[]);api.get=oldGet
})
test('store center stale member response cannot restore private stock',async()=>{storage.clear();storage.set('mall.memberToken','a');const oldGet=api.get;let resolve;api.get=()=>new Promise(r=>resolve=r);const p=mount('../pages/store-center/index.js');const pending=p.onShow();storage.set('mall.memberToken','b');resolve({items:[{id:'s',permissions:['products']}]});await pending;assert.equal(p.data.store,null);assert.deepEqual(p.data.products,[]);api.get=oldGet})
test('homepage custom navigation leaves native capsule clear and declared location access',()=>{const fs=require('node:fs'),path=require('node:path');const root=path.join(__dirname,'..');const app=JSON.parse(fs.readFileSync(path.join(root,'app.json')));const page=JSON.parse(fs.readFileSync(path.join(root,'pages/home/home.json')));assert.equal(page.navigationStyle,'custom');assert.ok(app.requiredPrivateInfos.includes('chooseLocation'));const html=fs.readFileSync(path.join(root,'pages/home/home.wxml'),'utf8');assert.match(html,/capsuleRight/);assert.match(html,/store.name/);assert.ok(!html.includes('距离 0.8'))})
test('login checkout recovery cannot move old store basket into a newly selected store',()=>{storage.clear();const session=require('../lib/session');stores.select({id:'first'});session.rememberCheckout([{skuId:'a',quantity:2}]);stores.select({id:'second'});assert.deepEqual(session.recoverCheckout(),[]);assert.equal(storage.has('mall.checkoutRecovery.v1'),false)})
test('delivery quote errors keep mode/address recovery and existing address visible',async()=>{storage.clear();storage.set('mall.memberToken','member');stores.select({id:'store',supportedModes:['PICKUP','DELIVERY','EXPRESS']});storage.set('mall.checkoutSelection.v1',[{skuId:'sku',quantity:1}]);const oldGet=api.get,oldPost=api.post;let visited='';wx.navigateTo=o=>visited=o.url;api.get=async()=>[];api.post=async()=>{throw new Error('配送到家需要收货地址与坐标')};const p=mount('../pages/checkout/checkout.js');await p.onLoad();await p.selectDelivery({detail:{value:'DELIVERY'}});assert.equal(p.data.state,'error');p.chooseAddress();assert.equal(visited,'/pages/addresses/addresses?select=1');api.get=async()=>[{id:'a',isDefault:true,detail:'旧地址',latitude:null,longitude:null}];await p.refresh();assert.equal(p.data.address.id,'a');assert.equal(p.data.state,'error');await p.selectDelivery({detail:{value:'PICKUP'}});assert.equal(p.data.deliveryMode,'PICKUP');const fs=require('node:fs');const html=fs.readFileSync(require('node:path').join(__dirname,'../pages/checkout/checkout.wxml'),'utf8');assert.ok(html.indexOf('bindchange="selectDelivery"')<html.indexOf("state === 'loading'"));assert.ok(html.indexOf('bindtap="chooseAddress"')<html.indexOf('  <block wx:else>'));api.get=oldGet;api.post=oldPost})
test('unlocated address pending quote never enables submission even with goods ready',async()=>{storage.clear();storage.set('mall.memberToken','member');stores.select({id:'store',supportedModes:['DELIVERY']});storage.set('mall.checkoutSelection.v1',[{skuId:'sku',quantity:1}]);const oldGet=api.get,oldPost=api.post;api.get=async(path)=>path.endsWith('/addresses')?[{id:'a',isDefault:true}]:{configured:true,instructions:'支付说明'};api.post=async()=>({quoteId:'q',lines:[],availablePaymentMethods:['OFFLINE'],goodsTotalFen:100,shippingFeeFen:0,couponDiscountFen:0,pointsDiscountFen:0,payableFen:100,ready:true,orderSubmissionAvailable:true,addressRequired:true,deliveryEligibilityPending:true,deliveryMessage:'地址尚未定位'});const p=mount('../pages/checkout/checkout.js');await p.onLoad();assert.equal(p.data.state,'ready');assert.equal(p.data.canSubmit,false);assert.equal(p.data.quoteWarning,'地址尚未定位');p.selectPayment({detail:{value:'OFFLINE'}});assert.equal(p.data.canSubmit,false);api.get=oldGet;api.post=oldPost})
