# Generated by Django 5.2.17 on 2026-09-28 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AUDIT', 'Audit'), ('BUSINESS', 'Business')], max_length=8)),
                ('request_key', models.UUIDField()),
                ('filters', models.JSONField(default=dict)),
                ('filters_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=8)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('object_key', models.CharField(blank=True, max_length=160)),
                ('file_sha256', models.CharField(blank=True, max_length=64)),
                ('file_bytes', models.PositiveBigIntegerField(default=0)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_export_task',
                'indexes': [models.Index(fields=['status', 'lease_until', 'created_at'], name='export_worker_due_idx'), models.Index(fields=['-created_at', '-id'], name='export_admin_page_idx'), models.Index(fields=['expires_at'], name='export_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'request_key'), name='export_actor_request_unique'), models.CheckConstraint(condition=models.Q(('kind__in', ['AUDIT', 'BUSINESS'])), name='export_kind_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'READY', 'FAILED', 'EXPIRED'])), name='export_status_valid'), models.CheckConstraint(condition=models.Q(('attempt_count__lte', 3)), name='export_attempt_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('lease_token__isnull', False), ('lease_until__isnull', False), ('status', 'RUNNING')), models.Q(models.Q(('status', 'RUNNING'), _negated=True), ('lease_token__isnull', True), ('lease_until__isnull', True)), _connector='OR'), name='export_lease_shape'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY'), _negated=True), models.Q(models.Q(('object_key', ''), _negated=True), models.Q(('file_sha256', ''), _negated=True), ('file_bytes__gt', 0), ('completed_at__isnull', False), ('expires_at__isnull', False)), _connector='OR'), name='export_ready_file_shape')],
            },
        ),
    ]
