# Generated by Django 5.2.17 on 2026-09-27 02:56

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0007_orderline_redeem_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleAllocation',
            fields=[
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='orders.orderline')),
                ('purchased_qty', models.PositiveIntegerField()),
                ('payable_fen', models.PositiveBigIntegerField()),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('refunded_qty', models.PositiveIntegerField(default=0)),
                ('reserved_fen', models.PositiveBigIntegerField(default=0)),
                ('refunded_fen', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'aftersale_allocation',
                'constraints': [models.CheckConstraint(condition=models.Q(('purchased_qty__gt', 0)), name='aftersale_purchased_positive'), models.CheckConstraint(condition=models.Q(('purchased_qty__gte', django.db.models.expressions.CombinedExpression(models.F('reserved_qty'), '+', models.F('refunded_qty')))), name='aftersale_qty_bounded'), models.CheckConstraint(condition=models.Q(('payable_fen__gte', django.db.models.expressions.CombinedExpression(models.F('reserved_fen'), '+', models.F('refunded_fen')))), name='aftersale_money_bounded')],
            },
        ),
        migrations.CreateModel(
            name='AfterSaleCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('unredeemed_quantity', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('REFUND_ONLY', 'Refund Only'), ('RETURN_REFUND', 'Return Refund')], max_length=13)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('WAITING_RETURN', 'Waiting Return'), ('WAITING_REFUND', 'Waiting Refund'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING_REVIEW', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersale_cases', to='orders.orderline')),
            ],
            options={
                'db_table': 'aftersale_case',
            },
        ),
        migrations.CreateModel(
            name='AfterSaleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='aftersales.aftersalecase')),
            ],
            options={
                'db_table': 'aftersale_event',
            },
        ),
        migrations.CreateModel(
            name='AfterSalePolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('received_window_days', models.PositiveSmallIntegerField(default=15)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'aftersale_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='aftersale_policy_singleton'), models.CheckConstraint(condition=models.Q(('received_window_days__gte', 1), ('received_window_days__lte', 365)), name='aftersale_policy_days')],
            },
        ),
        migrations.CreateModel(
            name='OrderAfterSaleSnapshot',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='orders.order')),
                ('received_window_days', models.PositiveSmallIntegerField()),
                ('policy_revision', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'aftersale_order_snapshot',
                'constraints': [models.CheckConstraint(condition=models.Q(('received_window_days__gte', 1), ('received_window_days__lte', 365)), name='aftersale_snapshot_days')],
            },
        ),
        migrations.AddIndex(
            model_name='aftersalecase',
            index=models.Index(fields=['status', 'created_at'], name='aftersale_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.UniqueConstraint(fields=('member', 'request_key'), name='aftersale_member_key'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_REVIEW', 'WAITING_RETURN', 'WAITING_REFUND'])), fields=('order_line',), name='aftersale_line_one_active'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='aftersale_case_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', django.db.models.expressions.CombinedExpression(models.F('used_quantity'), '+', models.F('unredeemed_quantity')))), name='aftersale_scope_bounded'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_REVIEW', 'WAITING_RETURN', 'WAITING_REFUND', 'COMPLETED', 'REJECTED', 'WITHDRAWN'])), name='aftersale_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['REFUND_ONLY', 'RETURN_REFUND'])), name='aftersale_kind_valid'),
        ),
    ]
