# Generated by Django 5.2.17 on 2026-09-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0002_evidence_guards'),
        ('customers', '0001_initial'),
        ('orders', '0007_orderline_redeem_valid_until'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='aftersale_case_money_positive'),
        ),
    ]
