# Generated by Django 5.2.17 on 2026-09-27 03:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0003_aftersalecase_aftersale_case_money_positive'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('expected_revision', models.PositiveIntegerField()),
                ('mode', models.CharField(max_length=13)),
                ('received_quantity', models.PositiveIntegerField()),
                ('salable_quantity', models.PositiveIntegerField()),
                ('refund_quantity', models.PositiveIntegerField()),
                ('refund_amount_fen', models.PositiveBigIntegerField()),
                ('max_refund_amount_fen', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_acceptance', to='aftersales.aftersalecase')),
            ],
            options={
                'db_table': 'aftersale_return_acceptance',
                'constraints': [models.UniqueConstraint(fields=('actor', 'request_key'), name='return_acceptance_actor_key'), models.CheckConstraint(condition=models.Q(('mode__in', ['RECEIVED', 'WAIVED_RETURN'])), name='return_acceptance_mode'), models.CheckConstraint(condition=models.Q(('salable_quantity__lte', models.F('received_quantity'))), name='return_salable_bounded'), models.CheckConstraint(condition=models.Q(('refund_amount_fen__lte', models.F('max_refund_amount_fen'))), name='return_amount_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('refund_amount_fen', 0), ('refund_quantity', 0)), models.Q(('refund_amount_fen__gt', 0), ('refund_quantity__gt', 0)), _connector='OR'), name='return_refund_shape'), models.CheckConstraint(condition=models.Q(models.Q(('mode', 'RECEIVED'), ('refund_quantity__lte', models.F('received_quantity'))), models.Q(('mode', 'WAIVED_RETURN'), ('received_quantity', 0), ('salable_quantity', 0)), _connector='OR'), name='return_receipt_shape')],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('expected_revision', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField()),
                ('carrier_name', models.CharField(max_length=80)),
                ('tracking_no', models.CharField(max_length=80)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_shipments', to='aftersales.aftersalecase')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.member')),
            ],
            options={
                'db_table': 'aftersale_return_shipment',
                'indexes': [models.Index(fields=['case', '-revision'], name='return_shipment_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'request_key'), name='return_shipment_member_key'), models.UniqueConstraint(fields=('case', 'revision'), name='return_shipment_case_revision')],
            },
        ),
    ]
