# Generated by Django 5.2.17 on 2026-09-27 04:26

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftersales', '0005_return_guards'),
        ('customers', '0001_initial'),
        ('orders', '0007_orderline_redeem_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitOnlySettlement',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='aftersales.aftersalecase')),
                ('request_key', models.UUIDField()),
                ('expected_revision', models.PositiveIntegerField()),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aftersale_benefit_settlement',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingRefundClaim',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='orders.order')),
                ('amount_fen', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aftersale_shipping_refund_claim',
            },
        ),
        migrations.CreateModel(
            name='RefundAmountSnapshot',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='refund_amount_snapshot', serialize=False, to='aftersales.aftersalecase')),
                ('goods_fen', models.PositiveBigIntegerField()),
                ('shipping_fen', models.PositiveBigIntegerField(default=0)),
                ('total_fen', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aftersale_refund_amount_snapshot',
            },
        ),
        migrations.RemoveConstraint(
            model_name='aftersalecase',
            name='aftersale_case_money_positive',
        ),
        migrations.RemoveConstraint(
            model_name='returnacceptance',
            name='return_refund_shape',
        ),
        migrations.AddConstraint(
            model_name='aftersalecase',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gte', 0)), name='aftersale_case_money_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnacceptance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refund_amount_fen', 0), ('refund_quantity', 0)), models.Q(('refund_amount_fen__gte', 0), ('refund_quantity__gt', 0)), _connector='OR'), name='return_refund_shape'),
        ),
        migrations.AddField(
            model_name='benefitonlysettlement',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordershippingrefundclaim',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='aftersales.aftersalecase'),
        ),
        migrations.AddConstraint(
            model_name='refundamountsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('total_fen', django.db.models.expressions.CombinedExpression(models.F('goods_fen'), '+', models.F('shipping_fen')))), name='refund_amount_components'),
        ),
        migrations.AddConstraint(
            model_name='benefitonlysettlement',
            constraint=models.UniqueConstraint(fields=('actor', 'request_key'), name='benefit_settlement_actor_key'),
        ),
        migrations.AddConstraint(
            model_name='ordershippingrefundclaim',
            constraint=models.CheckConstraint(condition=models.Q(('amount_fen__gt', 0)), name='shipping_refund_positive'),
        ),
    ]
